/**
 * The submit seam for the Request Talent form: one insert into `leads`,
 * as a website lead, straight from the visitor's browser.
 *
 * Why the browser and not our server: the rate limit (migration 9) keys on
 * the client address Supabase's edge records. Through our server every
 * visitor would share one address and one limit. See CLAUDE.md, "Three
 * clients, one job each".
 *
 * anon may INSERT the form's columns of `leads` and nothing else, and may
 * SELECT nothing - not even the row it just wrote. So the insert asks for no
 * representation back (`return=minimal`, supabase-js's default when
 * `.select()` is not chained). The insert policy only admits a new,
 * unowned `website_form` lead, so `source` is the one column set here that
 * the visitor did not type.
 *
 * `submissionKey` is generated by the form once per submission and resent
 * on every retry of it, so a retry after a dropped connection is recognised
 * and stores nothing twice.
 *
 * NOTHING IS LOGGED. This used to console.log the payload while the form was
 * unwired; now it carries a real person's details to a real database.
 *
 * Whether the form calls this at all is the forms gate's decision
 * (src/lib/supabase/forms-gate.ts): a closed form never reaches here.
 */

import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
import { toIntakeResult, type IntakeResult } from "@/lib/supabase/intake-result";

export type RequisitionPayload = {
  /** A UUID, generated once per submission and resent on its retries. */
  submissionKey: string;
  /**
   * A spam trap tripped more than once in this attempt. The row is stored
   * and held for staff review, never refused (migration 13).
   */
  trapTripped: boolean;
  contact: {
    fullName: string;
    workEmail: string;
    phone: string;
    companyName: string;
    /** Optional; empty string when not given. */
    jobTitle: string;
  };
  role: {
    title: string;
    /** Engagement model id, e.g. "direct-hire". */
    service: string;
    /** "<area>:<sub-specialty>", e.g. "healthcare:nursing". */
    specialty: string;
    location: { city: string; state: string };
    /** "onsite" | "hybrid" | "remote". */
    workMode: string;
    positions: number;
    /** ISO date, or null when the start date is open. */
    targetStartDate: string | null;
    compensation: {
      min: number | null;
      max: number | null;
      /** "hour" | "year", or null when no range was given. */
      unit: string | null;
    };
    /** Optional; empty string when not given. */
    additionalRequirements: string;
  };
};

export type SubmitResult = IntakeResult;

export async function submitRequisition(payload: RequisitionPayload): Promise<SubmitResult> {
  const { contact, role } = payload;
  // The taxonomy's "<desk>:<specialty>" pair, as the two columns the
  // database keys it on (leads_specialty_on_desk).
  const [desk, specialty] = role.specialty.split(":");
  try {
    const supabase = createBrowserSupabaseClient();
    const { error, status } = await supabase.from("leads").insert({
      source: "website_form",
      submission_key: payload.submissionKey,
      trap_tripped: payload.trapTripped,
      contact_name: contact.fullName,
      contact_email: contact.workEmail,
      contact_phone: contact.phone,
      company_name: contact.companyName,
      contact_title: contact.jobTitle === "" ? null : contact.jobTitle,
      role_title: role.title,
      requested_service: role.service,
      desk,
      specialty,
      city: role.location.city,
      state: role.location.state,
      work_mode: role.workMode,
      positions: role.positions,
      target_start: role.targetStartDate,
      salary_min: role.compensation.min,
      salary_max: role.compensation.max,
      salary_unit: role.compensation.unit,
      submitted_details: role.additionalRequirements === "" ? null : role.additionalRequirements,
    });
    return toIntakeResult({ error, status });
  } catch {
    // The client could not be constructed, or the request threw before
    // PostgREST answered. Either way nothing we can confirm was stored.
    return { ok: false, reason: "failed" };
  }
}
