/**
 * The submit seam for the general contact form: one insert into
 * `contact_messages`, straight from the visitor's browser.
 *
 * Why the browser and not our server: the rate limit (migration 9) keys on
 * the client address Supabase's edge records. Through our server every
 * visitor would share one address and one limit. See CLAUDE.md, "Three
 * clients, one job each".
 *
 * anon may INSERT the form's columns and nothing else, and may SELECT
 * nothing - not even the row it just wrote. So the insert asks for no
 * representation back (`return=minimal`, supabase-js's default when
 * `.select()` is not chained).
 *
 * `submissionKey` is generated by the form once per submission and resent
 * on every retry of it, so a retry after a dropped connection is recognised
 * and stores nothing twice.
 *
 * NOTHING IS LOGGED. This used to console.log the payload while the form was
 * unwired; now it carries a real person's message to a real database.
 *
 * Whether the form calls this at all is the forms gate's decision
 * (src/lib/supabase/forms-gate.ts): a closed form never reaches here.
 */

import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
import { toIntakeResult, type IntakeResult } from "@/lib/supabase/intake-result";

export type ContactPayload = {
  /** A UUID, generated once per submission and resent on its retries. */
  submissionKey: string;
  /**
   * A spam trap tripped more than once in this attempt. The row is stored
   * and held for staff review, never refused (migration 13).
   */
  trapTripped: boolean;
  fullName: string;
  email: string;
  /** Optional; empty string when not given. */
  phone: string;
  /** "employer" | "job-seeker". Routes the message to the right desk. */
  enquiryType: string;
  subject: string;
  message: string;
};

export type SubmitResult = IntakeResult;

export async function submitContact(payload: ContactPayload): Promise<SubmitResult> {
  try {
    const supabase = createBrowserSupabaseClient();
    const { error, status } = await supabase.from("contact_messages").insert({
      submission_key: payload.submissionKey,
      trap_tripped: payload.trapTripped,
      full_name: payload.fullName,
      email: payload.email,
      phone: payload.phone === "" ? null : payload.phone,
      enquiry_type: payload.enquiryType,
      subject: payload.subject,
      message: payload.message,
    });
    return toIntakeResult({ error, status });
  } catch {
    // The client could not be constructed, or the request threw before
    // PostgREST answered. Either way nothing we can confirm was stored.
    return { ok: false, reason: "failed" };
  }
}
