/**
 * GENERATED by scripts/import-articles.ts from "AI Hiring Laws Employers Must Know in 2027.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "ai-hiring-laws",
  "slug": "ai-hiring-laws",
  "title": "AI Hiring Laws Employers Must Know in 2027",
  "metaTitle": "AI Hiring Laws Employers Must Know in 2027",
  "metaDescription": "AI hiring laws in 2027: Illinois, Colorado (effective Jan 1, 2027), New York City and California rules, plus a compliance checklist. Not legal advice.",
  "summary": "As of January 2027, employers using AI in hiring face specific rules in Illinois, Colorado, New York City and California, on top of federal and state anti-discrimination laws that apply to any hiring method. The common requirements are telling candidates when AI is used, avoiding discriminatory outcomes, testing tools for bias, offering human review, and keeping records. These rules apply to healthcare employers the same way they apply to others.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Illinois (in force since January 1, 2026): notice when AI is used in employment decisions; no discriminatory use.",
      "Colorado (effective January 1, 2027): notice, post-decision explanations, human review and three-year record-keeping for automated decision-making technology.",
      "New York City: bias audits and notices for automated employment decision tools.",
      "California: regulations on automated-decision systems in employment in effect since October 1, 2025.",
      "Using a vendor's tool doesn't transfer your responsibility for the outcome."
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "This article is general information, not legal advice."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "AI hiring laws at a glance"
    },
    {
      "kind": "table",
      "header": [
        "Jurisdiction",
        "Law",
        "Status",
        "Core requirements"
      ],
      "rows": [
        [
          "Illinois",
          "HB 3773 (amends the Illinois Human Rights Act)",
          "In force since January 1, 2026",
          "Notify applicants and employees when AI is used in hiring and other employment decisions; no AI use with discriminatory effect; no zip codes as a proxy for protected classes"
        ],
        [
          "Colorado",
          "SB 26-189 (signed May 14, 2026)",
          "Effective January 1, 2027",
          "Advance notice; explanation within 30 days after an adverse outcome; a process for human review; records kept at least three years; accessible notices; vendor disclosures"
        ],
        [
          "New York City",
          "Local Law 144",
          "In force",
          "Independent bias audits of automated employment decision tools; public audit summaries; candidate notices"
        ],
        [
          "California",
          "Civil Rights Council regulations on automated-decision systems",
          "In effect since October 1, 2025",
          "Applies existing discrimination law to automated tools; bias testing relevant to claims; extended record-keeping"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Sources: K&L Gates, Seyfarth Shaw, NYC Department of Consumer and Worker Protection. Details summarized; check the official text for your obligations."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Illinois: notice and non-discrimination"
    },
    {
      "kind": "paragraph",
      "text": "Illinois HB 3773 makes it a civil rights violation to use AI in a way that has a discriminatory effect on applicants or employees in recruitment, hiring, promotion and other employment decisions. Employers must give notice when AI is used for these decisions, and may not use zip codes as a proxy for protected characteristics. The notice duty applies even if the tool produces no discriminatory outcome."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Colorado: a new framework from 2027"
    },
    {
      "kind": "paragraph",
      "text": "Colorado's original AI Act never took effect. It was repealed and replaced by SB 26-189, signed on May 14, 2026 and effective January 1, 2027. For employers using automated decision-making technology in employment decisions, it requires:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Advance notice, with a way to request more information"
        },
        {
          "text": "A plain-language explanation within 30 days after an adverse decision, including the role the technology played"
        },
        {
          "text": "A process to request meaningful human review and reconsideration"
        },
        {
          "text": "Records kept for at least three years"
        },
        {
          "text": "Notices accessible to people with disabilities and limited English proficiency"
        },
        {
          "text": "Vendor contracts that provide the necessary disclosures about how tools work"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "New York City: bias audits"
    },
    {
      "kind": "paragraph",
      "text": "NYC's Local Law 144 requires employers using automated employment decision tools for candidates or employees in the city to have the tool independently audited for bias, publish a summary of the results, and notify candidates."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "California: existing discrimination law applied to automation"
    },
    {
      "kind": "paragraph",
      "text": "California's Civil Rights Council regulations, effective October 1, 2025, clarify how state anti-discrimination law applies to automated-decision systems in employment. They make bias testing (or its absence) relevant to discrimination claims and extend record-keeping requirements."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "A compliance checklist for healthcare employers"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Inventory every tool in your hiring process that uses AI or automation, including features inside your applicant tracking system and vendor services."
        },
        {
          "text": "Classify each use: administrative (scheduling, reminders) vs. decision-influencing (ranking, screening, rejecting)."
        },
        {
          "text": "Map where you hire. Obligations follow the location of candidates and roles."
        },
        {
          "text": "Update candidate notices for each jurisdiction."
        },
        {
          "text": "Request bias-testing documentation from vendors."
        },
        {
          "text": "Set up human review for any automated recommendation that affects a candidate."
        },
        {
          "text": "Keep records for at least three years."
        },
        {
          "text": "Review quarterly. More states are considering similar laws."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What this means for healthcare hiring"
    },
    {
      "kind": "paragraph",
      "text": "Healthcare employers often hire across state lines and use high-volume tools for roles such as CNAs and patient care technicians. That makes a tool inventory especially important. For clinical roles, a human conversation before interviews remains the most reliable way to judge fit, and it also reduces reliance on automated screening."
    },
    {
      "kind": "paragraph",
      "text": "For a broader view, see AI in healthcare recruitment: what employers need to know.",
      "links": [
        {
          "start": 24,
          "end": 81,
          "href": "/insights/ai-in-healthcare-recruitment"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Which states regulate AI in hiring?",
      "answer": [
        {
          "text": "As of January 2027, Illinois and Colorado have AI-specific employment laws, New York City requires bias audits, and California has regulations on automated-decision systems. Other states are considering similar rules."
        }
      ]
    },
    {
      "question": "When does Colorado's AI law take effect?",
      "answer": [
        {
          "text": "Colorado SB 26-189 takes effect January 1, 2027. It replaced the state's earlier AI Act, which never took effect."
        }
      ]
    },
    {
      "question": "Do I have to tell candidates I use AI in hiring?",
      "answer": [
        {
          "text": "In Illinois, Colorado and New York City, notice is required in covered situations. Even where it isn't required, transparency builds trust."
        }
      ]
    },
    {
      "question": "Am I responsible if a vendor's AI tool discriminates?",
      "answer": [
        {
          "text": "Generally yes. Employers remain responsible for employment decisions, including those informed by third-party tools. Consult legal counsel."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "K&L Gates, Navigating the AI Employment Landscape in 2026",
      "url": "https://www.klgates.com/thought-leadership/Navigating-the-AI-Employment-Landscape-in-2026-Considerations-and-Best-Practices-for-Employers-2-2-2026"
    },
    {
      "name": "Epstein Becker Green, Workplace AI Regulation in 2026",
      "url": "https://www.ebglaw.com/insights/publications/workplace-ai-regulation-in-2026-how-employers-can-navigate-the-changing-legal-landscape"
    },
    {
      "name": "Seyfarth Shaw, Colorado Enacts Artificial Intelligence Replacement Law",
      "url": "https://www.seyfarth.com/news-insights/colorado-enacts-artificial-intelligence-replacement-law.html"
    },
    {
      "name": "Seyfarth Shaw, AI Legal Roundup (California regulations and Illinois law)",
      "url": "https://www.seyfarth.com/news-insights/artificial-intelligence-legal-roundup-colorado-postpones-implementation-of-ai-law-as-california-finalizes-new-employment-discrimination-regulations-and-illinois-disclosure-law-set-to-take-effect.html"
    },
    {
      "name": "Colorado General Assembly, SB26-189",
      "url": "https://leg.colorado.gov/bills/sb26-189"
    },
    {
      "name": "NYC Department of Consumer and Worker Protection, Automated Employment Decision Tools",
      "url": "https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page"
    }
  ],
  "related": [
    "healthcare-hiring-trends-2027",
    "healthcare-hiring-process"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
