/**
 * GENERATED by scripts/import-articles.ts from "How AI Is Changing Administrative, Accounting and HR Roles (and What to Hire For).docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "@/features/articles";

export const article: Article = {
  "id": "ai-impact-admin-finance-hr-roles",
  "slug": "ai-impact-admin-finance-hr-roles",
  "title": "How AI Is Changing Administrative, Accounting and HR Roles (and What to Hire For)",
  "metaTitle": "How AI Is Changing Admin, Accounting and HR Roles",
  "metaDescription": "How AI is changing administrative, accounting and HR jobs: BLS projections, which tasks are shifting, early-career effects and what to hire for now.",
  "summary": "AI and automation are shrinking routine clerical work (document preparation, data entry, basic bookkeeping) while demand grows for people who can analyze, decide, manage systems and work with others. BLS projects employment of secretaries and administrative assistants to fall 2% and bookkeeping clerks 6% from 2025 to 2035, while accountants (+5%), HR specialists (+6%) and financial managers (+10%) grow. For employers, the shift means rewriting job descriptions and hiring for judgment and systems skills, not just task completion.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "BLS cites AI and digital tools as a reason for the projected decline in administrative assistant jobs.",
      "Analytical and leadership roles in finance and HR continue to grow.",
      "Stanford researchers found the AI-related employment gap is concentrated among workers aged 22 to 25; experienced workers show no comparable gap.",
      "Hire for judgment, data literacy, systems skills and communication."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What official projections show"
    },
    {
      "kind": "table",
      "header": [
        "Role (BLS)",
        "Growth, 2025–35",
        "Annual openings",
        "BLS outlook note"
      ],
      "rows": [
        [
          "Secretaries and administrative assistants",
          "-2%",
          "About 314,400",
          "AI systems and digital tools let staff prepare their own documents; managers handle more tasks themselves"
        ],
        [
          "Bookkeeping, accounting and auditing clerks",
          "-6%",
          "About 144,100",
          "Software has automated many tasks"
        ],
        [
          "Accountants and auditors",
          "+5%",
          "About 115,300",
          "Faster than average"
        ],
        [
          "Human resources specialists",
          "+6%",
          "About 73,700",
          "Faster than average"
        ],
        [
          "Human resources managers",
          "+6%",
          "About 16,800",
          "Faster than average"
        ],
        [
          "Financial managers",
          "+10%",
          "About 65,600",
          "Much faster than average"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: BLS Occupational Outlook Handbook, 2025–35 projections. Even declining occupations have many openings each year because people retire or change careers."
    },
    {
      "kind": "paragraph",
      "text": "In August 2026, BLS also published AI exposure categories (\"low,\" \"moderate,\" \"high\" and \"very high\") for 831 occupations, based on how much of each occupation's work AI can complete or assist."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Which tasks are changing"
    },
    {
      "kind": "table",
      "header": [
        "Function",
        "Tasks AI increasingly supports",
        "Tasks that remain human-led"
      ],
      "rows": [
        [
          "Administrative",
          "Drafting documents, scheduling, summarizing, data entry",
          "Managing priorities, stakeholder coordination, confidential judgment"
        ],
        [
          "Accounting",
          "Transaction coding, reconciliations, report drafts",
          "Reviewing exceptions, interpreting results, controls, advising leaders"
        ],
        [
          "HR",
          "Drafting job descriptions and policies, answering routine questions",
          "Employee relations, investigations, coaching, workforce decisions"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The early-career effect"
    },
    {
      "kind": "paragraph",
      "text": "Stanford's Digital Economy Lab (August 2026 update, using ADP payroll data) found employment for workers aged 22 to 25 in highly AI-exposed occupations was about 19% below where it would have been had it kept pace with less-exposed peers. Experienced workers showed no comparable gap. The researchers describe the patterns as descriptive rather than causal, and suggest the effect appears mainly through reduced hiring rather than layoffs."
    },
    {
      "kind": "paragraph",
      "text": "The World Economic Forum's Future of Jobs Report 2025 similarly expects administrative assistants to be among the jobs with the largest absolute declines by 2030."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What to hire for now"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Judgment and exception handling: spotting what's wrong, not just processing what's right"
        },
        {
          "text": "Data literacy: reading reports, questioning numbers, building simple analyses"
        },
        {
          "text": "Systems fluency: ERP, HRIS and workflow tools, plus the ability to learn new ones"
        },
        {
          "text": "Communication: explaining findings and coordinating across teams"
        },
        {
          "text": "Responsible AI use: using tools efficiently while checking their output"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to update job descriptions"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Replace task lists (\"types correspondence\") with outcomes (\"coordinates executive priorities and communications\")"
        },
        {
          "text": "Name the systems the person will use"
        },
        {
          "text": "Include analysis or improvement responsibilities where relevant"
        },
        {
          "text": "Keep genuine requirements (such as a CPA license) clearly stated"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "See skills-based hiring for non-IT roles for how to assess these skills.",
      "links": [
        {
          "start": 4,
          "end": 40,
          "href": "/insights/skills-based-hiring"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "A note on AI in your own hiring process"
    },
    {
      "kind": "paragraph",
      "text": "If you use AI tools to screen or rank candidates, several jurisdictions now regulate how. Illinois requires notice, and Colorado's new rules take effect January 1, 2027. Keep people responsible for hiring decisions."
    }
  ],
  "faqs": [
    {
      "question": "Will AI replace administrative assistants?",
      "answer": [
        {
          "text": "BLS projects a 2% decline in employment from 2025 to 2035, not elimination, with about 314,400 openings a year. Roles are shifting toward coordination and judgment."
        }
      ]
    },
    {
      "question": "Is accounting at risk from AI?",
      "answer": [
        {
          "text": "Routine bookkeeping is declining (BLS: -6% for clerks), but accountant and auditor employment is projected to grow 5%, and financial manager employment 10%."
        }
      ]
    },
    {
      "question": "What skills should employers look for in administrative and finance roles?",
      "answer": [
        {
          "text": "Judgment, data literacy, systems fluency, communication and responsible use of AI tools."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Secretaries and Administrative Assistants",
      "url": "https://www.bls.gov/ooh/office-and-administrative-support/secretaries-and-administrative-assistants.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Bookkeeping, Accounting, and Auditing Clerks",
      "url": "https://www.bls.gov/ooh/office-and-administrative-support/bookkeeping-accounting-and-auditing-clerks.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Accountants and Auditors",
      "url": "https://www.bls.gov/ooh/business-and-financial/accountants-and-auditors.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Human Resources Specialists",
      "url": "https://www.bls.gov/ooh/business-and-financial/human-resources-specialists.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Human Resources Managers",
      "url": "https://www.bls.gov/ooh/management/human-resources-managers.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Financial Managers",
      "url": "https://www.bls.gov/ooh/management/financial-managers.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, AI exposure categories (August 2026)",
      "url": "https://www.bls.gov/emp/publications/ai-exposure-categories.htm"
    },
    {
      "name": "Stanford Digital Economy Lab, Canaries in the Coal Mine update (August 12, 2026)",
      "url": "https://digitaleconomy.stanford.edu/news/canariesaug26/"
    },
    {
      "name": "World Economic Forum, Future of Jobs Report 2025, as reported by Staffing Industry Analysts",
      "url": "https://www.staffingindustry.com/news/global-daily-news/world-to-add-170-million-jobs-by-2030-lose-92-million"
    },
    {
      "name": "Seyfarth Shaw, Colorado Enacts Artificial Intelligence Replacement Law",
      "url": "https://www.seyfarth.com/news-insights/colorado-enacts-artificial-intelligence-replacement-law.html"
    }
  ],
  "related": [
    "entry-level-hiring-2027",
    "hiring-accountants-cpa-pathway"
  ],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
