/**
 * GENERATED by scripts/import-articles.ts from "How to Choose a Healthcare Recruitment Partner - 12 Questions to Ask.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "choose-healthcare-recruitment-partner",
  "slug": "choose-healthcare-recruitment-partner",
  "title": "How to Choose a Healthcare Recruitment Partner: 12 Questions to Ask",
  "metaTitle": "How to Choose a Healthcare Recruitment Partner: 12 Questions",
  "metaDescription": "12 questions to ask before choosing a healthcare recruitment partner: services, exclusions, screening, fees, terms and red flags, plus our own answers.",
  "summary": "The best way to choose a healthcare recruitment partner is to ask specific questions about what they do, what they don't do, how they charge, and how they'll run your search, and then compare the answers in writing. A good partner answers plainly, is clear about the limits of its service, and doesn't promise outcomes no one can guarantee.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Ask exactly which steps the firm handles and which stay with you, especially license verification and background checks.",
      "Get fees, payment timing and any replacement terms in writing before a search opens.",
      "Be cautious of promises such as guaranteed hires or \"fully vetted\" candidates without a clear explanation of what that means.",
      "We've included Talentrax's own answers below for transparency."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "The 12 questions"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "About the service"
    },
    {
      "kind": "paragraph",
      "text": "1. Which staffing model do you offer? Direct hire, travel, per diem, locum tenens or contract-to-hire. Make sure the firm's model matches your need."
    },
    {
      "kind": "paragraph",
      "text": "2. Which steps of the search do you handle? For example: role scoping, sourcing, screening, resume submission, interview scheduling, feedback, offer support."
    },
    {
      "kind": "paragraph",
      "text": "3. What don't you do? License verification, credential checks, background and reference checks are sometimes included and sometimes not. Gaps here create compliance risk."
    },
    {
      "kind": "paragraph",
      "text": "4. Which roles and settings do you recruit for? Nursing, allied health and non-clinical roles require different networks and knowledge."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "About the search"
    },
    {
      "kind": "paragraph",
      "text": "5. How do you find candidates? Look for active outreach to employed candidates, not only job postings."
    },
    {
      "kind": "paragraph",
      "text": "6. What does your screening involve? Ask what's checked before a resume reaches you: experience, interest in the role, availability, salary expectations."
    },
    {
      "kind": "paragraph",
      "text": "7. How will you communicate during the search? Agree on update frequency and a single point of contact."
    },
    {
      "kind": "paragraph",
      "text": "8. What do you need from us? A good partner will ask for an approved position, a realistic salary range and committed interview times."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "About cost and terms"
    },
    {
      "kind": "paragraph",
      "text": "9. How do you charge? For direct hire, typically a one-time percentage of first-year base salary. Ask what salary figure it's based on and when it's invoiced. See how direct-hire placement fees work.",
      "links": [
        {
          "start": 163,
          "end": 198,
          "href": "/insights/direct-hire-placement-fees"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "10. What happens if a hire leaves early? Some agreements include a replacement or refund period; terms vary. Get it in writing."
    },
    {
      "kind": "paragraph",
      "text": "11. How long does candidate ownership last? If you hire someone the firm presented months later, will a fee apply?"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "About trust"
    },
    {
      "kind": "paragraph",
      "text": "12. What claims can you back up? Be wary of guarantees about outcomes, fill times or candidate quality that aren't supported by documented data."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How Talentrax answers"
    },
    {
      "kind": "table",
      "header": [
        "Question",
        "Talentrax's answer"
      ],
      "rows": [
        [
          "Staffing model",
          "Direct-hire recruitment only"
        ],
        [
          "Steps we handle",
          "Helping scope the role, sourcing and screening candidates, submitting resumes and scheduling interviews"
        ],
        [
          "What we don't do",
          "License and credential verification, background checks, contract or temporary staffing"
        ],
        [
          "Roles",
          "Nursing, allied health, clinical support and non-clinical healthcare roles"
        ],
        [
          "Fees and terms",
          "Ask us about fee terms for your role"
        ],
        [
          "Guarantees",
          "We don't guarantee hires; we explain our process so you know what to expect"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Red flags to watch for"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Promises of guaranteed hires or unrealistically fast fill times"
        },
        {
          "text": "Vague answers about what screening includes"
        },
        {
          "text": "Claims of \"pre-vetted\" or \"fully credentialed\" candidates without explaining who verified what"
        },
        {
          "text": "Pressure to sign before terms are clear"
        },
        {
          "text": "No questions about your role, team or salary range"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "What should I ask a healthcare staffing agency?",
      "answer": [
        {
          "text": "Ask which model they offer, which steps they handle, what they don't do, how they source and screen, how they charge, and what happens if a hire leaves early."
        }
      ]
    },
    {
      "question": "Should a recruitment agency verify nursing licenses?",
      "answer": [
        {
          "text": "Some do and some don't. Confirm in writing who is responsible. Talentrax does not provide license verification; employers typically verify through state boards or Nursys."
        }
      ]
    },
    {
      "question": "How are healthcare recruiters paid?",
      "answer": [
        {
          "text": "Direct-hire recruiters are typically paid a one-time fee based on the new hire's first-year base salary, usually after the hire starts."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "Industry fee benchmarks (2026): RecruitBPM, \"Recruitment Fees in 2026\"",
      "url": "https://recruitbpm.com/blog/recruitment-fees"
    },
    {
      "name": "NCSBN Nursys",
      "url": "https://www.nursys.com"
    }
  ],
  "related": [
    "direct-hire-healthcare-recruitment",
    "direct-hire-recruitment-process"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
