/**
 * GENERATED by scripts/import-articles.ts from "Direct Hire vs. Travel Nurses - A Total Cost Comparison for Hospitals.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "direct-hire-vs-travel-nurse-cost",
  "slug": "direct-hire-vs-travel-nurse-cost",
  "title": "Direct Hire vs. Travel Nurses: A Total Cost Comparison for Hospitals",
  "metaTitle": "Travel Nurse vs. Staff Nurse Cost: 2026 Hospital Comparison",
  "metaDescription": "Travel nurses cost hospitals about $66,000 more a year than staff RNs (NSI 2026). See the full cost comparison, a worked example and when travel still fits.",
  "summary": "On average, a travel nurse costs a US hospital about $66,000 more per year than an employed staff RN. The 2026 NSI National Health Care Retention & RN Staffing Report puts the average hospital travel nurse fee at $91.23 an hour, compared with $59.46 an hour for a staff RN including benefits. Even after a one-time direct-hire placement fee, a permanent hire usually costs less within the first year, provided the position is filled and the nurse stays.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Average travel nurse fee: $91.23/hour. Average staff RN cost: $59.46/hour including benefits (NSI, 2026 report).",
      "That gap is about $66,000 a year for one full-time position.",
      "A direct-hire placement fee is a one-time cost; the travel premium repeats every assignment.",
      "Direct hire carries its own risk: 22.7% of newly hired RNs leave within a year (NSI, 2026 report). Hiring for fit matters."
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "This article breaks down both sides of the comparison, including the costs that don't appear in the hourly rate and the situations where travel staffing is still the right choice."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What does a travel nurse cost compared with a staff nurse?"
    },
    {
      "kind": "table",
      "header": [
        "Cost measure",
        "Travel nurse",
        "Staff RN (employed)",
        "Difference"
      ],
      "rows": [
        [
          "Average hourly cost to the hospital",
          "$91.23 (fee)",
          "$59.46 (pay plus 25.8% benefits)",
          "$31.77/hour"
        ],
        [
          "Annualized per full-time position",
          "$189,758",
          "$123,676",
          "$66,081/year"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report. Hospital survey averages; your costs will vary by market and specialty."
    },
    {
      "kind": "paragraph",
      "text": "NSI also reports that travel rates range up to about $160 an hour, so in high-cost markets or hard-to-fill specialties the gap can be far larger than the average."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Costs that don't show up in the hourly rate"
    },
    {
      "kind": "paragraph",
      "text": "The hourly comparison captures the biggest difference, but not all of it. Both models carry costs that are easy to overlook."
    },
    {
      "kind": "paragraph",
      "text": "Travel staffing"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Repeated orientation. Each new traveler needs unit orientation, system access and time to learn local protocols, and many assignments are short."
        },
        {
          "text": "Continuity. Frequent turnover of contract staff can affect team cohesion and the knowledge a unit builds over time."
        },
        {
          "text": "Budget uncertainty. Rates move with demand, so costs can rise quickly when the market tightens."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Direct hire"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Placement fee. Usually a one-time percentage of first-year base salary. Published 2026 industry benchmarks commonly place it between 15% and 30%."
        },
        {
          "text": "Onboarding and orientation. Your own investment in a new employee, which pays back only if they stay."
        },
        {
          "text": "Time to fill. Hospitals take an average of 78 days to recruit an experienced RN (NSI, 2026 report). Coverage is still needed while the search runs."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Worked example: one RN position over 12 months"
    },
    {
      "kind": "paragraph",
      "text": "The example below uses NSI's 2026 hospital averages and an illustrative 20% placement fee on the BLS median RN wage of $97,550 (May 2025). It assumes the permanent hire starts at the beginning of the year and stays."
    },
    {
      "kind": "table",
      "header": [
        "",
        "Travel nurse (full year)",
        "Direct hire (year one)",
        "Direct hire (year two)"
      ],
      "rows": [
        [
          "Labor cost",
          "$189,758",
          "$123,676",
          "$123,676"
        ],
        [
          "Placement fee (illustrative 20%)",
          "Not applicable",
          "$19,510",
          "None"
        ],
        [
          "Total",
          "$189,758",
          "$143,186",
          "$123,676"
        ],
        [
          "Difference vs. travel",
          "",
          "About $46,600 lower",
          "About $66,100 lower"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Two cautions keep this example honest:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "The search takes time. If a position needs travel coverage for part of the year while you recruit, first-year savings are smaller."
        },
        {
          "text": "Salaries vary. A higher base salary means a higher percentage-based fee, and local pay can differ sharply from the national median."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "NSI, which is itself a nurse recruitment firm, runs a similar calculation at scale: replacing 20 travel nurses with employed RNs saves the average hospital about $1.32 million a year. That estimate doesn't subtract placement fees or account for time to fill, so treat it as an upper-bound illustration."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "When travel staffing still makes sense"
    },
    {
      "kind": "paragraph",
      "text": "Direct hire isn't always the answer. Travel or other contingent staffing is often the better tool when:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "The need is temporary, such as seasonal census peaks, leave coverage or a short project."
        },
        {
          "text": "You need coverage immediately and can't wait for a permanent search and notice period."
        },
        {
          "text": "You're covering a gap while a permanent search runs. Travel coverage can bridge the months until a new hire starts."
        },
        {
          "text": "Demand is uncertain, for example a new service line whose volume isn't yet proven."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Many hospitals now combine approaches: permanent staff for core positions, internal float pools for day-to-day swings, and contract labor for true short-term gaps."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The risk on the direct-hire side: early turnover"
    },
    {
      "kind": "paragraph",
      "text": "The savings in a direct-hire model depend on the new employee staying. According to the NSI 2026 report:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "22.7% of newly hired RNs left within their first year."
        },
        {
          "text": "The average cost of one bedside RN turnover is $60,090."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "That doesn't erase the case for permanent hiring, but it changes how you hire. Confirming a candidate's genuine interest, schedule fit and salary expectations before interviews, and investing in onboarding afterward, protect the savings. Read more in our guide to nurse turnover statistics.",
      "links": [
        {
          "start": 264,
          "end": 289,
          "href": "/insights/nurse-turnover-statistics"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to use this comparison in your budget"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "List your current travel positions by unit, with bill rates and contract end dates."
        },
        {
          "text": "Identify which are core, ongoing needs rather than temporary gaps."
        },
        {
          "text": "Compare each against the fully loaded cost of a staff RN in your market, plus a placement fee if you use a recruiter."
        },
        {
          "text": "Start permanent searches well before contracts end. With a 78-day average time to fill, begin roughly three months ahead."
        },
        {
          "text": "Track retention of converted positions at 90 days and one year."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "For a step-by-step approach, see our direct-hire transition plan for reducing travel staff. For broader nurse hiring guidance, read how to recruit and hire nurses in 2026.",
      "links": [
        {
          "start": 37,
          "end": 90,
          "href": "/insights/reduce-travel-nurse-reliance"
        },
        {
          "start": 132,
          "end": 170,
          "href": "/insights/how-to-hire-nurses"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Is a travel nurse more expensive than a staff nurse?",
      "answer": [
        {
          "text": "Yes, on average. NSI's 2026 report puts the average travel nurse fee at $91.23 an hour versus $59.46 an hour for a staff RN including benefits, a difference of about $66,000 a year per full-time position."
        }
      ]
    },
    {
      "question": "How much does a hospital pay for a travel nurse?",
      "answer": [
        {
          "text": "The NSI 2026 hospital average is $91.23 an hour, with rates ranging up to about $160 an hour depending on market and specialty."
        }
      ]
    },
    {
      "question": "How much can a hospital save by replacing travel nurses with staff?",
      "answer": [
        {
          "text": "NSI estimates the average hospital saves about $1.32 million a year by replacing 20 travel nurses with employed RNs. Actual savings depend on local pay, placement fees and how long new hires stay."
        }
      ]
    },
    {
      "question": "When should a hospital still use travel nurses?",
      "answer": [
        {
          "text": "For temporary needs, immediate coverage, bridging a vacancy while a permanent search runs, or uncertain demand."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "US Bureau of Labor Statistics, Registered Nurses",
      "url": "https://www.bls.gov/ooh/healthcare/registered-nurses.htm"
    },
    {
      "name": "Industry fee benchmarks (2026): RecruitBPM, \"Recruitment Fees in 2026\"",
      "url": "https://recruitbpm.com/blog/recruitment-fees"
    }
  ],
  "related": [
    "direct-hire-healthcare-recruitment",
    "direct-hire-placement-fees"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
