/**
 * GENERATED by scripts/import-articles.ts from "How Direct-Hire Placement Fees Work.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "direct-hire-placement-fees",
  "slug": "direct-hire-placement-fees",
  "title": "How Direct-Hire Placement Fees Work",
  "metaTitle": "How Direct-Hire Placement Fees Work (Healthcare, 2026)",
  "metaDescription": "What direct-hire placement fees cost, how they're calculated, contingency vs. retained, and how the fee compares with travel staffing costs.",
  "summary": "A direct-hire placement fee is a one-time payment an employer makes to a recruiting firm when a candidate the firm presented is hired into a permanent role. It is usually calculated as a percentage of the new hire's first-year base salary, and under the most common arrangement, contingency, it is due only after the person starts. Published 2026 industry benchmarks commonly put direct-hire fees between 15% and 30% of first-year base salary.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Direct-hire fees are one-time, not ongoing.",
      "Contingency fees are paid only if you hire; retained fees are partly paid up front.",
      "The percentage depends on role difficulty, seniority, location and volume.",
      "Compare the fee with the cost of leaving the role open or covering it with travel staff."
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "This guide explains how fees are calculated, the main fee structures, what drives the percentage, and how to compare the cost with the alternatives."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How is a direct-hire placement fee calculated?"
    },
    {
      "kind": "paragraph",
      "text": "The fee is usually a percentage of the candidate's first-year base salary. Some agreements also count guaranteed bonuses or sign-on payments, so check the definition in your contract."
    },
    {
      "kind": "paragraph",
      "text": "Worked example: The median annual wage for registered nurses was $97,550 in May 2025 (BLS). At an illustrative 20% fee, the placement fee for an RN hired at that salary would be $19,510, paid once."
    },
    {
      "kind": "table",
      "header": [
        "Base salary",
        "15% fee",
        "20% fee",
        "25% fee"
      ],
      "rows": [
        [
          "$60,000",
          "$9,000",
          "$12,000",
          "$15,000"
        ],
        [
          "$80,000",
          "$12,000",
          "$16,000",
          "$20,000"
        ],
        [
          "$97,550 (RN median, BLS)",
          "$14,633",
          "$19,510",
          "$24,388"
        ],
        [
          "$120,000",
          "$18,000",
          "$24,000",
          "$30,000"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "These are examples only; your actual fee depends on your agreement."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What are the main types of placement fee?"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Contingency"
    },
    {
      "kind": "paragraph",
      "text": "You pay only if you hire a candidate the recruiter presented. There is no up-front cost. Contingency is widely used for nursing, allied health, clinical support and administrative roles."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Retained"
    },
    {
      "kind": "paragraph",
      "text": "You pay part of the fee up front to secure the recruiter's dedicated time, with the rest due at later milestones. This is typically used for senior leadership searches."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Engaged or container search"
    },
    {
      "kind": "paragraph",
      "text": "A hybrid: a smaller up-front payment to commit the recruiter's time, with the balance due at placement."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What affects the fee percentage?"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Difficulty of the role: hard-to-fill specialties and niche allied roles take more sourcing effort."
        },
        {
          "text": "Seniority: leadership roles usually carry higher percentages."
        },
        {
          "text": "Location: rural and remote locations can require wider searches. HRSA projects RN shortages in nonmetropolitan areas to remain well above those in metro areas through 2038."
        },
        {
          "text": "Volume: some firms adjust fees when an employer has several openings."
        },
        {
          "text": "Exclusivity: giving one recruiter exclusive responsibility for a role may affect the terms."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "When is the fee paid?"
    },
    {
      "kind": "paragraph",
      "text": "Under a typical contingency agreement:"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "The recruiter presents the candidate."
        },
        {
          "text": "You interview, verify and hire."
        },
        {
          "text": "The candidate starts work."
        },
        {
          "text": "The recruiter invoices the fee, with payment terms set by the agreement."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Many agreements also include a replacement or refund period that applies if the new hire leaves within a set time. Terms vary widely between firms, so read this clause carefully and get it in writing."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Is a direct-hire fee worth it? Comparing the alternatives"
    },
    {
      "kind": "paragraph",
      "text": "The fee is easier to evaluate next to what the vacancy is already costing you."
    },
    {
      "kind": "table",
      "header": [
        "Cost",
        "Figure",
        "Source"
      ],
      "rows": [
        [
          "Average hospital travel nurse fee vs. staff RN pay (incl. benefits)",
          "$91.23/hr vs. $59.46/hr, a difference of about $66,000 a year per full-time position",
          "NSI, 2026 report"
        ],
        [
          "Average cost of one bedside RN turnover",
          "$60,090",
          "NSI, 2026 report"
        ],
        [
          "Average time to recruit an experienced RN",
          "78 days",
          "NSI, 2026 report"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "In other words, a one-time placement fee for a permanent hire can be modest compared with a year of travel-rate premiums or the cost of a new hire leaving early. Cost pressure is also visible in hospital plans: 70.7% say they want to reduce their reliance on travel and agency staff (NSI, 2026 report)."
    },
    {
      "kind": "paragraph",
      "text": "A direct-hire fee is not always the right spend, though. If you only need short-term coverage, or your internal team can fill the role quickly, a recruiter may not be necessary."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Questions to ask before signing a fee agreement"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "What percentage do you charge, and what salary figure is it based on?"
        },
        {
          "text": "Is the agreement contingency or retained?"
        },
        {
          "text": "When is the fee invoiced, and what are the payment terms?"
        },
        {
          "text": "Is there a replacement or refund period, and what are the conditions?"
        },
        {
          "text": "What exactly is included in your service (for example, role scoping, sourcing, screening, resume submission, interview scheduling)?"
        },
        {
          "text": "What is not included, such as license verification or background checks?"
        },
        {
          "text": "How long does candidate ownership last if we hire someone you presented later?"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Do candidates pay direct-hire fees?",
      "answer": [
        {
          "text": "No. In standard direct-hire recruitment, the employer pays the fee."
        }
      ]
    },
    {
      "question": "Is the fee negotiable?",
      "answer": [
        {
          "text": "Often, yes. Rate, payment terms and replacement conditions are commonly discussed before an agreement is signed."
        }
      ]
    },
    {
      "question": "What if we hire a candidate we found ourselves?",
      "answer": [
        {
          "text": "Under most contingency agreements, the fee applies only to candidates the recruiter presented. Confirm how your agreement defines this."
        }
      ]
    },
    {
      "question": "Does Talentrax charge a placement fee?",
      "answer": [
        {
          "text": "Yes. Talentrax works on a direct-hire basis. Contact us to discuss the role you're hiring for and our fee terms.",
          "links": [
            {
              "start": 45,
              "end": 55,
              "href": "/employers/request-talent"
            }
          ]
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "US Bureau of Labor Statistics, Registered Nurses (median pay, May 2025)",
      "url": "https://www.bls.gov/ooh/healthcare/registered-nurses.htm"
    },
    {
      "name": "HRSA, Health Workforce Projections",
      "url": "https://bhw.hrsa.gov/data-research/projecting-health-workforce-supply-demand"
    },
    {
      "name": "Industry fee benchmarks (2026): RecruitBPM, \"Recruitment Fees in 2026\"",
      "url": "https://recruitbpm.com/blog/recruitment-fees"
    },
    {
      "name": "Pin, \"Direct Hire Explained\"",
      "url": "https://www.pin.com/blog/direct-hire-explained/"
    }
  ],
  "related": [
    "direct-hire-healthcare-recruitment",
    "direct-hire-recruitment-process",
    "direct-hire-vs-travel-nurse-cost"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
