/**
 * GENERATED by scripts/import-articles.ts from "Entry-Level Hiring in 2027 - What Employers Should Know About the New-Graduate Market.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "@/features/articles";

export const article: Article = {
  "id": "entry-level-hiring-2027",
  "slug": "entry-level-hiring-2027",
  "title": "Entry-Level Hiring in 2027: What Employers Should Know About the New-Graduate Market",
  "metaTitle": "Entry-Level Hiring in 2027: The New-Graduate Market",
  "metaDescription": "The 2027 new-graduate market: NACE hiring plans up 5.6%, recent-grad unemployment near 5.6%, AI's effect on junior roles and how to design entry-level jobs.",
  "summary": "The market for new graduates is mixed: employers surveyed by NACE planned to hire 5.6% more graduates from the class of 2026, yet the New York Fed reports unemployment for recent college graduates at about 5.6% and underemployment at 42% in mid-2026. Research also suggests AI is reducing hiring into some entry-level roles. For employers, that means capable graduates are available, but entry-level jobs need to be redesigned around what junior employees will actually do as routine tasks are automated.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "NACE employers projected a 5.6% increase in hiring from the class of 2026 (spring 2026 update).",
      "Recent-graduate unemployment was about 5.6% and underemployment 42% in Q2 2026 (New York Fed).",
      "Employment for workers aged 22 to 25 in highly AI-exposed occupations was about 19% below trend in 2026 (Stanford).",
      "Employers that build structured training for junior roles can hire strong graduates in a buyer's market."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What the data shows"
    },
    {
      "kind": "table",
      "header": [
        "Indicator",
        "Figure",
        "Source"
      ],
      "rows": [
        [
          "Projected change in hiring, class of 2026",
          "+5.6%",
          "NACE Job Outlook 2026 Spring Update (185 employers, February to March 2026)"
        ],
        [
          "Unemployment rate, recent college graduates",
          "About 5.6% (Q2 2026)",
          "Federal Reserve Bank of New York"
        ],
        [
          "Underemployment rate, recent college graduates",
          "42% (Q2 2026)",
          "Federal Reserve Bank of New York"
        ],
        [
          "Employment gap, ages 22–25 in highly AI-exposed occupations",
          "About 19% below trend",
          "Stanford Digital Economy Lab (August 2026)"
        ],
        [
          "Employers using skills-based approaches for new graduates",
          "Nearly 70%",
          "NACE (spring 2026)"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "NACE notes hiring plans are uneven across industries. Stanford's researchers describe their findings as descriptive rather than causal, and suggest the effect shows up mainly as reduced hiring rather than job losses."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why entry-level work is changing"
    },
    {
      "kind": "paragraph",
      "text": "Many traditional junior tasks, such as data entry, first-draft documents, basic research and routine reconciliations, are now supported by software and AI. BLS projects declines for administrative assistants (-2%) and bookkeeping clerks (-6%) from 2025 to 2035, partly for these reasons."
    },
    {
      "kind": "paragraph",
      "text": "At the same time, organizations still need a pipeline of people who will become tomorrow's experienced accountants, HR professionals and operations managers. Stanford's research found experienced workers in tacit-knowledge roles saw employment increase, and tacit knowledge is built on the job."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to design entry-level roles now"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Start from future roles. Ask what a senior accountant or operations manager needs to know in three years, and build junior roles that develop it."
        },
        {
          "text": "Pair tasks with review. Let junior staff use tools for first drafts, then learn by reviewing, correcting and explaining the output."
        },
        {
          "text": "Build structured training. Rotations, mentors and clear milestones help new graduates become productive faster."
        },
        {
          "text": "Hire for learning ability. Assess problem-solving, communication and willingness to learn, not just coursework."
        },
        {
          "text": "Use internships as a pipeline. Early exposure helps both sides assess fit."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to recruit new graduates effectively"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Be specific about the job: what they'll do in the first six months and how they'll be trained"
        },
        {
          "text": "Share pay clearly: many states now require ranges in postings"
        },
        {
          "text": "Move quickly: strong graduates often accept the first solid offer"
        },
        {
          "text": "Assess skills directly: short, realistic exercises rather than GPA filters alone. See skills-based hiring",
          "links": [
            {
              "start": 86,
              "end": 105,
              "href": "/insights/skills-based-hiring"
            }
          ]
        },
        {
          "text": "Look beyond your usual schools: capable candidates are graduating from many programs"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Is it a good time to hire recent college graduates?",
      "answer": [
        {
          "text": "For employers, often yes. Recent-graduate unemployment (about 5.6%) and underemployment (42%) were elevated in mid-2026, so capable candidates are available."
        }
      ]
    },
    {
      "question": "Is AI reducing entry-level jobs?",
      "answer": [
        {
          "text": "Research from Stanford's Digital Economy Lab found employment for workers aged 22 to 25 in highly AI-exposed occupations was about 19% below trend, with no comparable gap for experienced workers. The researchers describe this as a pattern, not proof of cause."
        }
      ]
    },
    {
      "question": "Are employers hiring more graduates in 2026?",
      "answer": [
        {
          "text": "NACE's spring 2026 survey found employers projected a 5.6% increase in hiring from the class of 2026."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "NACE, Job Outlook 2026 Spring Update (April 2026)",
      "url": "https://www.naceweb.org/research/reports/2026/job-outlook/spring-update/"
    },
    {
      "name": "Federal Reserve Bank of New York, The Labor Market for Recent College Graduates",
      "url": "https://www.newyorkfed.org/research/college-labor-market"
    },
    {
      "name": "Stanford Digital Economy Lab, Canaries in the Coal Mine update (August 12, 2026)",
      "url": "https://digitaleconomy.stanford.edu/news/canariesaug26/"
    },
    {
      "name": "US Bureau of Labor Statistics, Secretaries and Administrative Assistants",
      "url": "https://www.bls.gov/ooh/office-and-administrative-support/secretaries-and-administrative-assistants.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Bookkeeping, Accounting, and Auditing Clerks",
      "url": "https://www.bls.gov/ooh/office-and-administrative-support/bookkeeping-accounting-and-auditing-clerks.htm"
    }
  ],
  "related": [
    "ai-impact-admin-finance-hr-roles",
    "non-it-hiring-trends-2027"
  ],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
