/**
 * GENERATED by scripts/import-articles.ts from "Why Healthcare Workers Quit in Their First Year.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "first-year-healthcare-turnover",
  "slug": "first-year-healthcare-turnover",
  "title": "Why Healthcare Workers Quit in Their First Year",
  "metaTitle": "Why Healthcare Workers Quit in Their First Year",
  "metaDescription": "22.7% of new hospital RNs leave within a year (NSI 2026). What the data shows, likely reasons, and how to prevent first-year turnover.",
  "summary": "More than one in five newly hired hospital nurses leaves within a year: NSI's 2026 report found 22.7% of new RNs and 29.5% of all new hospital hires left in their first year. The survey doesn't measure why individual new hires leave, but the most common reasons hospital staff give for resigning (personal circumstances, relocation, scheduling conflicts, commute, pay, and workload or staffing ratios) point to mismatches that can often be surfaced before the offer or addressed during onboarding.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "22.7% of newly hired RNs left within a year; first-year exits made up 29.0% of all RN separations (NSI, 2026 report).",
      "Across all hospital roles, 29.5% of new hires left within a year, and first-year exits were 35.6% of all turnover.",
      "Many common reasons for leaving (schedule, commute, pay, workload) can be checked during hiring.",
      "74% of hospitals have a formal retention strategy, and 80.8% report a strategy to protect newly hired nurses (NSI)."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What the data shows"
    },
    {
      "kind": "table",
      "header": [
        "Measure",
        "Registered nurses",
        "All hospital employees"
      ],
      "rows": [
        [
          "New hires who left within a year",
          "22.7%",
          "29.5%"
        ],
        [
          "First-year exits as a share of all separations",
          "29.0%",
          "35.6%"
        ],
        [
          "Employees who left with under two years' service",
          "Not reported separately",
          "56.8%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: NSI, 2026 National Health Care Retention & RN Staffing Report (calendar 2025, 527 hospitals). NSI notes the RN first-year figure includes both experienced and newly graduated nurses and shouldn't be read as new-graduate turnover alone."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why new hires leave"
    },
    {
      "kind": "paragraph",
      "text": "NSI asks hospitals for the top reasons employees resign, not specifically new hires. For staff RNs, the top 10 are: personal issues, relocation, retirement, career advancement, scheduling conflict, education, salary, commute, working conditions, and workload or staffing ratios."
    },
    {
      "kind": "paragraph",
      "text": "Several of these are especially likely to surface early in a new job:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Schedule reality. A rotation, weekend pattern or on-call requirement that wasn't fully understood at hire."
        },
        {
          "text": "Commute. A distance that seemed manageable at the offer becomes tiring on 12-hour shifts."
        },
        {
          "text": "Workload and staffing. Unit conditions that differ from what was described in interviews."
        },
        {
          "text": "Pay relative to alternatives. Especially when another employer offers more after the start date."
        },
        {
          "text": "Support in orientation. Newer nurses in particular may leave if orientation or preceptorship feels rushed."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "These are informed interpretations of NSI's reasons list, not findings from a first-year-specific study."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Preventing first-year turnover starts at hiring"
    },
    {
      "kind": "table",
      "header": [
        "Hiring stage",
        "What to confirm"
      ],
      "rows": [
        [
          "Screening",
          "Schedule and weekend expectations, commute, salary range, genuine interest in the unit"
        ],
        [
          "Interviews",
          "Realistic view of workload and staffing; opportunity to meet the team"
        ],
        [
          "Offer",
          "No surprises in pay, shift differentials or start date"
        ],
        [
          "Pre-boarding",
          "Orientation schedule, preceptor assignment, first-week plan"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "A recruiter's screening can help here. At Talentrax, screening confirms each candidate's interest in the specific role, availability and salary expectations before resumes are submitted. See how Talentrax works."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Retention during the first year"
    },
    {
      "kind": "paragraph",
      "text": "NSI's 2026 report found 74% of hospitals have a formal retention strategy, and a large majority (80.8%) have a strategy to protect newly hired nurses. Common elements:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Nurse residency programs for new graduates, rated 3.9 out of 5 for effectiveness by NSI respondents"
        },
        {
          "text": "A named preceptor or buddy"
        },
        {
          "text": "Check-ins at 30, 60 and 90 days and again before the first anniversary"
        },
        {
          "text": "Early schedule adjustments where operations allow"
        },
        {
          "text": "Clear development plans, such as certifications or specialty training"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Measure it"
    },
    {
      "kind": "paragraph",
      "text": "Track first-year retention by unit, role and hiring source. If a particular unit or source loses new hires faster, look at what candidates were told during hiring and what happened during orientation."
    }
  ],
  "faqs": [
    {
      "question": "What percentage of new nurses quit in their first year?",
      "answer": [
        {
          "text": "22.7% of newly hired RNs left their hospital within a year, according to NSI's 2026 report."
        }
      ]
    },
    {
      "question": "Why do new nurses leave their first job?",
      "answer": [
        {
          "text": "NSI doesn't report reasons specific to new hires. Among all staff RNs, the top reasons include personal issues, relocation, scheduling conflicts, pay, commute, working conditions and workload."
        }
      ]
    },
    {
      "question": "How can hospitals reduce first-year turnover?",
      "answer": [
        {
          "text": "Confirm schedule, commute, pay and unit expectations before the offer; provide structured onboarding with a preceptor; and hold regular check-ins during the first year."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    }
  ],
  "related": [
    "healthcare-employee-turnover",
    "why-candidates-decline-offers"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
