/**
 * GENERATED by scripts/import-articles.ts from "Why Healthcare Candidates Drop Out of the Hiring Process.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "healthcare-candidate-drop-off",
  "slug": "healthcare-candidate-drop-off",
  "title": "Why Healthcare Candidates Drop Out of the Hiring Process",
  "metaTitle": "Why Healthcare Candidates Drop Out of Hiring (and Fixes)",
  "metaDescription": "Why healthcare candidates drop out of hiring: poor fit, pay, other offers and slow communication. Where drop-off happens and what employers can do.",
  "summary": "Healthcare candidates most often drop out of a hiring process because the role turns out not to fit (in pay, schedule, commute or unit), because they accept another offer while waiting, or because communication stalls between stages. In a market where hospitals take an average of 78 days to recruit an experienced RN (NSI, 2026 report), a slow or unclear process gives strong candidates time to move on.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "In Indeed's survey of US, UK and Canadian employers, 89% said candidates dropping out or not showing up is a problem.",
      "Job seekers' top reasons for disappearing include poor fit with the job or company, insufficient pay or benefits, and receiving another offer.",
      "Most drop-off is preventable with early screening for fit, clear pay information, fast scheduling and steady communication.",
      "Published data on drop-off specifically in healthcare hiring is limited; the patterns below combine general hiring research with healthcare hiring conditions."
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "This article looks at where drop-off happens, why, and what employers can control at each stage."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How common is candidate drop-off?"
    },
    {
      "kind": "paragraph",
      "text": "The most detailed recent survey comes from Indeed, which asked 4,516 job seekers and 4,517 employers in the US, UK and Canada about \"ghosting\" in hiring (fieldwork April to May 2023, published January 2024):"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "89% of employers said it's a problem when candidates drop out of hiring processes or don't show up on the first day."
        },
        {
          "text": "61% of US job seekers said they had ghosted two to four employers in the previous 12 months."
        },
        {
          "text": "The top reasons job seekers gave: the job wasn't the right fit, the company wasn't the right fit, the pay offered was insufficient, benefits were inadequate, or they received another job offer."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "These figures cover all industries, not healthcare specifically. But the reasons map closely onto healthcare hiring, where schedule, unit, commute and pay often decide whether a nurse or technologist moves forward."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why healthcare hiring is especially vulnerable"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Long timelines. NSI's 2026 average of 78 days to recruit an experienced RN leaves plenty of room for competing offers."
        },
        {
          "text": "Shift-based schedules. Clinicians working 12-hour or rotating shifts have limited windows to interview, which slows scheduling."
        },
        {
          "text": "Multiple options. With an 8.6% national RN vacancy rate (NSI), experienced nurses often have several employers interested at once."
        },
        {
          "text": "Notice periods and relocation. Candidates may need to give notice or, if moving states, confirm their license allows them to practice."
        },
        {
          "text": "Fit matters later, too. NSI reports 22.7% of newly hired RNs leave within their first year. Some of the same fit issues that cause early drop-off also cause early turnover."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Where candidates drop out, and how to prevent it"
    },
    {
      "kind": "table",
      "header": [
        "Stage",
        "Why candidates drop out",
        "What employers can do"
      ],
      "rows": [
        [
          "Before applying or responding",
          "Pay not stated; vague job description",
          "Publish a salary range and specifics: unit, shift, schedule"
        ],
        [
          "After first contact",
          "Role doesn't match their needs",
          "Screen early for schedule, commute, pay expectations and genuine interest"
        ],
        [
          "Waiting for an interview",
          "No response for days; another offer arrives",
          "Commit to resume review and scheduling within 48 hours"
        ],
        [
          "Scheduling",
          "Interview times clash with shifts",
          "Offer early, late or virtual first-round slots"
        ],
        [
          "Between rounds",
          "Silence after interviews",
          "Share feedback and next steps within a day or two"
        ],
        [
          "Offer stage",
          "Offer below expectations; slow approvals",
          "Confirm expectations before the offer; pre-approve offer ranges"
        ],
        [
          "Offer to start date",
          "Counteroffer from current employer; loss of contact",
          "Keep in touch, set a start date quickly, share onboarding details"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Five practices that reduce drop-off"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Confirm interest before the interview. A short conversation about the unit, schedule, commute and pay range filters out mismatches early, which saves everyone time."
        },
        {
          "text": "Put the pay range in writing early. Pay was among the top reasons candidates disappeared in Indeed's survey."
        },
        {
          "text": "Set internal service levels. For example, resumes reviewed within 48 hours and feedback within one business day of each interview."
        },
        {
          "text": "Make scheduling easy for clinicians. Reserve recurring slots and offer virtual first rounds."
        },
        {
          "text": "Keep one point of contact. Candidates are less likely to go quiet when they know who to call and what happens next."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How a direct-hire recruiter can help"
    },
    {
      "kind": "paragraph",
      "text": "Several of these practices are part of a direct-hire recruiter's role. At Talentrax, a search includes scoping the role with you, sourcing and screening candidates against agreed criteria (including their interest and availability), submitting resumes, and scheduling interviews. That front-end screening is designed to bring you candidates who are ready to move forward. See how the direct-hire recruitment process works and how we work.",
      "links": [
        {
          "start": 376,
          "end": 421,
          "href": "/insights/direct-hire-recruitment-process"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Why do candidates drop out of the hiring process?",
      "answer": [
        {
          "text": "The most common reasons are poor fit with the job or company, insufficient pay or benefits, and accepting another offer, often made worse by slow or unclear communication (Indeed survey, 2023)."
        }
      ]
    },
    {
      "question": "What is candidate ghosting?",
      "answer": [
        {
          "text": "Ghosting is when a candidate stops responding, misses an interview or doesn't show up for a first day, without explanation."
        }
      ]
    },
    {
      "question": "How can healthcare employers reduce candidate no-shows?",
      "answer": [
        {
          "text": "Confirm interest and availability before scheduling, send reminders, offer flexible times for shift workers, and keep the time between steps short."
        }
      ]
    },
    {
      "question": "Is candidate drop-off worse in healthcare?",
      "answer": [
        {
          "text": "There's limited healthcare-specific data. But long time-to-fill (78 days for experienced RNs, NSI 2026) and high demand give healthcare candidates more opportunities to accept other offers."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "Indeed, \"How Job Seekers and Employers Are Responding to Ghosting\" (survey April to May 2023; published January 2024)",
      "url": "https://www.indeed.com/career-advice/news/ghosting-in-hiring-insights-strategies"
    },
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    }
  ],
  "related": [
    "how-long-to-hire-a-nurse"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
