/**
 * GENERATED by scripts/import-articles.ts from "Healthcare Hiring Trends for 2027.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "healthcare-hiring-trends-2027",
  "slug": "healthcare-hiring-trends-2027",
  "title": "Healthcare Hiring Trends for 2027",
  "metaTitle": "Healthcare Hiring Trends for 2027: 8 Shifts to Plan For",
  "metaDescription": "Eight healthcare hiring trends for 2027: clinician demand, the staffing market, Medicaid changes, rural shortages, retirements and new AI hiring rules.",
  "summary": "Healthcare hiring in 2027 will be shaped by steady demand for clinicians, a modest recovery in contract staffing, new financial pressure from federal Medicaid changes, persistent rural shortages, rising nurse retirements, and new state rules on AI in hiring. For most employers, the practical result is the same: permanent hiring needs to be faster and better targeted, because budgets and candidate pools are both tight.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Healthcare remains the main source of US job growth: BLS projects about 1.9 million openings a year across healthcare occupations.",
      "Staffing Industry Analysts expects healthcare staffing to return to growth: +1% in 2026 and +3% in 2027.",
      "Medicaid work requirements begin January 1, 2027, adding budget uncertainty for many hospitals.",
      "Colorado's new AI decision-making law takes effect January 1, 2027, joining Illinois's AI hiring rules."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "1. Demand for healthcare workers keeps growing"
    },
    {
      "kind": "paragraph",
      "text": "The Bureau of Labor Statistics projects healthcare support and healthcare practitioner occupations to be the fastest-growing occupational groups from 2025 to 2035, together accounting for almost one-third of new US jobs. Nurse practitioners are projected to be the fastest-growing single occupation, up 41%."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: competition for experienced clinicians, and especially advanced practice providers, won't ease in 2027."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "2. Contract staffing stabilizes after its reset"
    },
    {
      "kind": "paragraph",
      "text": "After three years of decline, Staffing Industry Analysts (September 2026) projects the US healthcare staffing market to grow 1% in 2026 to $39.0 billion and 3% in 2027 to $40.1 billion."
    },
    {
      "kind": "table",
      "header": [
        "Segment",
        "2026",
        "2027"
      ],
      "rows": [
        [
          "Travel nursing",
          "+2%",
          "+3%"
        ],
        [
          "Per diem nursing",
          "-7%",
          "Stabilizing"
        ],
        [
          "International nursing",
          "-8%",
          "Flat"
        ],
        [
          "Locum tenens",
          "+4%",
          "+4%"
        ],
        [
          "Allied health",
          "+2%",
          "+3%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: Staffing Industry Analysts, September 8, 2026."
    },
    {
      "kind": "paragraph",
      "text": "SIA notes that 2026 travel revenue was lifted by strike staffing, and that international nursing is constrained by visa and pipeline limits."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: contract labor isn't disappearing, but hospitals remain focused on cost. The 2026 NSI report found 70.7% of hospitals want to reduce travel and agency use. Expect continued emphasis on converting ongoing needs to permanent roles."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "3. Medicaid changes add budget pressure"
    },
    {
      "kind": "paragraph",
      "text": "The 2025 federal reconciliation law (H.R. 1) requires 44 states (including DC) to apply Medicaid work requirements to adults in the expansion group starting January 1, 2027 (KFF). The Commonwealth Fund projects federal Medicaid funding will fall by more than $900 billion over fiscal years 2025 to 2034, and projects that the combined federal cuts could eliminate about 1.65 million jobs nationwide by 2029, nearly half of them in healthcare. The law also created a $50 billion Rural Health Transformation Program over five years."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: hospitals with large Medicaid populations may face tighter budgets, making every hire more scrutinized. Hiring decisions will lean even more on cost comparisons, such as direct hire vs. travel staffing.",
      "links": [
        {
          "start": 199,
          "end": 230,
          "href": "/insights/direct-hire-vs-travel-nurse-cost"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "4. Rural shortages remain the sharpest"
    },
    {
      "kind": "paragraph",
      "text": "HRSA projects an 11% RN shortage in nonmetropolitan areas in 2038, compared with 2% in metro areas. Rural facilities face the combined pressure of smaller candidate pools and, in some states, Medicaid-related financial strain."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: rural employers will need targeted outreach, relocation support and \"grow your own\" partnerships with local schools."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "5. Retirement becomes a bigger driver of turnover"
    },
    {
      "kind": "paragraph",
      "text": "In NSI's 2026 report, retirement was the third most common reason staff RNs resigned, and it has been rising steadily. The American Hospital Association reports that 40% of nurses intend to leave or retire within five years."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: succession planning for experienced nurses, especially in specialties with older workforces, becomes a hiring priority, alongside programs that keep late-career nurses (flexible schedules, mentoring or educator roles)."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "6. Team-based care changes the roles employers hire"
    },
    {
      "kind": "paragraph",
      "text": "AHA's 2026 Workforce Scan describes hospitals augmenting care teams with advanced practice professionals and licensed practical nurses, embedding behavioral health specialists, and expanding hospital-at-home programs."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: job descriptions and hiring plans will increasingly be written for team models, with more demand for NPs, LPNs and roles that combine clinical and digital skills."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "7. AI in hiring faces new rules"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Illinois (HB 3773, in force since January 1, 2026) requires employers to notify applicants when AI is used in hiring decisions and prohibits discriminatory use."
        },
        {
          "text": "Colorado (SB 26-189, signed May 14, 2026) takes effect January 1, 2027. It requires advance notice before using automated decision-making technology in employment decisions, post-decision explanations, a route to human review, and record-keeping."
        },
        {
          "text": "New York City (Local Law 144) requires bias audits and candidate notices for automated employment decision tools."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: audit any AI screening or ranking tools in your hiring process, including those used by vendors, and confirm your notices meet the rules where you hire."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "8. Long-term care staffing rules shift to states"
    },
    {
      "kind": "paragraph",
      "text": "CMS repealed the federal nursing home minimum-staffing requirements (including 24/7 RN coverage) through an interim final rule effective February 2, 2026. The facility assessment requirement remains."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: long-term care staffing standards now depend more on state rules and each facility's own assessment of resident needs."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to prepare your 2027 hiring plan"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "List ongoing roles currently covered by contract labor and decide which to convert."
        },
        {
          "text": "Start permanent searches early: experienced RNs take 78 days on average to recruit (NSI, 2026 report)."
        },
        {
          "text": "Plan for retirements in your most experienced units."
        },
        {
          "text": "Review AI tools and notices in your hiring process against Illinois, Colorado and local rules."
        },
        {
          "text": "Protect new hires with structured onboarding: 22.7% of new RNs leave within a year (NSI)."
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "What are the biggest healthcare hiring trends for 2027?",
      "answer": [
        {
          "text": "Continued clinician demand, a modest recovery in contract staffing, Medicaid-related budget pressure, rural shortages, rising retirements, team-based care models and new AI hiring rules."
        }
      ]
    },
    {
      "question": "Will travel nursing grow in 2027?",
      "answer": [
        {
          "text": "Staffing Industry Analysts projects 3% growth for travel nursing in 2027, after 2% in 2026."
        }
      ]
    },
    {
      "question": "When do Medicaid work requirements start?",
      "answer": [
        {
          "text": "January 1, 2027, under the 2025 reconciliation law, according to KFF."
        }
      ]
    },
    {
      "question": "Do AI hiring laws apply to healthcare employers?",
      "answer": [
        {
          "text": "Yes. Laws such as Illinois HB 3773 and Colorado SB 26-189 apply to employers generally, including healthcare organizations, where they hire. Consult legal counsel for your situation."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Employment Projections 2025–35",
      "url": "https://www.bls.gov/news.release/ecopro.nr0.htm"
    },
    {
      "name": "Staffing Industry Analysts, \"Healthcare staffing rebounds as demand strengthens in the second and third quarters\" (September 8, 2026)",
      "url": "https://www.staffingindustry.com/editorial/healthcare-staffing-report/healthcare-staffing-rebounds-as-demand-strengthens-in-the-second-and-third-quarters"
    },
    {
      "name": "KFF, Medicaid Work Requirements Tracker (updated September 2026)",
      "url": "https://www.kff.org/medicaid/medicaid-work-requirements-tracker-overview/"
    },
    {
      "name": "Commonwealth Fund, H.R. 1 Funding Cuts Will Overshadow Gains from the New Rural Health Transformation Program (June 2026)",
      "url": "https://www.commonwealthfund.org/publications/issue-briefs/2026/jun/hr-1-funding-cuts-rural-health-transformation"
    },
    {
      "name": "HRSA, Health Workforce Projections",
      "url": "https://bhw.hrsa.gov/data-research/projecting-health-workforce-supply-demand"
    },
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "American Hospital Association, 2026 Health Care Workforce Scan Executive Summary",
      "url": "https://www.aha.org/system/files/media/file/2025/12/2026-Health-Care-Workforce-Scan-Executive-Summary.pdf"
    },
    {
      "name": "American Hospital Association, Assessing the Health Care Environment for 2026",
      "url": "https://www.aha.org/aha-center-health-innovation-market-scan/2025-12-23-assessing-health-care-environment-2026-key-signals-field"
    },
    {
      "name": "Seyfarth Shaw, Colorado Enacts Artificial Intelligence Replacement Law",
      "url": "https://www.seyfarth.com/news-insights/colorado-enacts-artificial-intelligence-replacement-law.html"
    },
    {
      "name": "K&L Gates, Navigating the AI Employment Landscape in 2026",
      "url": "https://www.klgates.com/thought-leadership/Navigating-the-AI-Employment-Landscape-in-2026-Considerations-and-Best-Practices-for-Employers-2-2-2026"
    },
    {
      "name": "NYC Department of Consumer and Worker Protection, Automated Employment Decision Tools",
      "url": "https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page"
    },
    {
      "name": "Federal Register, Repeal of Minimum Staffing Standards for Long-Term Care Facilities",
      "url": "https://www.federalregister.gov/documents/2025/12/03/2025-21792/medicare-and-medicaid-programs-repeal-of-minimum-staffing-standards-for-long-term-care-facilities"
    }
  ],
  "related": [
    "nurse-turnover-statistics",
    "reduce-travel-nurse-reliance"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
