/**
 * GENERATED by scripts/import-articles.ts from "Healthcare Employee Turnover - Costs Causes and Retention Strategies.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "healthcare-employee-turnover",
  "slug": "healthcare-employee-turnover",
  "title": "Healthcare Employee Turnover: Costs, Causes and Retention Strategies",
  "metaTitle": "Healthcare Employee Turnover: Costs, Causes, Retention",
  "metaDescription": "Hospital turnover was 18.5% in 2025 (NSI). Turnover by role and tenure, why healthcare workers leave, what it costs, and retention strategies.",
  "summary": "Healthcare employee turnover remains high: US hospitals recorded 18.5% turnover across all employees in 2025, and 17.6% for staff registered nurses, according to the 2026 NSI National Health Care Retention & RN Staffing Report. Turnover is costly (about $60,090 for each bedside RN who leaves) and concentrated among new hires and frontline roles, which is why retention starts at the hiring stage.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "All-employee hospital turnover: 18.5%; staff RN turnover: 17.6% (NSI, 2025 data).",
      "Patient care technicians (33.8%) and CNAs (32.5%) have the highest turnover of any hospital role.",
      "29.5% of all new hospital hires left within a year; 56.8% of employees who left had less than two years' service.",
      "Personal reasons, relocation, career advancement, retirement and education top the list of why hospital employees resign."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "How high is healthcare turnover?"
    },
    {
      "kind": "table",
      "header": [
        "Measure",
        "Figure",
        "Source"
      ],
      "rows": [
        [
          "Hospital turnover, all employees",
          "18.5% (2025)",
          "NSI, 2026 report"
        ],
        [
          "Hospital turnover, full- and part-time only",
          "15.8%",
          "NSI, 2026 report"
        ],
        [
          "Staff RN turnover",
          "17.6%",
          "NSI, 2026 report"
        ],
        [
          "Share of hospital separations that were voluntary",
          "94.9%",
          "NSI, 2026 report"
        ],
        [
          "Monthly quits rate, healthcare and social assistance",
          "1.9% (July 2026)",
          "BLS JOLTS, via FRED"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Across five years, NSI calculates the average hospital turned over 106% of its workforce. For RN-specific data, see our nurse turnover statistics.",
      "links": [
        {
          "start": 120,
          "end": 145,
          "href": "/insights/nurse-turnover-statistics"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Turnover by role"
    },
    {
      "kind": "table",
      "header": [
        "Role",
        "2025 hospital turnover"
      ],
      "rows": [
        [
          "Patient care technician",
          "33.8%"
        ],
        [
          "Certified nursing assistant",
          "32.5%"
        ],
        [
          "Environmental services",
          "27.6%"
        ],
        [
          "Registered nurse",
          "17.6%"
        ],
        [
          "Radiologic technologist",
          "15.5%"
        ],
        [
          "Respiratory therapist",
          "14.8%"
        ],
        [
          "Physical therapist",
          "11.1%"
        ],
        [
          "Pharmacist",
          "10.7%"
        ],
        [
          "Nurse practitioner",
          "9.8%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: NSI, 2026 report. Advanced practice and allied health professionals have had turnover below the hospital average for eight consecutive years."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "When employees leave: the tenure pattern"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "29.5% of all new hospital hires left within their first year."
        },
        {
          "text": "First-year departures made up 35.6% of all hospital turnover."
        },
        {
          "text": "56.8% of employees who left had less than two years of service."
        },
        {
          "text": "Employees with more than five years' tenure showed greater organizational commitment."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "The pattern is clear: the first two years are where most turnover happens. See why healthcare workers quit in their first year.",
      "links": [
        {
          "start": 79,
          "end": 126,
          "href": "/insights/first-year-healthcare-turnover"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why healthcare employees leave"
    },
    {
      "kind": "paragraph",
      "text": "NSI's respondents ranked the top reasons hospital employees resigned:"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Personal issues"
        },
        {
          "text": "Relocation"
        },
        {
          "text": "Career advancement"
        },
        {
          "text": "Retirement"
        },
        {
          "text": "Education"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Rounding out the top 10: scheduling conflicts, salary, commute, culture, and workload or staffing ratios. For RNs, retirement ranks third and has been rising."
    },
    {
      "kind": "paragraph",
      "text": "The American Hospital Association also reports widespread burnout across clinical roles, and that 40% of nurses intend to leave or retire within five years."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What turnover costs"
    },
    {
      "kind": "table",
      "header": [
        "Measure",
        "Figure"
      ],
      "rows": [
        [
          "Cost of one bedside RN turnover",
          "$60,090"
        ],
        [
          "Average hospital annual loss to RN turnover",
          "$5.19 million"
        ],
        [
          "Cost or saving per 1-point change in RN turnover",
          "About $295,000 a year"
        ],
        [
          "Hospitals that track turnover cost",
          "46.1%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: NSI, 2026 report. Turnover costs typically include separation, covering the vacancy (overtime or contract labor), recruitment, orientation and lost productivity."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Retention strategies that start before day one"
    },
    {
      "kind": "paragraph",
      "text": "Because so much turnover happens early, hiring practices matter:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Confirm fit before the offer. Schedule, commute, unit and pay expectations are all among the top reasons for leaving; each can be discussed during screening."
        },
        {
          "text": "Give realistic job previews. Unit tours and candid conversations about workload help candidates self-select."
        },
        {
          "text": "Move quickly but carefully. A fast process reduces drop-off; a thorough one reduces early regret."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Retention strategies after the start date"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Structured onboarding and preceptorship. NSI respondents rated nurse residency programs 3.9 out of 5 for effectiveness."
        },
        {
          "text": "Check-ins at 30, 60 and 90 days to catch problems early."
        },
        {
          "text": "Schedule flexibility where operations allow."
        },
        {
          "text": "Career paths: clinical ladders, certification support and education benefits."
        },
        {
          "text": "Workload and staffing attention, since workload and staffing ratios appear among the top 10 reasons for leaving."
        },
        {
          "text": "Plans for experienced staff nearing retirement, such as mentoring, educator roles or reduced schedules. NSI found 62.4% of hospitals have strategies aimed at tenured nurses."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Set a measurable goal"
    },
    {
      "kind": "paragraph",
      "text": "NSI found 27.6% of hospitals had no measurable turnover goal. Setting one, tracking it by unit and role, and reviewing it quarterly makes retention a managed outcome rather than a hope."
    }
  ],
  "faqs": [
    {
      "question": "What is the turnover rate in healthcare?",
      "answer": [
        {
          "text": "US hospitals recorded 18.5% turnover across all employees in 2025, and 17.6% for staff RNs (NSI, 2026 report)."
        }
      ]
    },
    {
      "question": "Which healthcare jobs have the highest turnover?",
      "answer": [
        {
          "text": "Patient care technicians (33.8%) and certified nursing assistants (32.5%) had the highest hospital turnover in 2025."
        }
      ]
    },
    {
      "question": "What does turnover cost a hospital?",
      "answer": [
        {
          "text": "NSI estimates each bedside RN who leaves costs $60,090, and the average hospital lost $5.19 million to RN turnover in 2025."
        }
      ]
    },
    {
      "question": "How can healthcare employers reduce turnover?",
      "answer": [
        {
          "text": "Start with hiring for fit (schedule, unit, pay, commute), then support new hires with structured onboarding, early check-ins, schedule flexibility and clear career paths."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "BLS JOLTS via FRED, Quits: Health Care and Social Assistance (JTS6200QUR)",
      "url": "https://fred.stlouisfed.org/series/JTS6200QUR"
    },
    {
      "name": "American Hospital Association, Assessing the Health Care Environment for 2026",
      "url": "https://www.aha.org/aha-center-health-innovation-market-scan/2025-12-23-assessing-health-care-environment-2026-key-signals-field"
    }
  ],
  "related": [
    "nurse-turnover-statistics",
    "how-to-hire-nurses"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
