/**
 * GENERATED by scripts/import-articles.ts from "US Healthcare Workforce Outlook - Shortages Projections and Planning.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "healthcare-workforce-outlook",
  "slug": "healthcare-workforce-outlook",
  "title": "US Healthcare Workforce Outlook: Shortages, Projections and Planning",
  "metaTitle": "US Healthcare Workforce Outlook: Shortages and Projections",
  "metaDescription": "US healthcare workforce outlook: BLS 2025-35 demand, HRSA shortage projections, current job openings and the forces shaping hiring. Dated and sourced.",
  "summary": "The US healthcare workforce faces sustained demand growth and uneven shortages. The Bureau of Labor Statistics projects about 1.9 million openings a year across healthcare occupations through 2035, while HRSA projects an 8% national shortage of registered nurses in 2028, with shortages far larger in rural areas than in cities. For employers, the practical challenge is less a single national shortage than specific gaps by role, specialty and location.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Healthcare support (+13.3%) and healthcare practitioner (+8.0%) jobs are the fastest-growing occupational groups, 2025 to 2035 (BLS).",
      "HRSA projects an RN shortage of 8% in 2028, narrowing to 3% by 2038, but 11% in nonmetropolitan areas vs. 2% in metro areas in 2038.",
      "Healthcare and social assistance had 5.7 job openings per 100 jobs in July 2026, above the all-industry rate of 4.4 (BLS JOLTS).",
      "Hospitals still take an average of 78 days to recruit an experienced RN (NSI, 2026 report)."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "Demand: healthcare leads US job growth"
    },
    {
      "kind": "paragraph",
      "text": "The BLS 2025–35 projections show healthcare driving employment growth:"
    },
    {
      "kind": "table",
      "header": [
        "Measure",
        "Projection",
        "Source"
      ],
      "rows": [
        [
          "Healthcare support occupations",
          "+13.3%, 2025–35",
          "BLS"
        ],
        [
          "Healthcare practitioners and technical occupations",
          "+8.0%, 2025–35",
          "BLS"
        ],
        [
          "Share of new US jobs from these two groups",
          "Almost one-third",
          "BLS"
        ],
        [
          "Annual openings, healthcare occupations",
          "About 1.9 million",
          "BLS"
        ],
        [
          "Fastest-growing single occupation",
          "Nurse practitioners, +41%",
          "BLS"
        ],
        [
          "Registered nurses",
          "+6%; about 180,800 openings a year",
          "BLS"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "BLS attributes much of this growth to an aging population and the prevalence of chronic conditions. Many annual openings come from the need to replace workers who retire or leave an occupation, not only from new positions."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Supply: shortages are real but uneven"
    },
    {
      "kind": "paragraph",
      "text": "HRSA's National Center for Health Workforce Analysis projects:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "An 8% national RN shortage in 2028, narrowing to 3% (about 108,960 full-time-equivalent RNs) by 2038"
        },
        {
          "text": "An 11% RN shortage in nonmetropolitan areas in 2038, compared with 2% in metro areas"
        },
        {
          "text": "A proportionally larger shortfall for licensed practical nurses than for RNs"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "HRSA's projections assume historical patterns of graduation, attrition and labor force participation continue. Policy or market changes could move the numbers in either direction."
    },
    {
      "kind": "paragraph",
      "text": "For detailed figures, see our nursing shortage statistics.",
      "links": [
        {
          "start": 30,
          "end": 57,
          "href": "/insights/nursing-shortage-statistics"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The labor market right now"
    },
    {
      "kind": "table",
      "header": [
        "Indicator",
        "Latest figure",
        "Source"
      ],
      "rows": [
        [
          "Job openings rate, healthcare and social assistance",
          "5.7 per 100 jobs (July 2026)",
          "BLS JOLTS, via FRED"
        ],
        [
          "Job openings rate, all industries",
          "4.4 per 100 jobs (July 2026)",
          "BLS JOLTS"
        ],
        [
          "Quits rate, healthcare and social assistance",
          "1.9% a month (July 2026)",
          "BLS JOLTS, via FRED"
        ],
        [
          "Hospital RN vacancy rate",
          "8.6%",
          "NSI, 2026 report"
        ],
        [
          "Hospital staff RN turnover",
          "17.6% (2025)",
          "NSI, 2026 report"
        ],
        [
          "Time to recruit an experienced RN",
          "78 days",
          "NSI, 2026 report"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "JOLTS figures are seasonally adjusted and cover the whole healthcare and social assistance sector, not hospitals alone."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Forces shaping the workforce"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Retirements. Retirement is now the third most common reason hospital RNs resign (NSI, 2026 report), and the American Hospital Association reports 40% of nurses intend to leave or retire within five years."
        },
        {
          "text": "Contract labor reset. Staffing Industry Analysts projects healthcare staffing to grow 1% in 2026 and 3% in 2027 after three years of decline, while hospitals continue efforts to reduce travel spending."
        },
        {
          "text": "Financial pressure. Medicaid work requirements under the 2025 reconciliation law begin January 1, 2027 in 44 states including DC (KFF), adding budget uncertainty for many hospitals."
        },
        {
          "text": "New care models. AHA's 2026 Workforce Scan describes more team-based care, with advanced practice professionals and LPNs taking larger roles, and AI used alongside redesigned workflows."
        },
        {
          "text": "Rural strain. Nonmetropolitan facilities face the largest projected shortages and smaller local candidate pools."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "For more, see healthcare hiring trends for 2027.",
      "links": [
        {
          "start": 14,
          "end": 47,
          "href": "/insights/healthcare-hiring-trends-2027"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What this means for workforce planning"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Plan by role and location, not by national headlines. A metro hospital hiring med/surg RNs faces a very different market from a rural clinic hiring an LPN."
        },
        {
          "text": "Forecast replacement demand, not just growth. Retirements and turnover create most openings."
        },
        {
          "text": "Start searches earlier for hard-to-fill roles; telemetry RNs averaged 87 days to recruit (NSI)."
        },
        {
          "text": "Invest in retention, since every retained employee is one less opening. See healthcare employee turnover.",
          "links": [
            {
              "start": 76,
              "end": 104,
              "href": "/insights/healthcare-employee-turnover"
            }
          ]
        },
        {
          "text": "Review your contingent labor mix and convert ongoing needs to permanent roles where it makes financial sense."
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Is there a healthcare worker shortage in the US?",
      "answer": [
        {
          "text": "Yes, but it varies. HRSA projects an 8% national RN shortage in 2028, and much larger shortages in rural areas. Healthcare job openings (5.7 per 100 jobs in July 2026) also exceed the all-industry rate."
        }
      ]
    },
    {
      "question": "Which healthcare jobs are growing fastest?",
      "answer": [
        {
          "text": "Nurse practitioners are projected to grow 41% from 2025 to 2035, the fastest of any US occupation (BLS). Healthcare support occupations as a group are projected to grow 13.3%."
        }
      ]
    },
    {
      "question": "Will the nursing shortage end?",
      "answer": [
        {
          "text": "HRSA projects the national RN shortage to narrow from 8% in 2028 to 3% in 2038, but rural shortages are projected to remain much larger."
        }
      ]
    },
    {
      "question": "Why are hospitals short-staffed?",
      "answer": [
        {
          "text": "See our answer to why hospitals are short-staffed.",
          "links": [
            {
              "start": 18,
              "end": 49,
              "href": "/insights/why-are-hospitals-short-staffed"
            }
          ]
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Employment Projections 2025–35",
      "url": "https://www.bls.gov/news.release/ecopro.nr0.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Occupational Outlook Handbook, Healthcare Occupations",
      "url": "https://www.bls.gov/ooh/healthcare/"
    },
    {
      "name": "US Bureau of Labor Statistics, Registered Nurses",
      "url": "https://www.bls.gov/ooh/healthcare/registered-nurses.htm"
    },
    {
      "name": "HRSA, Nurse Workforce Projections 2023–2038",
      "url": "https://bhw.hrsa.gov/sites/default/files/bureau-health-workforce/data-research/nursing-projections-factsheet.pdf"
    },
    {
      "name": "HRSA, Health Workforce Projections",
      "url": "https://bhw.hrsa.gov/data-research/projecting-health-workforce-supply-demand"
    },
    {
      "name": "BLS JOLTS via FRED, Job Openings: Health Care and Social Assistance (JTS6200JOR)",
      "url": "https://fred.stlouisfed.org/series/JTS6200JOR"
    },
    {
      "name": "BLS JOLTS via FRED, Quits: Health Care and Social Assistance (JTS6200QUR)",
      "url": "https://fred.stlouisfed.org/series/JTS6200QUR"
    },
    {
      "name": "BLS, Job Openings and Labor Turnover Summary (July 2026)",
      "url": "https://www.bls.gov/news.release/jolts.nr0.htm"
    },
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "American Hospital Association, Assessing the Health Care Environment for 2026",
      "url": "https://www.aha.org/aha-center-health-innovation-market-scan/2025-12-23-assessing-health-care-environment-2026-key-signals-field"
    },
    {
      "name": "American Hospital Association, 2026 Health Care Workforce Scan Executive Summary",
      "url": "https://www.aha.org/system/files/media/file/2025/12/2026-Health-Care-Workforce-Scan-Executive-Summary.pdf"
    },
    {
      "name": "Staffing Industry Analysts (September 8, 2026)",
      "url": "https://www.staffingindustry.com/editorial/healthcare-staffing-report/healthcare-staffing-rebounds-as-demand-strengthens-in-the-second-and-third-quarters"
    },
    {
      "name": "KFF, Medicaid Work Requirements Tracker",
      "url": "https://www.kff.org/medicaid/medicaid-work-requirements-tracker-overview/"
    }
  ],
  "related": [
    "how-to-hire-nurses",
    "nurse-turnover-statistics"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
