/**
 * GENERATED by scripts/import-articles.ts from "The Accounting Talent Shortage - How to Hire Accountants as CPA Rules Change.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "hiring-accountants-cpa-pathway",
  "slug": "hiring-accountants-cpa-pathway",
  "title": "The Accounting Talent Shortage: How to Hire Accountants as CPA Rules Change",
  "metaTitle": "Accounting Talent Shortage: Hiring Under New CPA Rules",
  "metaDescription": "How the new 120-credit CPA pathway (44 states and Puerto Rico) changes accountant hiring, with BLS outlook data, a hiring approach and interview questions.",
  "summary": "The biggest change in accounting hiring is the new CPA licensure pathway: as of July 2026, 44 states and Puerto Rico had enacted laws allowing candidates to become CPAs with a bachelor's degree (120 credit hours) plus two years of experience, instead of the traditional 150 credit hours. For employers, that widens the pool of CPA-track candidates, changes what \"CPA-eligible\" means on a resume, and makes clear role definitions and a fast hiring process more important than ever.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "BLS projects about 115,300 openings a year for accountants and auditors from 2025 to 2035.",
      "44 states and Puerto Rico have enacted a \"bachelor's plus two years\" CPA pathway; five states had not formalized reforms as of July 2026 (CFO Dive).",
      "Routine bookkeeping work is shrinking: BLS projects bookkeeping, accounting and auditing clerks to decline 6%, citing software automation.",
      "Verify CPA licenses with the state board of accountancy before an offer."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "The accounting job market"
    },
    {
      "kind": "table",
      "header": [
        "Role (BLS)",
        "Jobs, 2025",
        "Growth, 2025–35",
        "Annual openings",
        "Median pay (May 2025)"
      ],
      "rows": [
        [
          "Accountants and auditors",
          "1,595,200",
          "5%",
          "About 115,300",
          "$83,680"
        ],
        [
          "Financial managers (includes controllers)",
          "879,700",
          "10%",
          "About 65,600",
          "$166,570"
        ],
        [
          "Bookkeeping, accounting and auditing clerks",
          "1,532,400",
          "-6%",
          "About 144,100 (replacement only)",
          "$50,670"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: BLS Occupational Outlook Handbook. Demand is growing for analytical and leadership roles while routine transaction processing declines as software takes over."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What changed in CPA licensing"
    },
    {
      "kind": "paragraph",
      "text": "Traditionally, CPA candidates needed 150 college credit hours (roughly five years of study), one year of experience and a passing score on the CPA exam. The reform adds an alternative:"
    },
    {
      "kind": "table",
      "header": [
        "",
        "Traditional pathway",
        "New alternative pathway"
      ],
      "rows": [
        [
          "Education",
          "150 credit hours",
          "Bachelor's degree (120 credit hours)"
        ],
        [
          "Experience",
          "Typically 1 year",
          "2 years"
        ],
        [
          "Exam",
          "CPA exam",
          "CPA exam"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "According to CFO Dive's tracker (updated July 14, 2026), 44 states and Puerto Rico have enacted the new pathway. Michigan, Massachusetts, North Dakota, Wyoming and Florida had yet to formalize reforms at that date."
    },
    {
      "kind": "paragraph",
      "text": "The AICPA and the National Association of State Boards of Accountancy also updated the model Uniform Accountancy Act in July 2025 so that a CPA's ability to practice across state lines depends on the individual's qualifications rather than on whether states' rules are \"substantially equivalent.\""
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What it means for employers"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "More CPA-track candidates: graduates with a bachelor's degree can pursue licensure while working, rather than completing a fifth year of school first."
        },
        {
          "text": "Experience matters more: the alternative pathway requires two years of qualifying experience, so candidates may look for employers who can support it."
        },
        {
          "text": "Resumes look different: \"CPA-eligible\" or \"CPA candidate\" may now refer to either pathway. Ask which one and where the candidate is in the process."
        },
        {
          "text": "Mobility rules are changing: check your state's rules if the role requires practicing across state lines."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to hire accountants in the current market"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Define the level precisely. Staff accountant, senior accountant, accounting manager and controller need very different experience."
        },
        {
          "text": "Separate CPA-required from CPA-preferred. Many industry roles don't require a license; public accounting and SEC reporting roles often do."
        },
        {
          "text": "Offer licensure support such as exam fees, study time or supervision that counts toward experience requirements. It's a strong draw for early-career candidates."
        },
        {
          "text": "Specify systems. ERP and close tools (for example, NetSuite, SAP or QuickBooks) often matter as much as the title."
        },
        {
          "text": "Share the pay range early. Many states now require it in postings. See pay transparency laws.",
          "links": [
            {
              "start": 71,
              "end": 92,
              "href": "/insights/pay-transparency-laws-2026"
            }
          ]
        },
        {
          "text": "Test practically. A short reconciliation or journal-entry exercise shows skill better than a resume."
        },
        {
          "text": "Verify licenses through the state board of accountancy or NASBA's CPAverify before an offer. Talentrax does not provide license verification."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Interview questions for accounting roles"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Walk me through your month-end close. What would you improve?"
        },
        {
          "text": "How do you handle a reconciliation that won't tie out?"
        },
        {
          "text": "Which ERP and reporting tools have you used, and how deeply?"
        },
        {
          "text": "Where are you in CPA licensure, and which pathway are you on?"
        },
        {
          "text": "How are you using automation or AI tools in your work today?"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Is there a shortage of accountants?",
      "answer": [
        {
          "text": "Demand remains steady: BLS projects about 115,300 openings a year for accountants and auditors through 2035, and states have changed CPA licensing rules partly to widen the pipeline."
        }
      ]
    },
    {
      "question": "What is the new CPA pathway?",
      "answer": [
        {
          "text": "An alternative route to licensure that requires a bachelor's degree (120 credit hours), two years of experience and passing the CPA exam, instead of 150 credit hours."
        }
      ]
    },
    {
      "question": "How many states allow the 120-credit CPA pathway?",
      "answer": [
        {
          "text": "As of July 14, 2026, 44 states and Puerto Rico had enacted laws creating the pathway (CFO Dive)."
        }
      ]
    },
    {
      "question": "How do I verify a CPA license?",
      "answer": [
        {
          "text": "Through the relevant state board of accountancy or NASBA's CPAverify database."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "CFO Dive, Tracking CPA licensure paths: Removing the 150-hour-rule hurdle (updated July 14, 2026)",
      "url": "https://www.cfodive.com/news/broadening-cpa-licensure-paths-marching-beyond-150-hour-rule-accounting-talent-shortage/745282/"
    },
    {
      "name": "US Bureau of Labor Statistics, Accountants and Auditors",
      "url": "https://www.bls.gov/ooh/business-and-financial/accountants-and-auditors.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Financial Managers",
      "url": "https://www.bls.gov/ooh/management/financial-managers.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Bookkeeping, Accounting, and Auditing Clerks",
      "url": "https://www.bls.gov/ooh/office-and-administrative-support/bookkeeping-accounting-and-auditing-clerks.htm"
    },
    {
      "name": "NASBA, CPAverify",
      "url": "https://cpaverify.org"
    }
  ],
  "related": [
    "ai-impact-admin-finance-hr-roles",
    "non-it-hiring-trends-2027"
  ],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
