/**
 * GENERATED by scripts/import-articles.ts from "How to Recruit and Hire Nurses in 2026.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "how-to-hire-nurses",
  "slug": "how-to-hire-nurses",
  "title": "How to Recruit and Hire Nurses in 2026",
  "metaTitle": "How to Hire Nurses in 2026: An Employer's Guide",
  "metaDescription": "How to recruit and hire nurses in 2026: current supply and turnover data, hiring by role (RN, NP, LPN, CNA), an 8-step process and license verification.",
  "summary": "To hire nurses successfully in 2026, employers need a precise role brief, a competitive and clearly stated salary range, active sourcing beyond job postings, a fast interview process built around shift schedules, license verification before the offer, and a plan to keep new hires past their first year. Demand is steady, experienced nurses often weigh several options, and the average hospital takes 78 days to recruit an experienced RN (NSI, 2026 report).",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "BLS projects about 180,800 RN openings a year through 2035, and nurse practitioner employment is projected to grow 41%.",
      "Hospital RN turnover rose to 17.6% in 2025, and 22.7% of newly hired RNs left within a year (NSI, 2026 report).",
      "Shortages are uneven: HRSA projects much larger RN shortages in nonmetropolitan areas than in metro areas.",
      "Employers are responsible for verifying nursing licenses, commonly through state boards of nursing or NCSBN's Nursys."
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "This guide covers the current nurse hiring market, what differs by nursing role, a step-by-step hiring process, where to find candidates, and when outside recruiting help makes sense."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The nurse hiring market in 2026"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Demand"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Registered nurses: about 3.47 million jobs in 2025, projected to grow 6% by 2035, with roughly 180,800 openings a year, many to replace nurses who retire or leave the field (BLS)."
        },
        {
          "text": "Hospitals remain the largest employer, with 59% of RN jobs, followed by ambulatory care at 19% (BLS)."
        },
        {
          "text": "Nurse practitioners: the fastest-growing occupation in the US, projected to grow 41% between 2025 and 2035 (BLS)."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Supply"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "HRSA projects an 8% national shortage of full-time-equivalent RNs in 2028, narrowing to 3% by 2038."
        },
        {
          "text": "The shortage is geographic: in 2038, HRSA projects an 11% RN shortage in nonmetropolitan areas versus 2% in metro areas."
        },
        {
          "text": "HRSA also projects a proportionally larger shortfall for LPNs than for RNs."
        },
        {
          "text": "The American Hospital Association's 2026 Environmental Scan reports that more than 138,000 nurses left the workforce between 2022 and 2024, and 40% of nurses report an intent to leave or retire within five years."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Hiring conditions in hospitals"
    },
    {
      "kind": "table",
      "header": [
        "Metric (hospitals, calendar 2025)",
        "Value"
      ],
      "rows": [
        [
          "Staff RN turnover",
          "17.6%"
        ],
        [
          "RN vacancy rate",
          "8.6%"
        ],
        [
          "Average time to recruit an experienced RN",
          "78 days"
        ],
        [
          "Newly hired RNs who left within a year",
          "22.7%"
        ],
        [
          "Cost of one bedside RN turnover",
          "$60,090"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: NSI, 2026 National Health Care Retention & RN Staffing Report."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Hiring by nursing role"
    },
    {
      "kind": "paragraph",
      "text": "Each nursing role has a different supply picture, so recruiting approaches should differ too."
    },
    {
      "kind": "table",
      "header": [
        "Role",
        "2025 jobs",
        "Projected growth 2025–35",
        "Median pay (May 2025)",
        "Hiring notes"
      ],
      "rows": [
        [
          "Registered nurse (RN)",
          "3,465,400",
          "6%",
          "$97,550",
          "Specialty experience drives difficulty; telemetry and med/surg take longest to fill (NSI)"
        ],
        [
          "Nurse practitioner (NP)",
          "336,300",
          "41%",
          "$132,300",
          "Fast demand growth; scope of practice varies by state"
        ],
        [
          "Licensed practical/vocational nurse (LPN/LVN)",
          "666,900",
          "3%",
          "$64,400",
          "About 51,800 openings a year, mostly replacement demand"
        ],
        [
          "Nursing assistant (CNA)",
          "Part of 1,558,700 nursing assistants and orderlies",
          "3%",
          "$42,260",
          "Very high turnover; about 203,300 openings a year for the group"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: BLS Occupational Outlook Handbook, 2025–35 projections."
    },
    {
      "kind": "paragraph",
      "text": "A few implications:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "For RNs, specialty and shift matter more than headline pay alone. Be precise about unit, acuity and schedule."
        },
        {
          "text": "For NPs, competition is intense and growing. Clarify supervision or collaboration arrangements under your state's rules."
        },
        {
          "text": "For LPNs and CNAs, high-volume, ongoing hiring and strong onboarding usually matter more than one-off searches. NSI reports CNAs and patient care techs have the highest turnover of any hospital role, around one-third a year."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why nurses leave, and what that means for hiring"
    },
    {
      "kind": "paragraph",
      "text": "NSI's 2026 report lists the top reasons staff RNs resigned: personal issues, relocation, retirement, career advancement and scheduling conflicts, followed by education, salary, commute, working conditions and workload or staffing ratios. Retirement has been climbing and is now the third most common reason."
    },
    {
      "kind": "paragraph",
      "text": "Several of these can be addressed at the hiring stage:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Schedule and commute fit can be confirmed before an interview, not discovered after a start date."
        },
        {
          "text": "Career path questions can be answered openly: advancement, education support and specialty training."
        },
        {
          "text": "Realistic job previews (unit tours, shadowing, candid conversations about staffing ratios) help candidates self-select."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "An 8-step nurse hiring process"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Confirm the position is approved and budgeted before sourcing."
        },
        {
          "text": "Write a precise brief: unit, patient population, required license and certifications, experience, shift pattern, and salary range."
        },
        {
          "text": "Set the salary range against your local market. BLS state and metro wage data is a starting point; local competitors' postings are another."
        },
        {
          "text": "Source actively: referrals, direct outreach, professional networks, nursing schools and targeted postings."
        },
        {
          "text": "Screen for fit before interviews: experience match, genuine interest in the unit, availability, notice period and salary expectations."
        },
        {
          "text": "Interview quickly and flexibly: reserve recurring slots, offer virtual first rounds and early or late times for nurses on shifts."
        },
        {
          "text": "Verify the license and complete checks before the offer, including background and reference checks per your policy."
        },
        {
          "text": "Onboard for retention: preceptorship, check-ins at 30, 60 and 90 days, and a clear first-year plan."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "For a detailed look at how a recruiter-led search runs, see how the direct-hire recruitment process works.",
      "links": [
        {
          "start": 60,
          "end": 105,
          "href": "/insights/direct-hire-recruitment-process"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Where to find nurse candidates"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Employee referrals. Your current nurses know other nurses."
        },
        {
          "text": "Former employees and past applicants. People who left on good terms or were strong finalists before."
        },
        {
          "text": "Nursing schools and residency programs for new graduates."
        },
        {
          "text": "Professional associations and specialty networks."
        },
        {
          "text": "Direct outreach to passive candidates, often the only way to reach experienced specialty nurses who aren't job hunting."
        },
        {
          "text": "Direct-hire recruiters for hard-to-fill specialties, remote locations or when your team lacks capacity."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Writing a nurse job description that attracts applicants"
    },
    {
      "kind": "paragraph",
      "text": "A nurse job posting competes with dozens of similar postings. The ones that get responses answer a nurse's practical questions up front:"
    },
    {
      "kind": "table",
      "header": [
        "Include",
        "Example"
      ],
      "rows": [
        [
          "Unit and patient population",
          "32-bed telemetry unit, adult cardiac patients"
        ],
        [
          "Shift and schedule",
          "Three 12-hour night shifts, every third weekend"
        ],
        [
          "Ratios or staffing model",
          "Typical patient assignment, charge nurse support"
        ],
        [
          "Required license and certifications",
          "Active RN license (or multistate compact license), BLS, ACLS"
        ],
        [
          "Experience",
          "One year of acute care; telemetry preferred"
        ],
        [
          "Pay range",
          "A stated hourly or annual range, plus shift differentials"
        ],
        [
          "Benefits that matter to nurses",
          "Tuition support, certification reimbursement, retirement match"
        ],
        [
          "Growth",
          "Clinical ladder, charge or preceptor opportunities"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Avoid long lists of generic duties every RN already knows. Specifics about the unit and schedule do more to attract the right candidates."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Competing for nurses beyond pay"
    },
    {
      "kind": "paragraph",
      "text": "Pay must be competitive, but NSI's list of reasons RNs resign shows that schedule, commute, career advancement and workload also drive decisions. Employers that win candidates tend to:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Offer schedule choice where the unit can support it, such as fixed shifts, self-scheduling or weekend options."
        },
        {
          "text": "Show a career path, including specialty training, certification support and advancement to charge, educator or leadership roles."
        },
        {
          "text": "Support new graduates with residency programs. NSI respondents rated nurse residency programs 3.9 out of 5 for retention effectiveness."
        },
        {
          "text": "Be candid about staffing. Nurses often ask about ratios and support staff. Honest answers build trust and reduce early turnover."
        },
        {
          "text": "Move quickly. A fast, respectful process signals how the organization treats its nurses."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Hiring nurses for rural and nonmetropolitan facilities"
    },
    {
      "kind": "paragraph",
      "text": "HRSA projects an 11% RN shortage in nonmetropolitan areas in 2038, compared with 2% in metro areas, so rural employers face the hardest recruiting conditions. Approaches that help include:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Recruiting people with local ties, including nurses who grew up in the area or have family nearby."
        },
        {
          "text": "Growing your own through partnerships with community colleges and nursing schools, clinical placements and tuition support."
        },
        {
          "text": "Offering relocation support and being clear about housing, schools and community."
        },
        {
          "text": "Checking licensure early for out-of-state candidates. Nurses with a multistate license under the Nurse Licensure Compact may be able to practice in other compact states without a new license."
        },
        {
          "text": "Widening the search through direct outreach, since few experienced rural candidates will be actively applying."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Verifying nursing licenses"
    },
    {
      "kind": "paragraph",
      "text": "License verification is the employer's responsibility unless a written agreement says otherwise. Common tools include:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "State boards of nursing, which publish license lookups."
        },
        {
          "text": "NCSBN's Nursys, which provides license verification for nurses across participating boards."
        },
        {
          "text": "Nurse Licensure Compact (NLC) status, which determines whether a nurse's multistate license allows practice in your state. Check current compact membership on NCSBN's NLC site."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Build verification into your process as soon as you have a finalist, so it doesn't delay the start date."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "When to bring in a direct-hire recruiter"
    },
    {
      "kind": "paragraph",
      "text": "A recruiter makes most sense when:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "The role is permanent, budgeted and hard to fill"
        },
        {
          "text": "Your talent acquisition team is covering too many requisitions (NSI reports only 6.8% of hospitals planned to add recruitment staff in 2026)"
        },
        {
          "text": "You're replacing travel or agency coverage with employed staff"
        },
        {
          "text": "You need to reach passive candidates in a specific specialty or location"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "If you're currently covering nursing vacancies with contract staff, our transition plan for reducing travel staff shows how to phase in permanent hires. You can also see how Talentrax works and our nurse recruitment services.",
      "links": [
        {
          "start": 72,
          "end": 113,
          "href": "/insights/reduce-travel-nurse-reliance"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Metrics to track in nurse hiring"
    },
    {
      "kind": "table",
      "header": [
        "Metric",
        "What it tells you"
      ],
      "rows": [
        [
          "Time to fill, by unit",
          "Where searches stall. Compare with NSI's 78-day national benchmark"
        ],
        [
          "Offer acceptance rate",
          "Whether pay, schedule or process is losing candidates at the end"
        ],
        [
          "Interview-to-offer ratio",
          "Whether screening is sending the right candidates"
        ],
        [
          "90-day and first-year retention",
          "Whether hiring for fit is working (NSI: 22.7% of new RNs leave in year one)"
        ],
        [
          "Vacancy rate",
          "Overall pressure on the unit (NSI national average: 8.6%)"
        ],
        [
          "Contract labor spend",
          "Progress in replacing travel and agency coverage"
        ]
      ]
    }
  ],
  "faqs": [
    {
      "question": "How long does it take to hire a nurse?",
      "answer": [
        {
          "text": "Hospitals take an average of 78 days to recruit an experienced RN, ranging from about 56 to 102 days depending on specialty (NSI, 2026 report). See our 2026 nurse time-to-hire benchmarks.",
          "links": [
            {
              "start": 152,
              "end": 186,
              "href": "/insights/how-long-to-hire-a-nurse"
            }
          ]
        }
      ]
    },
    {
      "question": "What is the nurse turnover rate?",
      "answer": [
        {
          "text": "Hospital staff RN turnover was 17.6% in 2025 (NSI, 2026 report). See our nurse turnover statistics.",
          "links": [
            {
              "start": 73,
              "end": 98,
              "href": "/insights/nurse-turnover-statistics"
            }
          ]
        }
      ]
    },
    {
      "question": "Is there still a nursing shortage?",
      "answer": [
        {
          "text": "Yes, though it varies by place. HRSA projects an 8% national RN shortage in 2028, with much larger shortages in nonmetropolitan areas."
        }
      ]
    },
    {
      "question": "Who verifies a nurse's license during hiring?",
      "answer": [
        {
          "text": "The employer, unless an agreement assigns it elsewhere. Talentrax does not provide license verification; employers typically use their state board of nursing or Nursys."
        }
      ]
    },
    {
      "question": "What's the best way to attract experienced nurses?",
      "answer": [
        {
          "text": "State pay clearly, be specific about unit and schedule, move quickly through interviews, and reach candidates directly rather than relying only on job postings."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Registered Nurses",
      "url": "https://www.bls.gov/ooh/healthcare/registered-nurses.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Nurse Anesthetists, Nurse Midwives, and Nurse Practitioners",
      "url": "https://www.bls.gov/ooh/healthcare/nurse-anesthetists-nurse-midwives-and-nurse-practitioners.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Licensed Practical and Licensed Vocational Nurses",
      "url": "https://www.bls.gov/ooh/healthcare/licensed-practical-and-licensed-vocational-nurses.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Nursing Assistants and Orderlies",
      "url": "https://www.bls.gov/ooh/healthcare/nursing-assistants.htm"
    },
    {
      "name": "HRSA, Nurse Workforce Projections 2023–2038",
      "url": "https://bhw.hrsa.gov/sites/default/files/bureau-health-workforce/data-research/nursing-projections-factsheet.pdf"
    },
    {
      "name": "HRSA, Health Workforce Projections",
      "url": "https://bhw.hrsa.gov/data-research/projecting-health-workforce-supply-demand"
    },
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "American Hospital Association, Assessing the Health Care Environment for 2026",
      "url": "https://www.aha.org/aha-center-health-innovation-market-scan/2025-12-23-assessing-health-care-environment-2026-key-signals-field"
    },
    {
      "name": "NCSBN Nursys",
      "url": "https://www.nursys.com"
    }
  ],
  "related": [
    "direct-hire-healthcare-recruitment"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
