/**
 * GENERATED by scripts/import-articles.ts from "How Long Does It Take to Hire a Nurse - 2026 Benchmarks.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "how-long-to-hire-a-nurse",
  "slug": "how-long-to-hire-a-nurse",
  "title": "How Long Does It Take to Hire a Nurse? 2026 Benchmarks",
  "metaTitle": "How Long Does It Take to Hire a Nurse? 2026 Benchmarks",
  "metaDescription": "Hospitals take 78 days on average to recruit an experienced RN (NSI 2026). See benchmarks by specialty and region, and how to shorten time to hire.",
  "summary": "It takes US hospitals an average of 78 days to recruit an experienced registered nurse, according to the 2026 NSI National Health Care Retention & RN Staffing Report. Depending on specialty, the average ranges from about 56 to 102 days. Telemetry nurses take longest to recruit at 87 days on average, while emergency department nurses are quickest at about 70 days.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "National average: 78 days to recruit an experienced RN, five days faster than the prior year (NSI, 2026 report).",
      "Telemetry (87 days) and med/surg (83 days) take longest; ER is fastest at about 70 days.",
      "Regional averages range from about 70 days in the West to 82 days in the North-Central region.",
      "Magnet-recognized hospitals averaged 68 days."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What is the average time to hire a nurse?"
    },
    {
      "kind": "paragraph",
      "text": "NSI measures time to fill through its RN Recruitment Difficulty Index: the average number of days a hospital takes to recruit an experienced registered nurse. In its 2026 report (covering calendar 2025, 527 hospitals in 40 states), the index stood at 78 days, or more than two and a half months."
    },
    {
      "kind": "paragraph",
      "text": "That's an improvement of five days over the prior year, but NSI notes hospitals remain under pressure: the national RN vacancy rate is 8.6%, and the average hospital carries 43 unfilled RN full-time equivalents."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Time to hire by nursing specialty"
    },
    {
      "kind": "table",
      "header": [
        "Specialty",
        "Average days to recruit an experienced RN (2026 report)"
      ],
      "rows": [
        [
          "Telemetry",
          "87"
        ],
        [
          "Med/surg",
          "83"
        ],
        [
          "Emergency department",
          "About 70"
        ],
        [
          "All specialties (national average)",
          "78"
        ],
        [
          "Range across specialties",
          "About 56 to 102"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: NSI, 2026 National Health Care Retention & RN Staffing Report. The report charts additional specialties; see the full report for details."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Time to hire by region"
    },
    {
      "kind": "table",
      "header": [
        "Region (NSI definition)",
        "Average days"
      ],
      "rows": [
        [
          "West",
          "70"
        ],
        [
          "South-Central (AR, LA, OK, TX)",
          "74"
        ],
        [
          "South-East",
          "About the national average (78)"
        ],
        [
          "North-East",
          "About the national average (78)"
        ],
        [
          "North-Central",
          "82"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Magnet-recognized hospitals averaged 68 days, 10 days faster than the national benchmark. NSI suggests that nurses may be drawn to the culture and standards associated with Magnet recognition, though the survey didn't test this directly."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What the 78-day benchmark does and doesn't measure"
    },
    {
      "kind": "paragraph",
      "text": "NSI's figure is the average time to recruit an experienced RN in an acute-care hospital. It doesn't tell you:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "How long it takes to hire new graduate nurses, who are usually recruited in cohorts around graduation and licensure"
        },
        {
          "text": "Timelines for LPNs, CNAs or nurse practitioners"
        },
        {
          "text": "Timelines in clinics, long-term care or home health"
        },
        {
          "text": "How long the new hire takes to become fully productive after orientation"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Use it as a reference point for experienced hospital RNs, and track your own time to fill by unit and role for a more accurate picture."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why time to hire matters financially"
    },
    {
      "kind": "paragraph",
      "text": "Every day a position is open usually means overtime, float coverage or contract labor. NSI's 2026 report puts the average travel nurse fee at $91.23 an hour, compared with $59.46 an hour for a staff RN including benefits. Over a 78-day search, a position covered by a traveler working 36 hours a week costs roughly $12,700 more than a staff RN would. That is an illustrative estimate based on NSI averages; your costs will differ."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What adds time to a nurse hire?"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Unclear or overly narrow requirements. Every \"must-have\" shrinks the pool."
        },
        {
          "text": "Below-market pay. Candidates decline interviews when the range isn't competitive."
        },
        {
          "text": "Slow resume review and scheduling. Nurses working 12-hour or rotating shifts have limited windows to interview."
        },
        {
          "text": "Too many interview rounds."
        },
        {
          "text": "Notice periods. Experienced nurses usually need to give notice to a current employer."
        },
        {
          "text": "Verification and background checks left until after the offer."
        },
        {
          "text": "Location. HRSA projects RN shortages to remain much larger in nonmetropolitan areas than in metro areas."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to shorten time to hire"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Approve the position and salary range before sourcing starts."
        },
        {
          "text": "Separate true requirements from preferences in the brief."
        },
        {
          "text": "Reserve recurring interview slots each week, including early, late or virtual options."
        },
        {
          "text": "Commit to a review turnaround, such as 48 hours for resumes and feedback."
        },
        {
          "text": "Confirm candidate interest and availability up front so interviews go to people ready to move."
        },
        {
          "text": "Start license verification as soon as you have a finalist."
        },
        {
          "text": "Source proactively instead of waiting for applications, especially for telemetry, med/surg and rural roles."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "A direct-hire recruiter can help with steps 5 and 7. See how the direct-hire recruitment process works.",
      "links": [
        {
          "start": 57,
          "end": 102,
          "href": "/insights/direct-hire-recruitment-process"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "How long does it take to hire an RN?",
      "answer": [
        {
          "text": "On average, 78 days for an experienced RN in a hospital, according to NSI's 2026 report."
        }
      ]
    },
    {
      "question": "Which nursing specialty is hardest to hire?",
      "answer": [
        {
          "text": "In NSI's 2026 report, telemetry nurses took longest to recruit, at 87 days on average, followed by med/surg at 83 days."
        }
      ]
    },
    {
      "question": "Does this benchmark apply to clinics and outpatient settings?",
      "answer": [
        {
          "text": "NSI surveys acute-care hospitals, so treat it as a hospital benchmark. Timelines in clinics and other settings can differ."
        }
      ]
    },
    {
      "question": "How can we hire nurses faster?",
      "answer": [
        {
          "text": "Clarify the brief and pay range before starting, schedule interviews around shifts, move feedback quickly, and source candidates directly rather than relying only on postings."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "HRSA, Health Workforce Projections",
      "url": "https://bhw.hrsa.gov/data-research/projecting-health-workforce-supply-demand"
    }
  ],
  "related": [
    "how-to-hire-nurses",
    "nurse-turnover-statistics"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
