/**
 * GENERATED by scripts/import-articles.ts from "How to Hire Medical Billers and Coders.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "how-to-hire-medical-billers-coders",
  "slug": "how-to-hire-medical-billers-coders",
  "title": "How to Hire Medical Billers and Coders",
  "metaTitle": "How to Hire Medical Billers and Coders (Employer Guide)",
  "metaDescription": "How to hire medical billers and coders: the difference between the roles, CPC, CCS and RHIT credentials, BLS outlook, interview questions and skills tests.",
  "summary": "To hire a medical biller or coder, first decide which role you need (coders translate clinical documentation into diagnosis and procedure codes; billers submit claims, follow up on denials and manage payments), then define your specialty, payer mix and software, look for relevant certifications such as CPC, CCS or RHIT, test skills with a short practical exercise, and verify credentials with the issuing organization. BLS projects medical records specialists, the occupation that includes coders, to grow 8% from 2025 to 2035, with about 14,000 openings a year.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Coding and billing are related but different jobs; many practices combine them, larger organizations usually separate them.",
      "Medical records specialists: 200,700 jobs in 2025, median pay $51,140 (BLS).",
      "Common credentials include AAPC's CPC and AHIMA's CCS and RHIT; employers should verify them.",
      "A short skills test is one of the most reliable ways to assess coding accuracy."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "Medical biller vs. medical coder"
    },
    {
      "kind": "table",
      "header": [
        "",
        "Medical coder",
        "Medical biller"
      ],
      "rows": [
        [
          "Core task",
          "Assigns ICD-10-CM, CPT and HCPCS codes from clinical documentation",
          "Prepares and submits claims, posts payments, works denials and patient balances"
        ],
        [
          "Key knowledge",
          "Coding guidelines, anatomy, medical terminology",
          "Payer rules, claims processes, collections"
        ],
        [
          "Common credentials",
          "CPC (AAPC), CCS (AHIMA), specialty coding credentials",
          "Billing credentials are available; payer experience often matters more"
        ],
        [
          "Typical settings",
          "Hospitals, physician offices, coding companies, remote teams",
          "Physician practices, billing companies, hospital business offices"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "BLS counts coders within \"medical records specialists.\" Billers are counted in broader billing and office occupations."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The hiring market"
    },
    {
      "kind": "table",
      "header": [
        "Measure (medical records specialists)",
        "Figure (BLS)"
      ],
      "rows": [
        [
          "Jobs, 2025",
          "200,700"
        ],
        [
          "Projected growth, 2025–35",
          "8% (much faster than average)"
        ],
        [
          "Annual openings",
          "About 14,000"
        ],
        [
          "Median pay (May 2025)",
          "$51,140"
        ],
        [
          "Largest employers",
          "Hospitals (28%), physician offices (18%)"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Credentials to verify"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "CPC (Certified Professional Coder), issued by AAPC"
        },
        {
          "text": "CCS (Certified Coding Specialist) and RHIT (Registered Health Information Technician), issued by AHIMA"
        },
        {
          "text": "Specialty coding credentials where relevant (for example, for surgical or risk-adjustment coding)"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Confirm certification status directly with AAPC or AHIMA. Talentrax does not provide credential verification."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Job description checklist"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Specialty and setting (for example, orthopedics clinic, hospital outpatient, emergency)"
        },
        {
          "text": "Coding or billing scope, or both"
        },
        {
          "text": "Payer mix (Medicare, Medicaid, commercial)"
        },
        {
          "text": "EHR and billing software"
        },
        {
          "text": "Productivity and accuracy expectations"
        },
        {
          "text": "Remote, hybrid or on-site"
        },
        {
          "text": "Pay range"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Screening and interview questions"
    },
    {
      "kind": "paragraph",
      "text": "For coders"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Which specialties have you coded for, and at what volume?"
        },
        {
          "text": "How do you handle unclear or incomplete documentation?"
        },
        {
          "text": "How do you stay current with annual code changes?"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "For billers"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Which payers and claim types have you worked with?"
        },
        {
          "text": "Walk me through how you work a denied claim."
        },
        {
          "text": "How do you prioritize an aging accounts receivable list?"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "For both: a short practical exercise (coding sample charts, or reviewing sample denials) gives a clearer picture than an interview alone."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Where to find candidates"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Referrals from your revenue cycle team"
        },
        {
          "text": "AAPC and AHIMA local chapters and job boards"
        },
        {
          "text": "Graduates of coding and health information programs"
        },
        {
          "text": "Experienced staff at billing companies and other practices"
        },
        {
          "text": "Remote candidates, if your security policies allow"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "When a recruiter helps"
    },
    {
      "kind": "paragraph",
      "text": "A direct-hire recruiter can help when you need specialty coding experience, a coder-biller hybrid, or a lead for a revenue cycle team. Talentrax helps scope the role, source and screen candidates, submit resumes and schedule interviews. See how Talentrax works."
    }
  ],
  "faqs": [
    {
      "question": "What's the difference between a medical biller and a coder?",
      "answer": [
        {
          "text": "Coders assign codes based on clinical documentation; billers use those codes to prepare and submit claims and follow up on payments and denials."
        }
      ]
    },
    {
      "question": "What certifications should a medical coder have?",
      "answer": [
        {
          "text": "Common ones include CPC from AAPC and CCS or RHIT from AHIMA. Requirements depend on the role and setting."
        }
      ]
    },
    {
      "question": "How much do medical coders earn?",
      "answer": [
        {
          "text": "BLS reports a median of $51,140 in May 2025 for medical records specialists, the occupation that includes coders."
        }
      ]
    },
    {
      "question": "Can medical coders work remotely?",
      "answer": [
        {
          "text": "Many do, depending on the employer's systems and security policies."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Medical Records Specialists",
      "url": "https://www.bls.gov/ooh/healthcare/medical-records-and-health-information-technicians.htm"
    },
    {
      "name": "AAPC",
      "url": "https://www.aapc.com"
    },
    {
      "name": "AHIMA",
      "url": "https://www.ahima.org"
    }
  ],
  "related": [
    "non-clinical-healthcare-hiring"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
