/**
 * GENERATED by scripts/import-articles.ts from "How to Hire Respiratory Therapists.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "how-to-hire-respiratory-therapists",
  "slug": "how-to-hire-respiratory-therapists",
  "title": "How to Hire Respiratory Therapists",
  "metaTitle": "How to Hire Respiratory Therapists: Employer Guide 2027",
  "metaDescription": "How to hire respiratory therapists: licensure in every state but Alaska, CRT vs. RRT, BLS outlook and pay, where to find candidates and interview questions.",
  "summary": "To hire a respiratory therapist, confirm the state license your role requires (every state except Alaska requires one), decide whether you need the Registered Respiratory Therapist (RRT) credential or will accept Certified Respiratory Therapist (CRT), define the units and shift pattern, source through program graduates and direct outreach, and verify the license and NBRC credential before the offer. BLS projects respiratory therapist employment to grow 9% from 2025 to 2035, with about 8,600 openings a year.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "About 142,000 respiratory therapist jobs in 2025; median pay $82,280 (BLS).",
      "Hospitals employ about 80% of respiratory therapists (BLS), so hospitals compete mostly with each other.",
      "Every state except Alaska requires a license (BLS); NBRC's CRT and RRT are the main credentials.",
      "Hospital turnover for respiratory therapists was 14.8% in 2025 (NSI)."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What respiratory therapists do"
    },
    {
      "kind": "paragraph",
      "text": "Respiratory therapists evaluate and treat patients with breathing and cardiopulmonary problems. In hospitals they manage ventilators, airway support and oxygen therapy, respond to emergencies, and work in ICUs, emergency departments and neonatal units."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The hiring market"
    },
    {
      "kind": "table",
      "header": [
        "Measure",
        "Figure (BLS)"
      ],
      "rows": [
        [
          "Jobs, 2025",
          "142,000"
        ],
        [
          "Projected growth, 2025–35",
          "9% (much faster than average)"
        ],
        [
          "Annual openings",
          "About 8,600"
        ],
        [
          "Median pay (May 2025)",
          "$82,280"
        ],
        [
          "Share employed by hospitals",
          "About 80%"
        ],
        [
          "Typical entry-level education",
          "Associate's degree"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Credentials to verify"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "State license (required in every state except Alaska)"
        },
        {
          "text": "NBRC credential: Certified Respiratory Therapist (CRT) or Registered Respiratory Therapist (RRT)"
        },
        {
          "text": "Specialty credentials where relevant, such as neonatal-pediatric or adult critical care specialties"
        },
        {
          "text": "BLS, ACLS or PALS/NRP per your unit's needs"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Verify with the state board and NBRC. Talentrax does not provide license or credential verification."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Job description checklist"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Units covered: adult ICU, neonatal ICU, ED, general floors"
        },
        {
          "text": "Ventilator types and procedures (for example, arterial blood gases, bronchoscopy assistance)"
        },
        {
          "text": "Required credential: CRT accepted or RRT required"
        },
        {
          "text": "Shift pattern, weekends and on-call"
        },
        {
          "text": "Pay range and differentials"
        },
        {
          "text": "Growth: specialty credentials, lead or educator roles"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Where to find candidates"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Graduates of accredited respiratory care programs"
        },
        {
          "text": "Referrals from your respiratory care team"
        },
        {
          "text": "State respiratory care societies and professional networks"
        },
        {
          "text": "Direct outreach to experienced therapists in nearby hospitals"
        },
        {
          "text": "Former employees and past applicants"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Screening and interview questions"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Which units and patient populations have you worked with?"
        },
        {
          "text": "Which ventilator modes and equipment are you comfortable managing?"
        },
        {
          "text": "Do you hold the RRT credential, or plan to?"
        },
        {
          "text": "Describe how you've responded to a rapid response or code."
        },
        {
          "text": "What shift and weekend pattern works for you?"
        },
        {
          "text": "Which specialty credentials interest you?"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Retention considerations"
    },
    {
      "kind": "paragraph",
      "text": "With about 80% of respiratory therapists employed by hospitals, departments that offer credential support, fair shift rotation and a path to specialty or lead roles have an advantage. Respiratory therapist turnover was 14.8% in 2025 (NSI), below the hospital average of 18.5%."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "When a recruiter helps"
    },
    {
      "kind": "paragraph",
      "text": "A direct-hire recruiter can help when you need specific experience (for example, neonatal or adult critical care), the role has been open for months, or local candidates are few. Talentrax helps scope the role, source and screen candidates, submit resumes and schedule interviews. See how Talentrax works."
    }
  ],
  "faqs": [
    {
      "question": "Do respiratory therapists need a license?",
      "answer": [
        {
          "text": "Yes, in every state except Alaska (BLS)."
        }
      ]
    },
    {
      "question": "What's the difference between CRT and RRT?",
      "answer": [
        {
          "text": "Both are NBRC credentials. RRT is the advanced credential and is often required by hospitals, especially for critical care roles."
        }
      ]
    },
    {
      "question": "How much do respiratory therapists earn?",
      "answer": [
        {
          "text": "The BLS median was $82,280 in May 2025."
        }
      ]
    },
    {
      "question": "How fast is respiratory therapist employment growing?",
      "answer": [
        {
          "text": "BLS projects 9% growth from 2025 to 2035, much faster than the 3% average for all occupations."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Respiratory Therapists",
      "url": "https://www.bls.gov/ooh/healthcare/respiratory-therapists.htm"
    },
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "National Board for Respiratory Care (NBRC)",
      "url": "https://www.nbrc.org"
    }
  ],
  "related": [
    "allied-health-recruitment"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
