/**
 * GENERATED by scripts/import-articles.ts: the index of every imported article.
 *
 * Do not edit by hand. Adding or removing an article is a change to the
 * source documents followed by `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

import { article as article_aiHiringLaws } from "./ai-hiring-laws.ts";
import { article as article_aiInHealthcareRecruitment } from "./ai-in-healthcare-recruitment.ts";
import { article as article_alliedHealthRecruitment } from "./allied-health-recruitment.ts";
import { article as article_chooseHealthcareRecruitmentPartner } from "./choose-healthcare-recruitment-partner.ts";
import { article as article_directHireHealthcareRecruitment } from "./direct-hire-healthcare-recruitment.ts";
import { article as article_directHirePlacementFees } from "./direct-hire-placement-fees.ts";
import { article as article_directHireRecruitmentProcess } from "./direct-hire-recruitment-process.ts";
import { article as article_directHireVsContractToHire } from "./direct-hire-vs-contract-to-hire.ts";
import { article as article_directHireVsTravelNurseCost } from "./direct-hire-vs-travel-nurse-cost.ts";
import { article as article_firstYearHealthcareTurnover } from "./first-year-healthcare-turnover.ts";
import { article as article_healthcareCandidateDropOff } from "./healthcare-candidate-drop-off.ts";
import { article as article_healthcareEmployeeTurnover } from "./healthcare-employee-turnover.ts";
import { article as article_healthcareHiringProcess } from "./healthcare-hiring-process.ts";
import { article as article_healthcareHiringTrends2027 } from "./healthcare-hiring-trends-2027.ts";
import { article as article_healthcareStaffingModels } from "./healthcare-staffing-models.ts";
import { article as article_healthcareTimeToFillBenchmarks } from "./healthcare-time-to-fill-benchmarks.ts";
import { article as article_healthcareWorkforceOutlook } from "./healthcare-workforce-outlook.ts";
import { article as article_howLongToHireANurse } from "./how-long-to-hire-a-nurse.ts";
import { article as article_howToHireMedicalBillersCoders } from "./how-to-hire-medical-billers-coders.ts";
import { article as article_howToHireMedicalPracticeManager } from "./how-to-hire-medical-practice-manager.ts";
import { article as article_howToHireNurses } from "./how-to-hire-nurses.ts";
import { article as article_howToHireRadiologicTechnologists } from "./how-to-hire-radiologic-technologists.ts";
import { article as article_howToHireRespiratoryTherapists } from "./how-to-hire-respiratory-therapists.ts";
import { article as article_nonClinicalHealthcareHiring } from "./non-clinical-healthcare-hiring.ts";
import { article as article_nurseTurnoverStatistics } from "./nurse-turnover-statistics.ts";
import { article as article_nursingShortageStatistics } from "./nursing-shortage-statistics.ts";
import { article as article_reduceTravelNurseReliance } from "./reduce-travel-nurse-reliance.ts";
import { article as article_whatIsDirectHireRecruitment } from "./what-is-direct-hire-recruitment.ts";
import { article as article_whyAreHospitalsShortStaffed } from "./why-are-hospitals-short-staffed.ts";
import { article as article_whyCandidatesDeclineOffers } from "./why-candidates-decline-offers.ts";

export const articles: Article[] = [
  article_aiHiringLaws,
  article_aiInHealthcareRecruitment,
  article_alliedHealthRecruitment,
  article_chooseHealthcareRecruitmentPartner,
  article_directHireHealthcareRecruitment,
  article_directHirePlacementFees,
  article_directHireRecruitmentProcess,
  article_directHireVsContractToHire,
  article_directHireVsTravelNurseCost,
  article_firstYearHealthcareTurnover,
  article_healthcareCandidateDropOff,
  article_healthcareEmployeeTurnover,
  article_healthcareHiringProcess,
  article_healthcareHiringTrends2027,
  article_healthcareStaffingModels,
  article_healthcareTimeToFillBenchmarks,
  article_healthcareWorkforceOutlook,
  article_howLongToHireANurse,
  article_howToHireMedicalBillersCoders,
  article_howToHireMedicalPracticeManager,
  article_howToHireNurses,
  article_howToHireRadiologicTechnologists,
  article_howToHireRespiratoryTherapists,
  article_nonClinicalHealthcareHiring,
  article_nurseTurnoverStatistics,
  article_nursingShortageStatistics,
  article_reduceTravelNurseReliance,
  article_whatIsDirectHireRecruitment,
  article_whyAreHospitalsShortStaffed,
  article_whyCandidatesDeclineOffers,
];
