/**
 * GENERATED by scripts/import-articles.ts from "Job Hugging - How to Recruit Professionals Who Aren't Looking to Move.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "@/features/articles";

export const article: Article = {
  "id": "job-hugging-recruiting-passive-candidates",
  "slug": "job-hugging-recruiting-passive-candidates",
  "title": "Job Hugging: How to Recruit Professionals Who Aren't Looking to Move",
  "metaTitle": "Job Hugging: How to Recruit Professionals Who Aren't Moving",
  "metaDescription": "Job hugging explained: why fewer professionals are changing jobs (US quits rate 1.9%) and six ways to recruit employed candidates who aren't looking.",
  "summary": "\"Job hugging\" describes employees holding on to their current jobs rather than looking for new ones, usually because the job market feels uncertain. For employers, it means the strongest candidates for professional roles are mostly employed, cautious and unlikely to respond to a job posting. Recruiting them takes direct outreach, a clear and specific reason to move, transparent pay, and a fast, low-risk process.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "The term was popularized by Korn Ferry in August 2025 as the opposite of job hopping.",
      "The US quits rate was 1.9% in July 2026, and 1.8% in professional and business services, down from about 3% at the 2022 peak (BLS JOLTS).",
      "Cautious candidates weigh risk as much as reward: stability, clarity about the role and pay, and a trustworthy process matter.",
      "Expect counteroffers, and prepare for them before the offer stage."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What is job hugging?"
    },
    {
      "kind": "paragraph",
      "text": "Job hugging is the tendency of employees to stay in their current roles, even when they're not fully satisfied, because moving feels risky. Korn Ferry introduced the phrase in August 2025 to describe employees holding on to their jobs \"for dear life,\" and the term spread through business media later that year."
    },
    {
      "kind": "paragraph",
      "text": "Commentators link it to three things: slower hiring, uncertainty about the economy, and concern about how AI might change jobs."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What the data shows"
    },
    {
      "kind": "table",
      "header": [
        "Indicator",
        "Latest figure",
        "Source"
      ],
      "rows": [
        [
          "Quits rate, all US workers",
          "1.9% (July 2026)",
          "BLS JOLTS, via FRED"
        ],
        [
          "Quits rate, professional and business services",
          "1.8% (July 2026)",
          "BLS JOLTS, via FRED"
        ],
        [
          "Quits rate at the 2022 peak",
          "About 3%",
          "BLS JOLTS"
        ],
        [
          "Job openings, all US",
          "About 7.3 million (July 2026)",
          "BLS JOLTS"
        ],
        [
          "Unemployment rate",
          "4.1% (August 2026)",
          "BLS"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "A lower quits rate means fewer people are voluntarily leaving jobs each month, so fewer experienced candidates are actively on the market."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why job hugging makes hiring harder"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Postings reach fewer strong candidates. People who aren't looking don't browse job boards."
        },
        {
          "text": "The bar for moving is higher. A candidate leaving a secure job needs a clear reason: better role, better pay, better stability or better flexibility."
        },
        {
          "text": "Perceived risk matters. \"Last in, first out\" worries make candidates cautious about new employers."
        },
        {
          "text": "Current employers fight to keep people. Counteroffers are common when a valued employee resigns."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to recruit candidates who aren't looking"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "1. Reach out directly"
    },
    {
      "kind": "paragraph",
      "text": "Identify people doing the same or adjacent work at other organizations and contact them personally. A specific, relevant message about a specific role performs better than a generic invitation."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "2. Lead with a concrete reason to move"
    },
    {
      "kind": "paragraph",
      "text": "Be ready to explain, in a sentence or two, why this role is better than what they have: scope, growth, schedule, team, pay or stability. Vague \"exciting opportunity\" language doesn't move cautious people."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "3. Be transparent about pay early"
    },
    {
      "kind": "paragraph",
      "text": "Many states now require pay ranges in job postings. Even where they don't, sharing the range in the first conversation saves time and builds trust. WTW's 2026 survey found 36% of employers report hiring at higher salary ranges, so check that your range competes."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "4. Reduce the perceived risk"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Explain why the role exists (growth, backfill or new function)"
        },
        {
          "text": "Describe the team, manager and how performance is measured"
        },
        {
          "text": "Be honest about the organization's direction"
        },
        {
          "text": "Offer conversations with future colleagues"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "5. Make the process fast and respectful"
    },
    {
      "kind": "paragraph",
      "text": "Employed candidates can walk away at any point. Keep interviews to what's needed, schedule around their current job, and give feedback quickly. SHRM's 2025 benchmarking puts the median time to fill at about 45 days across industries."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "6. Prepare for the counteroffer"
    },
    {
      "kind": "paragraph",
      "text": "Ask early: \"If your employer offered you more to stay, what would you do?\" Understand what's driving the candidate's interest beyond pay, and make sure your offer addresses it."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Retention: the other side of job hugging"
    },
    {
      "kind": "paragraph",
      "text": "Low quit rates can hide disengagement. Employees who stay only because the market feels risky may leave quickly when conditions improve. Regular career conversations, fair pay reviews and clear growth paths help keep your own people from becoming someone else's passive candidates."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How a direct-hire recruiter helps"
    },
    {
      "kind": "paragraph",
      "text": "Reaching employed professionals is time-consuming. A direct-hire recruiter can identify and approach them, screen for interest, fit, availability and salary expectations, and submit resumes only for candidates ready to engage. Talentrax helps scope the role, source and screen candidates, submit resumes and schedule interviews. See how Talentrax works."
    }
  ],
  "faqs": [
    {
      "question": "What does job hugging mean?",
      "answer": [
        {
          "text": "Employees holding on to their current jobs rather than looking for new ones, often because the job market feels uncertain."
        }
      ]
    },
    {
      "question": "Who coined the term job hugging?",
      "answer": [
        {
          "text": "Korn Ferry introduced the phrase in August 2025, and it was widely reported by business media later that year."
        }
      ]
    },
    {
      "question": "How do you recruit passive candidates?",
      "answer": [
        {
          "text": "Contact them directly about a specific role, explain clearly why it's a better move, share pay early, reduce the perceived risk, and keep the process short."
        }
      ]
    },
    {
      "question": "Is job hugging still happening in 2026?",
      "answer": [
        {
          "text": "Quit rates remained low through mid-2026: 1.9% of US workers quit in July 2026 (BLS JOLTS)."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "Wikipedia, Job hugging (origin and early coverage)",
      "url": "https://en.wikipedia.org/wiki/Job_hugging"
    },
    {
      "name": "Axios, \"With labor market weak, employees are 'job hugging'\" (August 2025)",
      "url": "https://www.axios.com/2025/08/21/jobs-market-hiring-ai"
    },
    {
      "name": "BLS JOLTS via FRED, Quits rate, total nonfarm (JTSQUR)",
      "url": "https://fred.stlouisfed.org/series/JTSQUR"
    },
    {
      "name": "BLS JOLTS via FRED, Quits rate, professional and business services (JTS540099QUR)",
      "url": "https://fred.stlouisfed.org/series/JTS540099QUR"
    },
    {
      "name": "US Bureau of Labor Statistics, Job Openings and Labor Turnover Summary (July 2026)",
      "url": "https://www.bls.gov/news.release/jolts.nr0.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Employment Situation (August 2026)",
      "url": "https://www.bls.gov/news.release/empsit.nr0.htm"
    },
    {
      "name": "WTW, Salary Increase Budgets Expected to Average 3.4% in 2027",
      "url": "https://www.wtwco.com/en-us/news/2026/07/employers-shift-from-bigger-pay-budgets-to-smarter-pay-strategies-wtw-finds"
    },
    {
      "name": "SHRM, The State of Recruiting 2025",
      "url": "https://www.shrm.org/executive-network/insights/people-strategy/state-of-recruiting-2025-insights-to-maximize-recruitment"
    }
  ],
  "related": [
    "non-it-hiring-trends-2027",
    "pay-transparency-laws-2026"
  ],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
