/**
 * GENERATED by scripts/import-articles.ts from "Non-IT Hiring Trends for 2027 - What Employers Need to Know.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "non-it-hiring-trends-2027",
  "slug": "non-it-hiring-trends-2027",
  "title": "Non-IT Hiring Trends for 2027: What Employers Need to Know",
  "metaTitle": "Non-IT Hiring Trends for 2027: What Employers Need to Know",
  "metaDescription": "Eight non-IT hiring trends for 2027: low quit rates, pay budgets, pay transparency laws, CPA reform, AI, office policies and skills gaps. Sourced data.",
  "summary": "Non-IT hiring in 2027 is shaped by a slow-moving labor market where fewer people quit, a growing set of pay transparency laws, AI reshaping clerical and entry-level work, firmer office-attendance expectations, and persistent skills gaps in accounting, manufacturing and supply chain. For employers hiring professional and operations roles, the practical result is that good candidates are mostly employed and cautious, so recruiting has to be more targeted, more transparent and faster.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Quits are low: 1.9% of US workers quit in July 2026, and 1.8% in professional and business services (BLS JOLTS).",
      "Pay budgets are steady: US employers project 3.4% salary increases for 2027 (WTW).",
      "Virginia, Maine and Connecticut added pay-range posting laws in 2026; Delaware follows in 2027.",
      "89% of employers now expect at least three office days a week (CBRE, 2026)."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "1. A \"low-hire, low-quit\" labor market"
    },
    {
      "kind": "paragraph",
      "text": "The US added 162,000 jobs in August 2026, and unemployment held at 4.1% (BLS). But movement between jobs is slow. The quits rate was 1.9% in July 2026, well below the roughly 3% seen at the 2022 peak, and job openings stood at about 7.3 million (BLS JOLTS)."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: most qualified candidates are employed and not actively searching. Job postings alone reach fewer of them. See job hugging: how to recruit professionals who aren't looking to move.",
      "links": [
        {
          "start": 140,
          "end": 208,
          "href": "/insights/job-hugging-recruiting-passive-candidates"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "2. Moderate pay budgets, targeted increases"
    },
    {
      "kind": "paragraph",
      "text": "WTW's 2026 survey of 1,650 US companies found employers project average salary increases of 3.4% for 2027, close to 2026's actual 3.5%. Rather than larger across-the-board raises, 36% report hiring at higher salary ranges and 32% are raising starting salary ranges."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: pay for hard-to-fill roles is being set role by role. Benchmark each critical role rather than relying on a single company-wide increase."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "3. More pay transparency laws"
    },
    {
      "kind": "paragraph",
      "text": "Pay-range posting laws now cover much of the country. In 2026, Virginia (July 1), Maine (July 29) and Connecticut (October 1) added or expanded requirements, and Delaware's law takes effect September 26, 2027 (Jackson Lewis; Littler)."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: job postings, including those placed by recruiters, need accurate ranges in more places. See pay transparency laws in 2026 and 2027.",
      "links": [
        {
          "start": 122,
          "end": 160,
          "href": "/insights/pay-transparency-laws-2026"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "4. CPA licensing reform and the accounting talent gap"
    },
    {
      "kind": "paragraph",
      "text": "As of July 2026, 44 states and Puerto Rico had enacted an alternative CPA licensure pathway that allows a bachelor's degree plus two years of experience instead of 150 credit hours (CFO Dive). BLS projects about 115,300 openings a year for accountants and auditors through 2035."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: the pool of CPA-eligible candidates is changing. See how to hire accountants as CPA rules change.",
      "links": [
        {
          "start": 82,
          "end": 125,
          "href": "/insights/hiring-accountants-cpa-pathway"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "5. AI is reshaping clerical and junior work"
    },
    {
      "kind": "paragraph",
      "text": "BLS projects employment of secretaries and administrative assistants to decline 2% and bookkeeping, accounting and auditing clerks to decline 6% from 2025 to 2035, citing technology and automation. Stanford researchers found employment for workers aged 22 to 25 in highly AI-exposed occupations was about 19% below trend in 2026, with no comparable gap for experienced workers."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: job descriptions should shift toward judgment, systems and analysis. See how AI is changing administrative, accounting and HR roles.",
      "links": [
        {
          "start": 102,
          "end": 160,
          "href": "/insights/ai-impact-admin-finance-hr-roles"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "6. A mixed market for new graduates"
    },
    {
      "kind": "paragraph",
      "text": "Employers told NACE they plan to hire 5.6% more graduates from the class of 2026, yet the New York Fed reports unemployment for recent college graduates at about 5.6% and underemployment at 42% (Q2 2026)."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: strong graduates are available, but entry-level roles need redesigning as routine tasks change. See entry-level hiring in 2027.",
      "links": [
        {
          "start": 129,
          "end": 155,
          "href": "/insights/entry-level-hiring-2027"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "7. Firmer office expectations"
    },
    {
      "kind": "paragraph",
      "text": "CBRE's 2026 survey found 89% of employers require at least three office days a week, up from 78% in 2025, with an average expectation of 3.2 days and average actual attendance of 2.9 days."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: your office policy defines your candidate pool. Be explicit about it early. See return-to-office and hybrid work: how flexibility affects hiring.",
      "links": [
        {
          "start": 109,
          "end": 173,
          "href": "/insights/return-to-office-hiring"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "8. Skills gaps in manufacturing and supply chain"
    },
    {
      "kind": "paragraph",
      "text": "Deloitte and The Manufacturing Institute estimate manufacturers could need up to 3.8 million workers by 2033, with 1.9 million roles at risk of going unfilled. BLS projects logistician employment to grow 18% from 2025 to 2035."
    },
    {
      "kind": "paragraph",
      "text": "What it means for employers: operations roles need long lead times and active sourcing. See our guides to manufacturing hiring and supply chain and logistics hiring.",
      "links": [
        {
          "start": 106,
          "end": 126,
          "href": "/insights/manufacturing-hiring-skills-gap"
        },
        {
          "start": 131,
          "end": 164,
          "href": "/insights/supply-chain-logistics-hiring"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to prepare your 2027 hiring plan"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Plan for passive candidates: allow time and budget for direct outreach."
        },
        {
          "text": "Benchmark pay by role and publish accurate ranges where required."
        },
        {
          "text": "Rewrite job descriptions around the skills that matter now."
        },
        {
          "text": "State your office policy clearly in every posting and first conversation."
        },
        {
          "text": "Move quickly once a strong candidate engages; SHRM's 2025 benchmarking puts the median time to fill at about 45 days across industries."
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "What are the biggest non-IT hiring trends for 2027?",
      "answer": [
        {
          "text": "Low quit rates, moderate pay budgets, new pay transparency laws, CPA licensing reform, AI changes to clerical and entry-level roles, firmer office expectations, and skills gaps in manufacturing and supply chain."
        }
      ]
    },
    {
      "question": "Is it harder to hire professionals in 2027?",
      "answer": [
        {
          "text": "For many roles, yes, because fewer people are changing jobs. Candidates are available, but most are employed and need a clear reason to move."
        }
      ]
    },
    {
      "question": "Are salaries rising in 2027?",
      "answer": [
        {
          "text": "Moderately. WTW reports US employers project 3.4% average increases for 2027, with larger adjustments targeted at hard-to-fill roles."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Employment Situation (August 2026)",
      "url": "https://www.bls.gov/news.release/empsit.nr0.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Job Openings and Labor Turnover Summary (July 2026)",
      "url": "https://www.bls.gov/news.release/jolts.nr0.htm"
    },
    {
      "name": "BLS JOLTS via FRED, Quits rate, total nonfarm (JTSQUR)",
      "url": "https://fred.stlouisfed.org/series/JTSQUR"
    },
    {
      "name": "BLS JOLTS via FRED, Quits rate, professional and business services (JTS540099QUR)",
      "url": "https://fred.stlouisfed.org/series/JTS540099QUR"
    },
    {
      "name": "WTW, Salary Increase Budgets Expected to Average 3.4% in 2027 (July 2026)",
      "url": "https://www.wtwco.com/en-us/news/2026/07/employers-shift-from-bigger-pay-budgets-to-smarter-pay-strategies-wtw-finds"
    },
    {
      "name": "Jackson Lewis, Midyear Pay Transparency Update (July 2026)",
      "url": "https://www.jacksonlewis.com/insights/midyear-pay-transparency-update-job-postings-lead-employer-responsibilities"
    },
    {
      "name": "Jackson Lewis, Navigating 2026: Pay Transparency Laws (January 2026)",
      "url": "https://www.jacksonlewis.com/insights/navigating-2026-pay-transparency-laws-and-employer-obligations"
    },
    {
      "name": "CFO Dive, Tracking CPA licensure paths (updated July 2026)",
      "url": "https://www.cfodive.com/news/broadening-cpa-licensure-paths-marching-beyond-150-hour-rule-accounting-talent-shortage/745282/"
    },
    {
      "name": "US Bureau of Labor Statistics, Occupational Outlook Handbook (Accountants and Auditors; Secretaries and Administrative Assistants; Bookkeeping, Accounting, and Auditing Clerks; Logisticians)",
      "url": "https://www.bls.gov/ooh/"
    },
    {
      "name": "Stanford Digital Economy Lab, Canaries in the Coal Mine update (August 2026)",
      "url": "https://digitaleconomy.stanford.edu/news/canariesaug26/"
    },
    {
      "name": "NACE, Job Outlook 2026 Spring Update",
      "url": "https://www.naceweb.org/research/reports/2026/job-outlook/spring-update/"
    },
    {
      "name": "Federal Reserve Bank of New York, The Labor Market for Recent College Graduates",
      "url": "https://www.newyorkfed.org/research/college-labor-market"
    },
    {
      "name": "CBRE, 2026 Americas Office Occupier Sentiment Survey",
      "url": "https://www.cbre.com/insights/reports/2026-americas-office-occupier-sentiment-survey"
    },
    {
      "name": "The Manufacturing Institute, Manufacturers Need as Many as 3.8 Million New Employees by 2033",
      "url": "https://themanufacturinginstitute.org/manufacturers-need-as-many-as-3-8-million-new-employees-by-2033/"
    },
    {
      "name": "SHRM, The State of Recruiting 2025",
      "url": "https://www.shrm.org/executive-network/insights/people-strategy/state-of-recruiting-2025-insights-to-maximize-recruitment"
    }
  ],
  "related": [],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
