/**
 * GENERATED by scripts/import-articles.ts from "Nursing Shortage Statistics Current HRSA and BLS Data.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "nursing-shortage-statistics",
  "slug": "nursing-shortage-statistics",
  "title": "Nursing Shortage Statistics (Current HRSA and BLS Data)",
  "metaTitle": "Nursing Shortage Statistics 2026: HRSA and BLS Data",
  "metaDescription": "Nursing shortage statistics: HRSA projects an 8% RN shortage in 2028 and 11% in rural areas by 2038. Plus BLS openings and hospital vacancy data.",
  "summary": "HRSA projects the United States will be about 8% short of the registered nurses it needs in 2028, narrowing to 3% (about 108,960 full-time-equivalent RNs) by 2038. The gap is much wider outside cities: HRSA projects an 11% RN shortage in nonmetropolitan areas in 2038, compared with 2% in metro areas. Meanwhile, hospitals report an 8.6% RN vacancy rate and take 78 days on average to recruit an experienced RN (NSI, 2026 report).",
  "keyTakeaways": {
    "heading": "Key statistics at a glance",
    "items": [
      "Projected national RN shortage: 8% in 2028; 3% in 2038 (HRSA)",
      "Projected RN shortage in 2038: 11% nonmetro vs. 2% metro (HRSA)",
      "RN openings per year: about 180,800 (BLS, 2025–35)",
      "Hospital RN vacancy rate: 8.6% (NSI, 2026)",
      "Nurses who left the workforce 2022–2024: more than 138,000 (AHA)",
      "Nurses intending to leave or retire within five years: 40% (AHA)"
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "Data current as of September 2026."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "National RN supply and demand projections"
    },
    {
      "kind": "table",
      "header": [
        "Year",
        "Projected RN shortage (FTE)",
        "Source"
      ],
      "rows": [
        [
          "2028",
          "8%",
          "HRSA, Nurse Workforce Projections 2023–2038"
        ],
        [
          "2038",
          "3% (about 108,960 FTE RNs)",
          "HRSA"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "HRSA calculates the shortage as one minus supply adequacy (projected supply divided by projected demand), measured in full-time equivalents of 40 hours a week."
    },
    {
      "kind": "paragraph",
      "text": "A note on older figures: many websites still quote HRSA's previous projections (10% in 2027 and 6% in 2037, from the 2022–2037 series). The figures above are from the newer 2023–2038 series."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Metro vs. nonmetro shortages"
    },
    {
      "kind": "table",
      "header": [
        "Area (2038)",
        "Projected RN shortage"
      ],
      "rows": [
        [
          "Nonmetropolitan",
          "11%"
        ],
        [
          "Metropolitan",
          "2%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Source: HRSA, Health Workforce Projections."
    },
    {
      "kind": "paragraph",
      "text": "Rural facilities face the combination of higher projected shortages and smaller local candidate pools."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "LPN and nursing assistant outlook"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "HRSA projects a proportionally larger shortfall for licensed practical nurses than for RNs."
        },
        {
          "text": "BLS projects about 51,800 LPN/LVN openings a year and about 203,300 openings a year for nursing assistants and orderlies from 2025 to 2035, mostly to replace workers who leave."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Nursing workforce size and growth (BLS)"
    },
    {
      "kind": "table",
      "header": [
        "Occupation",
        "Jobs, 2025",
        "Growth, 2025–35",
        "Annual openings",
        "Median pay (May 2025)"
      ],
      "rows": [
        [
          "Registered nurses",
          "3,465,400",
          "6%",
          "About 180,800",
          "$97,550"
        ],
        [
          "Nurse practitioners",
          "336,300",
          "41%",
          "Included in about 32,200 for all APRNs",
          "$132,300"
        ],
        [
          "LPNs/LVNs",
          "666,900",
          "3%",
          "About 51,800",
          "$64,400"
        ],
        [
          "Nursing assistants and orderlies",
          "1,558,700",
          "3%",
          "About 203,300",
          "$42,260 (nursing assistants)"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Hospital vacancy and hiring data (NSI, 2026 report)"
    },
    {
      "kind": "table",
      "header": [
        "Metric",
        "Value"
      ],
      "rows": [
        [
          "RN vacancy rate",
          "8.6%"
        ],
        [
          "Hospitals with RN vacancy of 10% or more",
          "33.1%"
        ],
        [
          "Average unfilled RN FTEs per hospital",
          "43"
        ],
        [
          "NSI's estimate of the current national RN shortage (hospitals)",
          "158,600"
        ],
        [
          "Time to recruit an experienced RN",
          "78 days"
        ],
        [
          "Staff RN turnover",
          "17.6%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "NSI's estimate of 158,600 is based on its hospital survey and differs from HRSA's projection method."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Nurses leaving the workforce"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "The American Hospital Association's 2026 Environmental Scan reports that more than 138,000 nurses left the workforce between 2022 and 2024, and 40% of nurses report an intent to leave or retire within five years."
        },
        {
          "text": "Retirement is now the third most common reason hospital RNs resign (NSI, 2026 report)."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "About these statistics"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "HRSA projections model supply and demand in FTEs and assume historical patterns of graduation, attrition and participation continue."
        },
        {
          "text": "BLS projections estimate employment and openings, not shortages."
        },
        {
          "text": "NSI surveys acute-care hospitals (527 hospitals in 40 states for the 2026 report)."
        },
        {
          "text": "Each source measures something different, so they shouldn't be combined into a single \"shortage\" number."
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "How big is the nursing shortage in the US?",
      "answer": [
        {
          "text": "HRSA projects an 8% shortage of full-time-equivalent RNs nationally in 2028, narrowing to 3% by 2038."
        }
      ]
    },
    {
      "question": "Where is the nursing shortage worst?",
      "answer": [
        {
          "text": "In rural areas. HRSA projects an 11% RN shortage in nonmetropolitan areas in 2038, compared with 2% in metro areas."
        }
      ]
    },
    {
      "question": "How many nurses are needed each year?",
      "answer": [
        {
          "text": "BLS projects about 180,800 RN openings a year from 2025 to 2035, mostly to replace nurses who retire or leave the occupation."
        }
      ]
    },
    {
      "question": "Is the nursing shortage getting better?",
      "answer": [
        {
          "text": "HRSA's projections show the national gap narrowing through 2038, but hospital vacancy and turnover remain elevated and rural shortages persist."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "HRSA, Nurse Workforce Projections 2023–2038",
      "url": "https://bhw.hrsa.gov/sites/default/files/bureau-health-workforce/data-research/nursing-projections-factsheet.pdf"
    },
    {
      "name": "HRSA, Health Workforce Projections",
      "url": "https://bhw.hrsa.gov/data-research/projecting-health-workforce-supply-demand"
    },
    {
      "name": "US Bureau of Labor Statistics, Registered Nurses",
      "url": "https://www.bls.gov/ooh/healthcare/registered-nurses.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Nurse Anesthetists, Nurse Midwives, and Nurse Practitioners",
      "url": "https://www.bls.gov/ooh/healthcare/nurse-anesthetists-nurse-midwives-and-nurse-practitioners.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Licensed Practical and Licensed Vocational Nurses",
      "url": "https://www.bls.gov/ooh/healthcare/licensed-practical-and-licensed-vocational-nurses.htm"
    },
    {
      "name": "US Bureau of Labor Statistics, Nursing Assistants and Orderlies",
      "url": "https://www.bls.gov/ooh/healthcare/nursing-assistants.htm"
    },
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "American Hospital Association, Assessing the Health Care Environment for 2026",
      "url": "https://www.aha.org/aha-center-health-innovation-market-scan/2025-12-23-assessing-health-care-environment-2026-key-signals-field"
    }
  ],
  "related": [
    "healthcare-workforce-outlook",
    "how-to-hire-nurses",
    "nurse-turnover-statistics"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
