/**
 * GENERATED by scripts/import-articles.ts from "Nurse Turnover Rate and Cost - 2026 Statistics.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "nurse-turnover-statistics",
  "slug": "nurse-turnover-statistics",
  "title": "Nurse Turnover Rate and Cost: 2026 Statistics",
  "metaTitle": "Nurse Turnover Rate 2026: Statistics and Cost (NSI Data)",
  "metaDescription": "Hospital RN turnover was 17.6% in 2025, and each departure costs $60,090 (NSI 2026). Turnover by specialty, region, role and first year, with sources.",
  "summary": "The average turnover rate for hospital staff registered nurses was 17.6% in 2025, up 1.2 percentage points from the prior year, according to the 2026 NSI National Health Care Retention & RN Staffing Report. Each bedside RN who leaves costs the average hospital $60,090, and hospitals lost an average of $5.19 million to RN turnover in 2025.",
  "keyTakeaways": {
    "heading": "Key statistics at a glance (calendar 2025)",
    "items": [
      "Staff RN turnover: 17.6% (median 18.6%)",
      "All hospital employee turnover: 18.5%",
      "Cost of one bedside RN turnover: $60,090",
      "Average annual hospital loss to RN turnover: $5.19 million",
      "Each 1-point change in RN turnover: about $295,000 a year for the average hospital",
      "Newly hired RNs who left within a year: 22.7%",
      "RN vacancy rate: 8.6%"
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "Data source: NSI 2026 National Health Care Retention & RN Staffing Report (calendar 2025 data)."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "RN turnover over five years"
    },
    {
      "kind": "table",
      "header": [
        "Calendar year",
        "Staff RN turnover",
        "All hospital employees"
      ],
      "rows": [
        [
          "2021",
          "27.1%",
          "25.9%"
        ],
        [
          "2022",
          "22.5%",
          "22.7%"
        ],
        [
          "2023",
          "18.4%",
          "20.7%"
        ],
        [
          "2024",
          "16.4%",
          "18.3%"
        ],
        [
          "2025",
          "17.6%",
          "18.5%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "After falling steadily from its 2021 peak, RN turnover rose again in 2025. Over the five years, the average hospital turned over 102% of its RN workforce."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Turnover range and benchmarks"
    },
    {
      "kind": "table",
      "header": [
        "Percentile",
        "Staff RN turnover"
      ],
      "rows": [
        [
          "Top 10% of hospitals (90th percentile)",
          "11.5% or lower"
        ],
        [
          "75th percentile",
          "13.8%"
        ],
        [
          "Median",
          "18.6%"
        ],
        [
          "25th percentile",
          "21.6%"
        ],
        [
          "Bottom 10% (10th percentile)",
          "25.7% or higher"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Across hospitals of different sizes, RN turnover ranged from 5.6% to 40.0%. Hospitals that count only full-time and part-time RNs reported an average of 14.6%."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "RN turnover by specialty (2025)"
    },
    {
      "kind": "table",
      "header": [
        "Specialty",
        "RN turnover"
      ],
      "rows": [
        [
          "Behavioral health",
          "22.5%"
        ],
        [
          "Emergency",
          "20.7%"
        ],
        [
          "Telemetry",
          "19.5%"
        ],
        [
          "Step-down",
          "19.0%"
        ],
        [
          "Med/surg",
          "18.1%"
        ],
        [
          "Critical care",
          "17.6%"
        ],
        [
          "Burn center",
          "17.5%"
        ],
        [
          "Women's health",
          "15.0%"
        ],
        [
          "Surgical services",
          "14.9%"
        ],
        [
          "Pediatrics",
          "13.4%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Over five years, cumulative RN turnover was highest in telemetry (117.8%), step-down (115.4%) and emergency (113.6%). In practical terms, these units turn over their entire RN staff in less than four and a half years. Surgical services (78.8%) and pediatrics (75.6%) were the most stable."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "RN turnover by region (2025)"
    },
    {
      "kind": "table",
      "header": [
        "Region",
        "Staff RN turnover",
        "Change from prior year"
      ],
      "rows": [
        [
          "North-East",
          "17.9%",
          "+3.3 points"
        ],
        [
          "North-Central",
          "16.2%",
          "+0.4 points"
        ],
        [
          "South-East",
          "18.7%",
          "+1.4 points"
        ],
        [
          "South-Central",
          "17.1%",
          "-0.9 points"
        ],
        [
          "West",
          "18.4%",
          "+2.3 points"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Turnover by hospital role (2025)"
    },
    {
      "kind": "table",
      "header": [
        "Role",
        "Turnover"
      ],
      "rows": [
        [
          "Patient care technician",
          "33.8%"
        ],
        [
          "Certified nursing assistant",
          "32.5%"
        ],
        [
          "Environmental services",
          "27.6%"
        ],
        [
          "Registered nurse",
          "17.6%"
        ],
        [
          "Radiologic technologist",
          "15.5%"
        ],
        [
          "Medical technologist",
          "15.5%"
        ],
        [
          "Speech therapist",
          "15.0%"
        ],
        [
          "Respiratory therapist",
          "14.8%"
        ],
        [
          "Occupational therapist",
          "12.9%"
        ],
        [
          "Physical therapist",
          "11.1%"
        ],
        [
          "Pharmacist",
          "10.7%"
        ],
        [
          "Nurse practitioner",
          "9.8%"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "NSI notes that advanced practice and allied health professionals have recorded turnover below the hospital average for eight consecutive years."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "First-year turnover"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "22.7% of newly hired RNs left within their first year."
        },
        {
          "text": "First-year departures made up 29.0% of all RN separations."
        },
        {
          "text": "Across all hospital employees, 29.5% of new hires left within a year."
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "First-year turnover is one of the clearest links between hiring practices and retention, though NSI's survey doesn't measure the causes of individual departures. Confirming a candidate's interest, schedule fit and expectations before an offer, and supporting new hires through structured onboarding, both help reduce it. NSI reports 74% of hospitals have a formal retention strategy, and nurse residency programs were rated 3.9 out of 5 for effectiveness."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "The cost of nurse turnover"
    },
    {
      "kind": "table",
      "header": [
        "Measure",
        "Value"
      ],
      "rows": [
        [
          "Cost of one bedside RN turnover",
          "$60,090"
        ],
        [
          "Average hospital annual loss to RN turnover",
          "$5.19 million"
        ],
        [
          "Typical range of annual loss",
          "$4.2 million to $6.2 million"
        ],
        [
          "Cost or saving per 1-point change in RN turnover",
          "About $295,000 a year"
        ],
        [
          "Hospitals that track the cost of turnover",
          "46.1%"
        ]
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why registered nurses leave"
    },
    {
      "kind": "paragraph",
      "text": "NSI's respondents identified the top reasons staff RNs resigned:"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Personal issues"
        },
        {
          "text": "Relocation"
        },
        {
          "text": "Retirement"
        },
        {
          "text": "Career advancement"
        },
        {
          "text": "Scheduling conflict"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "The rest of the top 10: education, salary, commute, working conditions, and workload or staffing ratios. Retirement has been rising steadily and is now the third most common reason."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "About the data"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Source: NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report, published March 2026."
        },
        {
          "text": "Coverage: 527 acute-care hospitals in 40 states, covering 965,886 healthcare workers and 262,405 RNs, reporting January to December 2025."
        },
        {
          "text": "Method: turnover = separations divided by average number of employees. Temporary, agency and travel staff were excluded, and internal transfers weren't counted."
        },
        {
          "text": "Scope: acute-care hospitals only. Rates in clinics, long-term care and home health may differ."
        },
        {
          "text": "Publisher note: NSI is a nurse recruitment and retention firm. We cite its survey data, not its service claims."
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "What is the nurse turnover rate in 2026?",
      "answer": [
        {
          "text": "The most recent data, NSI's 2026 report covering calendar 2025, puts hospital staff RN turnover at 17.6%."
        }
      ]
    },
    {
      "question": "How much does nurse turnover cost?",
      "answer": [
        {
          "text": "NSI estimates the average cost of one bedside RN turnover at $60,090, and the average hospital lost $5.19 million to RN turnover in 2025."
        }
      ]
    },
    {
      "question": "Which nursing specialties have the highest turnover?",
      "answer": [
        {
          "text": "Behavioral health (22.5%), emergency (20.7%) and telemetry (19.5%) had the highest RN turnover in 2025."
        }
      ]
    },
    {
      "question": "What percentage of new nurses quit in the first year?",
      "answer": [
        {
          "text": "22.7% of newly hired RNs left within their first year, according to NSI's 2026 report."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    }
  ],
  "related": [
    "how-to-hire-nurses",
    "how-long-to-hire-a-nurse",
    "direct-hire-vs-travel-nurse-cost"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
