/**
 * GENERATED by scripts/import-articles.ts from "Pay Transparency Laws in 2026 and 2027 - What Employers Must Put in Job Postings.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "@/features/articles";

export const article: Article = {
  "id": "pay-transparency-laws-2026",
  "slug": "pay-transparency-laws-2026",
  "title": "Pay Transparency Laws in 2026 and 2027: What Employers Must Put in Job Postings",
  "metaTitle": "Pay Transparency Laws 2026-2027: Job Posting Requirements",
  "metaDescription": "Which states require pay ranges in job postings in 2026 and 2027, what's new (Virginia, Maine, Connecticut, Delaware), recruiter postings, and a checklist.",
  "summary": "Most pay transparency laws require employers to include a good-faith pay range, and sometimes a description of benefits, in job postings for roles covered by the law. In 2026, Virginia (July 1), Maine (July 29) and Connecticut (October 1) added or expanded posting requirements, and Delaware's law takes effect September 26, 2027. Because several laws also apply to postings placed through recruiters and to remote roles tied to a covered state, multi-state employers increasingly publish ranges everywhere.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "More than 15 states plus Washington, DC and several Ohio cities now have pay-range posting or disclosure laws.",
      "New in 2026: Virginia, Maine and Connecticut (expanded). Coming in 2027: Delaware.",
      "Some laws, such as Massachusetts', apply to postings made directly or through recruiters.",
      "The safest practice for multi-state hiring is an accurate, good-faith range in every posting."
    ]
  },
  "body": [
    {
      "kind": "paragraph",
      "text": "This article is general information, not legal advice."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What pay transparency laws usually require"
    },
    {
      "kind": "paragraph",
      "text": "Requirements vary by jurisdiction, but most include some of the following:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "A pay range in job postings: the range the employer reasonably and in good faith expects to pay"
        },
        {
          "text": "A general description of benefits (in states such as Colorado, Connecticut, Illinois, Maryland and New Jersey)"
        },
        {
          "text": "Disclosure to current employees on request, or for promotion and transfer opportunities"
        },
        {
          "text": "No retaliation against employees who ask about pay"
        },
        {
          "text": "Record-keeping of pay history in some states (for example, Maine)"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Where the laws apply"
    },
    {
      "kind": "table",
      "header": [
        "Jurisdiction",
        "Employer threshold",
        "Main requirement",
        "Status"
      ],
      "rows": [
        [
          "California",
          "15+ employees",
          "Pay scale",
          "In effect"
        ],
        [
          "Colorado",
          "1+ employee",
          "Pay range and benefits",
          "In effect"
        ],
        [
          "Connecticut",
          "All employers",
          "Wage range and general benefits description in postings",
          "Expanded October 1, 2026"
        ],
        [
          "Delaware",
          "26+ employees",
          "Pay range and benefits",
          "Effective September 26, 2027"
        ],
        [
          "Hawaii",
          "50+ employees",
          "Hourly rate or salary range",
          "In effect"
        ],
        [
          "Illinois",
          "15+ employees",
          "Pay scale and benefits",
          "In effect"
        ],
        [
          "Maine",
          "10+ employees",
          "Pay range",
          "Effective July 29, 2026"
        ],
        [
          "Maryland",
          "Covered postings",
          "Wage range and benefits",
          "In effect"
        ],
        [
          "Massachusetts",
          "25+ employees",
          "Pay range (including postings through recruiters)",
          "Effective October 29, 2025"
        ],
        [
          "Minnesota",
          "30+ employees",
          "Starting salary range",
          "In effect"
        ],
        [
          "Nevada",
          "All employers",
          "Wage or salary range disclosed to applicants after an interview (not necessarily in postings)",
          "In effect"
        ],
        [
          "New Jersey",
          "10+ employees",
          "Pay range and benefits",
          "In effect"
        ],
        [
          "New York",
          "4+ employees",
          "Compensation range",
          "In effect"
        ],
        [
          "Rhode Island",
          "All employers",
          "Wage range disclosed on request and before discussing pay (not necessarily in postings)",
          "In effect"
        ],
        [
          "Vermont",
          "5+ employees",
          "Compensation or range",
          "In effect"
        ],
        [
          "Virginia",
          "All employers",
          "Wage, salary or range in public and internal postings",
          "Effective July 1, 2026"
        ],
        [
          "Washington",
          "15+ employees",
          "Salary range",
          "In effect"
        ],
        [
          "Washington, DC",
          "1+ employee",
          "Minimum and maximum projected pay",
          "In effect"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Several Ohio cities, including Cincinnati, Cleveland, Columbus and Toledo, also have local requirements."
    },
    {
      "kind": "paragraph",
      "text": "Sources: Jackson Lewis (January and July 2026), Littler (Maine, April 2026), Seyfarth Shaw (Massachusetts). Summarized; check each law's text and any local ordinances for your obligations."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What's new in 2026 and 2027"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Virginia (July 1, 2026): all employers must include the wage, salary or range in public and internal postings for jobs, promotions and transfers."
        },
        {
          "text": "Maine (July 29, 2026): employers with 10 or more employees must include the range they expect to rely on; employees can request their own position's range; pay history records must be kept during employment and for three years after."
        },
        {
          "text": "Connecticut (October 1, 2026): moves from disclosure on request to requiring a wage range and a general description of benefits in job advertisements."
        },
        {
          "text": "Delaware (September 26, 2027): employers with 26 or more employees must include a pay range and benefits."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What this means when you use a recruiter"
    },
    {
      "kind": "paragraph",
      "text": "Some laws explicitly cover postings made through third parties. Massachusetts, for example, applies to positions posted directly or through recruiters. When you work with a recruiting firm:"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Give the recruiter a written, good-faith range for every role"
        },
        {
          "text": "Confirm which jurisdictions the role touches, including remote roles tied to a covered state"
        },
        {
          "text": "Keep ranges consistent across your own postings and the recruiter's"
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Practical compliance checklist"
    },
    {
      "kind": "list",
      "ordered": true,
      "items": [
        {
          "text": "Map where you hire, including remote roles and roles reporting to supervisors in covered states."
        },
        {
          "text": "Set a real range for every role before posting, based on what you genuinely expect to pay."
        },
        {
          "text": "Add a benefits summary where required."
        },
        {
          "text": "Align internal and external postings in states that cover promotions and transfers."
        },
        {
          "text": "Train hiring managers to answer pay questions consistently and never retaliate."
        },
        {
          "text": "Keep records of ranges, postings and pay decisions."
        },
        {
          "text": "Review quarterly, since new laws continue to pass."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Pay transparency beyond compliance"
    },
    {
      "kind": "paragraph",
      "text": "Transparent ranges also help recruiting. Candidates, especially employed ones, are more willing to engage when pay is clear, and it saves time for both sides. See job hugging: how to recruit professionals who aren't looking to move.",
      "links": [
        {
          "start": 163,
          "end": 231,
          "href": "/insights/job-hugging-recruiting-passive-candidates"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Which states require salary ranges in job postings?",
      "answer": [
        {
          "text": "As of October 2026, states requiring pay information in postings include California, Colorado, Connecticut, Hawaii, Illinois, Maine, Maryland, Massachusetts, Minnesota, New Jersey, New York, Vermont, Virginia and Washington, plus Washington, DC. Nevada and Rhode Island require disclosure to applicants rather than in postings. Delaware's law takes effect in September 2027."
        }
      ]
    },
    {
      "question": "Do pay transparency laws apply to recruiters?",
      "answer": [
        {
          "text": "Some do. Massachusetts' law, for example, covers positions posted directly or through recruiters. Employers should give recruiters accurate ranges."
        }
      ]
    },
    {
      "question": "Do I have to include benefits in job postings?",
      "answer": [
        {
          "text": "In some states, such as Colorado, Connecticut, Illinois, Maryland and New Jersey, a general description of benefits is required."
        }
      ]
    },
    {
      "question": "What is a good-faith pay range?",
      "answer": [
        {
          "text": "The range an employer reasonably expects to pay for the role at the time of posting, not an artificially wide range."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "Jackson Lewis, Midyear Pay Transparency Update: Job Postings Lead Employer Responsibilities (July 15, 2026)",
      "url": "https://www.jacksonlewis.com/insights/midyear-pay-transparency-update-job-postings-lead-employer-responsibilities"
    },
    {
      "name": "Jackson Lewis, Navigating 2026: Pay Transparency Laws and Employer Obligations (January 30, 2026)",
      "url": "https://www.jacksonlewis.com/insights/navigating-2026-pay-transparency-laws-and-employer-obligations"
    },
    {
      "name": "Littler, Maine Enacts Wage Transparency Law (April 27, 2026)",
      "url": "https://www.littler.com/news-analysis/asap/maine-enacts-wage-transparency-law"
    },
    {
      "name": "Seyfarth Shaw, Massachusetts Pay Transparency Law Takes Effect",
      "url": "https://www.seyfarth.com/news-insights/massachusetts-pay-transparency-law-takes-effect-what-employers-need-to-know.html"
    }
  ],
  "related": [
    "non-it-hiring-trends-2027"
  ],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
