/**
 * GENERATED by scripts/import-articles.ts from "Return-to-Office and Hybrid Work - How Flexibility Affects Hiring Professionals.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "@/features/articles";

export const article: Article = {
  "id": "return-to-office-hiring",
  "slug": "return-to-office-hiring",
  "title": "Return-to-Office and Hybrid Work: How Flexibility Affects Hiring Professionals",
  "metaTitle": "Return-to-Office and Hybrid Work: The Hiring Impact",
  "metaDescription": "89% of employers now require 3+ office days (CBRE 2026). How office policies affect candidate pools and how to recruit professionals under your policy.",
  "summary": "Office-attendance expectations have tightened: CBRE's 2026 survey found 89% of employers now require at least three office days a week, up from 78% in 2025, with an average expectation of 3.2 days. For hiring, your attendance policy effectively defines your candidate pool. The more days required, the smaller the commuting radius you can recruit from, and the more clearly the policy, pay and other benefits need to be explained upfront.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "89% of employers require three or more office days a week (CBRE, 2026).",
      "Actual attendance averages 2.9 days, below the 3.2-day expectation.",
      "Nearly one-third of organizations expect attendance to increase further.",
      "State the policy precisely in postings and first conversations to avoid late-stage drop-off."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What the data shows"
    },
    {
      "kind": "table",
      "header": [
        "Measure",
        "2026",
        "2025",
        "Source"
      ],
      "rows": [
        [
          "Employers requiring 3+ office days a week",
          "89%",
          "78%",
          "CBRE Americas Office Occupier Sentiment Survey"
        ],
        [
          "Employers expecting 1–2 days",
          "11%",
          "23%",
          "CBRE"
        ],
        [
          "Average days expected",
          "3.2",
          "Not stated",
          "CBRE"
        ],
        [
          "Average actual attendance",
          "2.9 days",
          "2.8 days",
          "CBRE"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "CBRE describes three days as \"the new standard,\" and for the fourth year in a row, nearly one-third of organizations expect attendance to rise over time."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How office policy affects hiring"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Commuting radius. A daily commute limits candidates to a smaller area than a two- or three-day hybrid schedule does."
        },
        {
          "text": "Candidate expectations. Many professionals have worked hybrid schedules for years; some will decline roles that require more office time than they have now."
        },
        {
          "text": "Late-stage surprises. If the policy isn't clear until the offer, candidates may withdraw after weeks of interviews."
        },
        {
          "text": "Competition. In a market where fewer people change jobs, flexibility can be the reason a candidate moves, or stays put."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "How to recruit under your policy"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Be precise, early"
    },
    {
      "kind": "paragraph",
      "text": "State the number of office days, whether they're fixed or flexible, and whether exceptions exist. \"Hybrid\" alone means different things to different people."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Match the policy to the role"
    },
    {
      "kind": "paragraph",
      "text": "Some roles genuinely need daily presence (for example, plant or front-office operations). Others may work well with fewer office days. Where you have flexibility, use it deliberately."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Widen or narrow the search accordingly"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Fully on-site roles: focus sourcing on the local commuting area and consider relocation support for hard-to-fill positions."
        },
        {
          "text": "Hybrid roles: you can recruit from a somewhat wider area; check state pay transparency rules for remote-eligible roles."
        },
        {
          "text": "Remote roles: check employment, tax and pay-posting rules in each state where the employee will work."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Make the office worth the commute"
    },
    {
      "kind": "paragraph",
      "text": "Explain what in-person time is for (collaboration, training, client work) and what support exists: parking, transit, schedule predictability."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "Compensate thoughtfully"
    },
    {
      "kind": "paragraph",
      "text": "If your policy requires more office time than competitors, candidates may expect higher pay or other benefits. WTW's 2026 survey found 36% of employers report hiring at higher salary ranges."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Keeping the policy consistent"
    },
    {
      "kind": "paragraph",
      "text": "Offer terms should match what was said in interviews. Changing the attendance expectation after someone starts is a common cause of early turnover."
    }
  ],
  "faqs": [
    {
      "question": "How many days a week do employers require in the office in 2026?",
      "answer": [
        {
          "text": "CBRE's 2026 survey found an average expectation of 3.2 days, and 89% of employers require at least three."
        }
      ]
    },
    {
      "question": "Does a return-to-office policy make hiring harder?",
      "answer": [
        {
          "text": "It narrows the pool of candidates who can commute, and some candidates prefer more flexibility. Being clear about the policy early reduces drop-off."
        }
      ]
    },
    {
      "question": "Should job postings state the office policy?",
      "answer": [
        {
          "text": "Yes. Stating the exact number of office days avoids misunderstandings and saves time for both sides."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "CBRE, 2026 Americas Office Occupier Sentiment Survey (July 2026)",
      "url": "https://www.cbre.com/insights/reports/2026-americas-office-occupier-sentiment-survey"
    },
    {
      "name": "WTW, Salary Increase Budgets Expected to Average 3.4% in 2027",
      "url": "https://www.wtwco.com/en-us/news/2026/07/employers-shift-from-bigger-pay-budgets-to-smarter-pay-strategies-wtw-finds"
    }
  ],
  "related": [
    "job-hugging-recruiting-passive-candidates",
    "pay-transparency-laws-2026"
  ],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
