/**
 * GENERATED by scripts/import-articles.ts from "Skills-Based Hiring for Non-IT Roles - From Promise to Practice.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "skills-based-hiring",
  "slug": "skills-based-hiring",
  "title": "Skills-Based Hiring for Non-IT Roles: From Promise to Practice",
  "metaTitle": "Skills-Based Hiring for Non-IT Roles: Making It Work",
  "metaDescription": "Why most skills-based hiring efforts stall (fewer than 1 in 700 hires affected) and a six-step method that works for accounting, HR and operations roles.",
  "summary": "Skills-based hiring means selecting candidates based on demonstrated skills rather than proxies such as degrees or job titles. It works only when employers change how they assess candidates, not just what their job postings say. A 2024 study by the Burning Glass Institute and Harvard Business School found that fewer than 1 in 700 hires in 2023 benefited from employers dropping degree requirements, because most companies removed the requirement on paper but kept hiring the same way.",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Nearly 70% of employers in NACE's 2026 survey of new-graduate hiring say they use skills-based approaches when evaluating candidates.",
      "But only 37% of firms that dropped degree requirements meaningfully changed who they hired (Burning Glass Institute and HBS).",
      "63% of employers cite skills gaps as the main barrier to transforming their business (WEF, 2025).",
      "The fix is practical: define skills per role, assess them directly, and train interviewers."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "What the evidence says"
    },
    {
      "kind": "paragraph",
      "text": "The Burning Glass Institute and Harvard Business School studied roles at large firms that removed degree requirements. Their February 2024 report found:"
    },
    {
      "kind": "table",
      "header": [
        "Group",
        "Share of firms",
        "What happened"
      ],
      "rows": [
        [
          "Leaders",
          "37%",
          "Increased hiring of non-degree workers by nearly 20% in affected roles"
        ],
        [
          "In name only",
          "45%",
          "No meaningful change in hiring behavior"
        ],
        [
          "Backsliders",
          "18%",
          "Initial gains that later reversed"
        ]
      ]
    },
    {
      "kind": "paragraph",
      "text": "Overall, the number of roles dropping degree requirements increased nearly fourfold from 2014 to 2023, yet the net effect on who was hired was very small."
    },
    {
      "kind": "paragraph",
      "text": "The lesson: rewriting a posting doesn't change a hiring manager's shortlist. Assessment methods have to change too."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Why it matters now for non-IT roles"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Skills are shifting. The World Economic Forum's Future of Jobs Report 2025 names analytical thinking as the most sought-after core skill (cited by 69% of employers), followed by resilience and flexibility, and leadership."
        },
        {
          "text": "Candidate pools are tight in accounting, operations and manufacturing. Degree filters exclude capable people with relevant experience."
        },
        {
          "text": "Early-career hiring is changing as AI takes over some routine tasks, which makes demonstrated skills more telling than credentials alone."
        }
      ]
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "A six-step method that works"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "1. Define the skills for each role"
    },
    {
      "kind": "paragraph",
      "text": "List the four to six skills that truly predict success. For an accounts payable specialist, that might be accuracy with high volumes, ERP use, vendor communication and exception handling."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "2. Separate true requirements from proxies"
    },
    {
      "kind": "paragraph",
      "text": "Ask whether a degree, certification or years of experience is legally or technically required, or just a shortcut. Keep what's required; convert the rest to skills."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "3. Rewrite the posting around skills"
    },
    {
      "kind": "paragraph",
      "text": "Describe what the person will do and what they need to be able to do. Where a credential is genuinely required (for example, a CPA for SEC reporting), say so clearly."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "4. Assess skills directly"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Work samples: a short, realistic task, such as a reconciliation, a scheduling problem or a draft policy memo"
        },
        {
          "text": "Structured interviews: the same job-related questions for every candidate, scored against the same criteria"
        },
        {
          "text": "Scenario questions: \"What would you do if…\" based on real situations in the role"
        }
      ]
    },
    {
      "kind": "paragraph",
      "text": "Keep assessments job-related and consistent, and review them for fairness."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "5. Train and align interviewers"
    },
    {
      "kind": "paragraph",
      "text": "Hiring managers need to know what skills they're assessing and how to score them. Without this, old habits return."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "6. Measure results"
    },
    {
      "kind": "paragraph",
      "text": "Track who gets interviewed, hired and retained, and how new hires perform. If the shortlist looks the same as before, the process hasn't changed."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Common pitfalls"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Removing degree requirements but screening resumes the same way"
        },
        {
          "text": "Using long, unpaid assessments that drive candidates away"
        },
        {
          "text": "Different interviewers asking different questions"
        },
        {
          "text": "No follow-up on whether new hires succeed"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "What is skills-based hiring?",
      "answer": [
        {
          "text": "Selecting candidates based on demonstrated skills rather than proxies such as degrees or previous titles."
        }
      ]
    },
    {
      "question": "Does skills-based hiring work?",
      "answer": [
        {
          "text": "It can, but research shows most employers that dropped degree requirements didn't change who they hired. Results depend on changing assessments and interviewer behavior, not just postings."
        }
      ]
    },
    {
      "question": "How do you assess skills in an interview?",
      "answer": [
        {
          "text": "Use short, realistic work samples and structured questions scored against consistent criteria."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "Burning Glass Institute and Harvard Business School, Skills-Based Hiring: The Long Road from Pronouncements to Practice (February 2024), as reported by HR Dive",
      "url": "https://www.hrdive.com/news/employers-failing-at-skills-based-hiring/707897/"
    },
    {
      "name": "Harvard Business School, Institute for Business in Global Society",
      "url": "https://www.hbs.edu/bigs/joseph-fuller-college-degree-gap"
    },
    {
      "name": "NACE, Job Outlook 2026 Spring Update (April 2026)",
      "url": "https://www.naceweb.org/research/reports/2026/job-outlook/spring-update/"
    },
    {
      "name": "World Economic Forum, Future of Jobs Report 2025, as reported by Staffing Industry Analysts",
      "url": "https://www.staffingindustry.com/news/global-daily-news/world-to-add-170-million-jobs-by-2030-lose-92-million"
    },
    {
      "name": "World Economic Forum, Future of Jobs Report 2025 (full report)",
      "url": "https://reports.weforum.org/docs/WEF_Future_of_Jobs_Report_2025.pdf"
    }
  ],
  "related": [
    "entry-level-hiring-2027",
    "ai-impact-admin-finance-hr-roles"
  ],
  "datePublished": "2026-09-30",
  "dateModified": "2026-09-30"
};
