/**
 * GENERATED by scripts/import-articles.ts from "Why Are Hospitals Short-Staffed.docx".
 *
 * Do not edit by hand: the next import overwrites this file. Fix the
 * source document and re-run `npm run import:articles -- <dir>`.
 */

import type { Article } from "../../lib/insights";

export const article: Article = {
  "id": "why-are-hospitals-short-staffed",
  "slug": "why-are-hospitals-short-staffed",
  "title": "Why Are Hospitals Short-Staffed?",
  "metaTitle": "Why Are Hospitals Short-Staffed? 6 Reasons (2026 Data)",
  "metaDescription": "Why hospitals are short-staffed: rising demand, retirements, high turnover, rural gaps, slow hiring and limited budgets. Six reasons with 2026 data.",
  "summary": "Hospitals are short-staffed because demand for care is rising faster than the supply of trained workers, experienced staff are leaving or retiring, turnover remains high, shortages are concentrated in rural areas and certain specialties, and hiring takes months. On average, US hospitals have an 8.6% RN vacancy rate and take 78 days to recruit an experienced RN (NSI, 2026 report).",
  "keyTakeaways": {
    "heading": "Key takeaways",
    "items": [
      "Demand is growing: BLS projects about 1.9 million healthcare openings a year through 2035.",
      "Workers are leaving: more than 138,000 nurses left the workforce between 2022 and 2024 (AHA).",
      "Turnover is high: 18.5% of hospital employees and 17.6% of staff RNs left in 2025 (NSI).",
      "Hiring is slow: 78 days on average to recruit an experienced RN (NSI)."
    ]
  },
  "body": [
    {
      "kind": "heading",
      "level": 2,
      "text": "Six reasons hospitals are short-staffed"
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "1. Demand for care keeps growing"
    },
    {
      "kind": "paragraph",
      "text": "The Bureau of Labor Statistics projects healthcare support and practitioner occupations to be the fastest-growing groups in the economy from 2025 to 2035, driven largely by an aging population and chronic conditions."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "2. Experienced workers are leaving or retiring"
    },
    {
      "kind": "paragraph",
      "text": "The American Hospital Association reports more than 138,000 nurses left the workforce between 2022 and 2024, and 40% of nurses intend to leave or retire within five years. Retirement is now the third most common reason hospital RNs resign (NSI, 2026 report)."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "3. Turnover keeps creating new vacancies"
    },
    {
      "kind": "paragraph",
      "text": "Hospital turnover was 18.5% across all employees in 2025. Frontline roles turn over fastest: about one-third of patient care technicians and CNAs left their hospital jobs in a year (NSI, 2026 report)."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "4. Shortages are concentrated in certain places and specialties"
    },
    {
      "kind": "paragraph",
      "text": "HRSA projects an 11% RN shortage in nonmetropolitan areas in 2038, compared with 2% in metro areas. Within hospitals, behavioral health, emergency and telemetry have the highest RN turnover."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "5. Hiring takes months"
    },
    {
      "kind": "paragraph",
      "text": "It takes 78 days on average to recruit an experienced RN, and 87 days for telemetry (NSI, 2026 report). Healthcare and social assistance also has more job openings per 100 jobs (5.7 in July 2026) than the economy overall (4.4) (BLS JOLTS)."
    },
    {
      "kind": "heading",
      "level": 3,
      "text": "6. Budgets and recruiting capacity are limited"
    },
    {
      "kind": "paragraph",
      "text": "Only 6.8% of hospitals planned to add recruitment staff in 2026, and hospitals average about 0.26 recruiters per 100 employees (NSI). Financial pressures, including Medicaid changes beginning in 2027, add uncertainty."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "Is it getting better?"
    },
    {
      "kind": "paragraph",
      "text": "Partly. HRSA projects the national RN shortage to narrow from 8% in 2028 to 3% in 2038, and NSI's 2026 report shows time to fill improving by five days and a lower RN vacancy rate (though NSI changed how it calculates vacancy this year). But turnover rose again in 2025, and rural shortages are projected to remain."
    },
    {
      "kind": "heading",
      "level": 2,
      "text": "What hospitals can do"
    },
    {
      "kind": "list",
      "ordered": false,
      "items": [
        {
          "text": "Convert ongoing contract positions to permanent roles"
        },
        {
          "text": "Start searches earlier for hard-to-fill units"
        },
        {
          "text": "Improve first-year retention with structured onboarding"
        },
        {
          "text": "Build internal float pools for short-term gaps"
        },
        {
          "text": "Add recruiting capacity where internal teams are stretched"
        }
      ]
    }
  ],
  "faqs": [
    {
      "question": "Why is there a shortage of nurses in hospitals?",
      "answer": [
        {
          "text": "Growing demand, retirements, high turnover, uneven geographic supply and long hiring timelines all contribute."
        }
      ]
    },
    {
      "question": "Are hospitals still short-staffed in 2026?",
      "answer": [
        {
          "text": "Yes. NSI's 2026 report found an average RN vacancy rate of 8.6%, with one-third of hospitals at 10% or higher."
        }
      ]
    },
    {
      "question": "Which hospital departments are most affected?",
      "answer": [
        {
          "text": "Behavioral health, emergency and telemetry have the highest RN turnover, and telemetry RNs take longest to recruit (NSI, 2026 report)."
        }
      ]
    }
  ],
  "sources": [
    {
      "name": "US Bureau of Labor Statistics, Employment Projections 2025–35",
      "url": "https://www.bls.gov/news.release/ecopro.nr0.htm"
    },
    {
      "name": "HRSA, Health Workforce Projections",
      "url": "https://bhw.hrsa.gov/data-research/projecting-health-workforce-supply-demand"
    },
    {
      "name": "NSI Nursing Solutions, 2026 National Health Care Retention & RN Staffing Report",
      "url": "https://www.nsinursingsolutions.com/documents/library/nsi_national_health_care_retention_report.pdf"
    },
    {
      "name": "American Hospital Association, Assessing the Health Care Environment for 2026",
      "url": "https://www.aha.org/aha-center-health-innovation-market-scan/2025-12-23-assessing-health-care-environment-2026-key-signals-field"
    },
    {
      "name": "BLS JOLTS via FRED, Job Openings: Health Care and Social Assistance",
      "url": "https://fred.stlouisfed.org/series/JTS6200JOR"
    },
    {
      "name": "BLS, Job Openings and Labor Turnover Summary (July 2026)",
      "url": "https://www.bls.gov/news.release/jolts.nr0.htm"
    },
    {
      "name": "KFF, Medicaid Work Requirements Tracker",
      "url": "https://www.kff.org/medicaid/medicaid-work-requirements-tracker-overview/"
    }
  ],
  "related": [
    "healthcare-workforce-outlook",
    "nursing-shortage-statistics",
    "reduce-travel-nurse-reliance"
  ],
  "datePublished": "2026-09-25",
  "dateModified": "2026-09-25"
};
