/**
 * Unit tests for redrawing the enrolment QR code.
 *
 * A QR code that is drawn wrong fails silently: the phone simply will not
 * read it. So the conversion is pinned on a document shaped like the one
 * Supabase Auth returns (one 3x3 <rect> per module, black or white).
 */

import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { qrFromSvg } from "./totp-qr.ts";

function document(size: number, black: [number, number][]): string {
  const rects: string[] = [];
  for (let row = 0; row < size; row++) {
    for (let col = 0; col < size; col++) {
      const fill = black.some(([r, c]) => r === row && c === col) ? "black" : "white";
      rects.push(`<rect x="${col * 3}" y="${row * 3}" width="3" height="3" style="fill:${fill};stroke:none" />`);
    }
  }
  return `<?xml version="1.0"?>\n<!-- Generated by SVGo -->\n<svg width="${size * 3}" height="${size * 3}"\n     xmlns="http://www.w3.org/2000/svg">\n${rects.join("\n")}\n</svg>\n`;
}

describe("qrFromSvg", () => {
  it("draws each run of black modules in a row as one rectangle, in module units", () => {
    const qr = qrFromSvg(document(4, [[0, 0], [0, 1], [0, 3], [2, 2]]));
    assert.deepEqual(qr, { size: 4, path: "M0 0h2v1h-2zM3 0h1v1h-1zM2 2h1v1h-1z" });
  });

  it("draws nothing white", () => {
    assert.equal(qrFromSvg(document(3, [[1, 1]]))?.path, "M1 1h1v1h-1z");
  });

  it("refuses anything that is not the expected uniform grid", () => {
    assert.equal(qrFromSvg("<svg></svg>"), null);
    assert.equal(qrFromSvg(document(3, [])), null);
    const mixed = document(3, [[0, 0]]).replace('width="3" height="3" style="fill:black', 'width="4" height="4" style="fill:black');
    assert.equal(qrFromSvg(mixed), null);
  });
});
