/**
 * import-articles.ts - import the client's .docx articles into
 * src/content/articles/, one typed file per article plus an index.
 *
 *   node scripts/import-articles.ts <directory-of-docx> [--date YYYY-MM-DD]
 *   npm run import:articles -- <directory-of-docx>
 *
 * The parser, not a transcription. Thirty articles copied by hand would
 * drift from the source in thirty small ways; this reads the .docx XML
 * directly and emits the content, so a re-import is repeatable and a diff
 * against the previous import is meaningful. Node's own zlib inflates the
 * .docx (it is a zip), so there is no dependency to install.
 *
 * WHAT COUNTS AS AN ARTICLE. A document with a "SEO and optimization notes"
 * section. Anything else in the directory (the strategy documents and the
 * monthly optimization audits) is internal planning material: it is skipped,
 * reported, and never written anywhere.
 *
 * WHAT IS STRIPPED, so it can never reach the site:
 *   - the whole "SEO and optimization notes (not for publication)" section,
 *     including the quality-control and confirm-before-publishing tables.
 *     Three fields are read out of it first (SEO title, meta description and
 *     the URL, which supplies the slug) and the rest is discarded;
 *   - the byline placeholder "By [Author name], [Title], ...". No named
 *     people anywhere on this site, and no bracketed placeholders;
 *   - the "Related reading" / "Learn more" / closing call-to-action
 *     sections, which are link lists. Links to other imported articles are
 *     kept as `related` slugs; the call-to-action prose in them is dropped
 *     and reported.
 *
 * INLINE LINKS are carried as marks on the prose: a paragraph, list item or
 * FAQ answer is `{ text, links: [{ start, end, href }] }`, offsets into the
 * text. Every href is resolved before it is written:
 *   - a link to an imported article becomes `/insights/<slug>`;
 *   - a link to a page this site has (a `src/app/<path>/page.tsx` exists)
 *     becomes that path;
 *   - an https link elsewhere is kept as it is;
 *   - anything else (the documents link to pages that were never built)
 *     keeps its text and loses the link, and the target is reported.
 * Links inside table cells and the takeaways box are dropped and counted:
 * cells are plain strings.
 *
 * WHAT IS PRESERVED EXACTLY: every figure and every attribution. The
 * site-wide no-statistics rule bans invented claims about Talentrax's own
 * performance; the cited third-party data in these articles is their whole
 * value. Nothing here rounds, restates or drops a number, and every source
 * comes through with its URL.
 *
 * BRAND. The documents spell the name "TalentRax". The site is "Talentrax"
 * (see CLAUDE.md) and the fix is applied to every string on the way out.
 *
 * DATES. The documents carry "Last updated: <Month> <Year>", and most of
 * those months are in the future relative to the import. A BlogPosting with
 * a future datePublished is wrong, so a future month is never imported:
 * the article gets the import date instead and is listed in the report. A
 * month already in the past becomes the first of that month. Once an
 * article has been written to src/content/articles/, its datePublished is
 * preserved across re-imports and its dateModified moves only when its
 * content changes.
 *
 * The script fails loudly, with the file name, on anything it does not
 * recognise: a heading level it has not seen, a list item outside a list,
 * a missing takeaways table. Silent tolerance is how a stripped section
 * comes back.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, resolve } from "node:path";
import { inflateRawSync } from "node:zlib";

import type {
  Article,
  ArticleBlock,
  ArticleFaq,
  ArticleSource,
  LinkMark,
  RichText,
} from "../src/lib/insights.ts";

/* ------------------------------------------------------------- arguments */

const OUTPUT_DIR = resolve(import.meta.dirname, "../src/content/articles");
const APP_DIR = resolve(import.meta.dirname, "../src/app");
const GENERATED_MARKER = "GENERATED by scripts/import-articles.ts";
const SITE_ORIGIN = /^https:\/\/(?:www\.)?talentraxglobal\.com(?=[/?#]|$)/;

const args = process.argv.slice(2);
const dateFlag = args.indexOf("--date");
const importDate =
  dateFlag >= 0 ? (args[dateFlag + 1] ?? "") : localIsoDate(new Date());
const sourceDir = args.filter(
  (_, i) => dateFlag < 0 || (i !== dateFlag && i !== dateFlag + 1),
)[0];

if (!sourceDir || !/^\d{4}-\d{2}-\d{2}$/.test(importDate)) {
  console.error(
    "usage: node scripts/import-articles.ts <directory-of-docx> [--date YYYY-MM-DD]",
  );
  process.exit(2);
}

function localIsoDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}

/* ------------------------------------------------------------ zip reader */

/**
 * Minimal zip reader: central directory, then each local entry, inflated
 * with node:zlib. Enough for a .docx, which is stored or deflated and never
 * zip64, and it keeps the importer dependency free.
 */
function readZip(buffer: Buffer): Map<string, Buffer> {
  let eocd = buffer.length - 22;
  while (eocd >= 0 && buffer.readUInt32LE(eocd) !== 0x06054b50) eocd -= 1;
  if (eocd < 0) throw new Error("not a zip file");

  const count = buffer.readUInt16LE(eocd + 10);
  let offset = buffer.readUInt32LE(eocd + 16);
  const entries = new Map<string, Buffer>();

  for (let i = 0; i < count; i += 1) {
    if (buffer.readUInt32LE(offset) !== 0x02014b50) {
      throw new Error("corrupt central directory");
    }
    const method = buffer.readUInt16LE(offset + 10);
    const compressedSize = buffer.readUInt32LE(offset + 20);
    const nameLength = buffer.readUInt16LE(offset + 28);
    const extraLength = buffer.readUInt16LE(offset + 30);
    const commentLength = buffer.readUInt16LE(offset + 32);
    const localOffset = buffer.readUInt32LE(offset + 42);
    const name = buffer.toString("utf8", offset + 46, offset + 46 + nameLength);

    const localNameLength = buffer.readUInt16LE(localOffset + 26);
    const localExtraLength = buffer.readUInt16LE(localOffset + 28);
    const dataStart = localOffset + 30 + localNameLength + localExtraLength;
    const data = buffer.subarray(dataStart, dataStart + compressedSize);

    if (method === 0) entries.set(name, Buffer.from(data));
    else if (method === 8) entries.set(name, inflateRawSync(data));
    else throw new Error(`unsupported zip method ${method} for ${name}`);

    offset += 46 + nameLength + extraLength + commentLength;
  }
  return entries;
}

/* ----------------------------------------------------------- docx model */

type Run = { text: string; href: string | null };
type Paragraph = { style: string; numId: string | null; runs: Run[] };
/** row -> cell -> paragraphs, plus the hrefs the cells carried */
type Table = { rows: string[][][]; links: string[] };
type Node = { kind: "p"; para: Paragraph } | { kind: "table"; table: Table };

const ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
};

function decodeXml(text: string): string {
  return text.replace(/&(#x[0-9a-fA-F]+|#\d+|[a-z]+);/g, (whole, entity) => {
    if (entity.startsWith("#x")) return String.fromCodePoint(parseInt(entity.slice(2), 16));
    if (entity.startsWith("#")) return String.fromCodePoint(parseInt(entity.slice(1), 10));
    return ENTITIES[entity] ?? whole;
  });
}

function attribute(tag: string, name: string): string | null {
  const match = tag.match(new RegExp(`${name}="([^"]*)"`));
  return match ? decodeXml(match[1]) : null;
}

/** Visible text of one run body. Tabs and breaks become spaces. */
function runText(xml: string): string {
  let out = "";
  const re = /<w:t(?:\s[^>]*)?>([^<]*)<\/w:t>|<w:t(?:\s[^>]*)?\/>|<w:tab\/>|<w:br(?:\s[^>]*)?\/>|<w:noBreakHyphen\/>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml))) {
    if (m[0].startsWith("<w:t")) out += m[1] === undefined ? "" : decodeXml(m[1]);
    else if (m[0].startsWith("<w:noBreakHyphen")) out += "-";
    else out += " ";
  }
  return out;
}

function parseParagraph(xml: string, rels: Map<string, string>): Paragraph {
  const pPr = xml.match(/<w:pPr>[\s\S]*?<\/w:pPr>/)?.[0] ?? "";
  const style = pPr.match(/<w:pStyle w:val="([^"]+)"/)?.[1] ?? "";
  const numId = pPr.match(/<w:numPr>[\s\S]*?<w:numId w:val="(\d+)"/)?.[1] ?? null;
  const content = xml.slice(pPr.length ? xml.indexOf(pPr) + pPr.length : 0);

  const runs: Run[] = [];
  const re = /<w:hyperlink\b([^>]*)>([\s\S]*?)<\/w:hyperlink>|<w:r\b[^>]*>([\s\S]*?)<\/w:r>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content))) {
    if (m[1] !== undefined) {
      const id = attribute(m[1], "r:id");
      const href = id ? (rels.get(id) ?? null) : null;
      const text = [...m[2].matchAll(/<w:r\b[^>]*>([\s\S]*?)<\/w:r>/g)]
        .map((run) => runText(run[1]))
        .join("");
      runs.push({ text, href });
    } else {
      runs.push({ text: runText(m[3]), href: null });
    }
  }
  return { style, numId, runs };
}

/**
 * The paragraph as prose with link marks. Whitespace is collapsed and the
 * ends trimmed while the marks are placed, so every offset points into the
 * text that is actually written. Marks are tightened to exclude any spaces
 * a hyperlink run carries at either end.
 */
function richText(para: Paragraph): { text: string; links: LinkMark[] } {
  let out = "";
  const raw: LinkMark[] = [];

  const push = (text: string) => {
    for (const ch of text) {
      if (/[\s ]/.test(ch)) {
        if (out.length > 0 && !out.endsWith(" ")) out += " ";
      } else {
        out += ch;
      }
    }
  };

  for (const run of para.runs) {
    const start = out.length;
    push(run.text);
    if (run.href) raw.push({ start, end: out.length, href: run.href });
  }

  const text = out.replace(/ $/, "");
  const links = raw
    .map((mark) => {
      let start = mark.start;
      let end = Math.min(mark.end, text.length);
      while (start < end && text[start] === " ") start += 1;
      while (end > start && text[end - 1] === " ") end -= 1;
      return { start, end, href: mark.href };
    })
    .filter((mark) => mark.end > mark.start);

  return { text, links };
}

function paragraphText(para: Paragraph): string {
  return richText(para).text;
}

function tableEnd(xml: string, start: number): number {
  let depth = 0;
  const re = /<w:tbl>|<\/w:tbl>/g;
  re.lastIndex = start;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml))) {
    depth += m[0] === "<w:tbl>" ? 1 : -1;
    if (depth === 0) return m.index + m[0].length;
  }
  throw new Error("unterminated table");
}

function parseTable(xml: string, rels: Map<string, string>): Table {
  if (xml.indexOf("<w:tbl>", 1) !== -1) throw new Error("nested table");
  const links: string[] = [];
  const rows = [...xml.matchAll(/<w:tr\b[^>]*>([\s\S]*?)<\/w:tr>/g)].map((row) =>
    [...row[1].matchAll(/<w:tc\b[^>]*>([\s\S]*?)<\/w:tc>/g)].map((cell) =>
      [...cell[1].matchAll(/<w:p\b[^>]*>[\s\S]*?<\/w:p>/g)]
        .map((p) => {
          const rich = richText(parseParagraph(p[0], rels));
          links.push(...rich.links.map((mark) => mark.href));
          return rich.text;
        })
        .filter((text) => text.length > 0),
    ),
  );
  return { rows, links };
}

function parseBody(xml: string, rels: Map<string, string>): Node[] {
  const body = xml.slice(xml.indexOf("<w:body>"), xml.lastIndexOf("</w:body>"));
  const nodes: Node[] = [];
  const re = /<w:tbl>|<w:p(?=[\s>/])/g;
  let pos = 0;
  let m: RegExpExecArray | null;
  while ((re.lastIndex = pos), (m = re.exec(body))) {
    if (m[0] === "<w:tbl>") {
      const end = tableEnd(body, m.index);
      nodes.push({ kind: "table", table: parseTable(body.slice(m.index, end), rels) });
      pos = end;
      continue;
    }
    const close = body.indexOf(">", m.index);
    if (body[close - 1] === "/") {
      pos = close + 1;
      continue;
    }
    const end = body.indexOf("</w:p>", m.index) + "</w:p>".length;
    nodes.push({ kind: "p", para: parseParagraph(body.slice(m.index, end), rels) });
    pos = end;
  }
  return nodes;
}

function parseRels(xml: string): Map<string, string> {
  const rels = new Map<string, string>();
  for (const rel of xml.matchAll(/<Relationship\b[^>]*>/g)) {
    const id = attribute(rel[0], "Id");
    const target = attribute(rel[0], "Target");
    if (id && target && rel[0].includes("/hyperlink")) rels.set(id, target);
  }
  return rels;
}

/** numId -> true when the list is numbered rather than bulleted. */
function parseNumbering(xml: string): Map<string, boolean> {
  const formats = new Map<string, string>();
  for (const abstract of xml.matchAll(
    /<w:abstractNum\b[^>]*w:abstractNumId="(\d+)"[^>]*>([\s\S]*?)<\/w:abstractNum>/g,
  )) {
    const level0 = abstract[2].match(/<w:lvl\b[^>]*w:ilvl="0"[^>]*>([\s\S]*?)<\/w:lvl>/);
    const format = level0?.[1].match(/<w:numFmt w:val="([^"]+)"/)?.[1] ?? "bullet";
    formats.set(abstract[1], format);
  }
  const ordered = new Map<string, boolean>();
  for (const num of xml.matchAll(
    /<w:num\b[^>]*w:numId="(\d+)"[^>]*>[\s\S]*?<w:abstractNumId w:val="(\d+)"/g,
  )) {
    ordered.set(num[1], (formats.get(num[2]) ?? "bullet") !== "bullet");
  }
  return ordered;
}

type Docx = { nodes: Node[]; ordered: Map<string, boolean> };

function readDocx(path: string): Docx {
  const entries = readZip(readFileSync(path));
  const document = entries.get("word/document.xml")?.toString("utf8");
  if (!document) throw new Error("no word/document.xml");
  const rels = parseRels(entries.get("word/_rels/document.xml.rels")?.toString("utf8") ?? "");
  const ordered = parseNumbering(entries.get("word/numbering.xml")?.toString("utf8") ?? "");
  return { nodes: parseBody(document, rels), ordered };
}

/* ------------------------------------------------------- article parser */

const SEO_HEADING = "SEO and optimization notes (not for publication)";
const FAQ_HEADING = "Frequently asked questions";
const SOURCES_HEADING = "Sources";
const RELATED_HEADINGS = new Set(["Related reading", "Learn more"]);
const BYLINE = /^By \[Author name\], \[Title\], TalentRax Global\.\s*Last updated: ([A-Z][a-z]+) (\d{4})\.?\s*(.*)$/;
const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

type Parsed = {
  file: string;
  /** Link hrefs are still the document's own until the resolve pass runs. */
  article: Omit<Article, "id" | "datePublished" | "dateModified">;
  statedDate: { year: number; month: number; text: string };
  /** hrefs in the related-reading sections that were not article links */
  droppedCtaLinks: string[];
  /** closing call-to-action sections, dropped with their prose */
  droppedSections: string[];
  /** hrefs inside table cells, which are plain strings */
  tableLinks: string[];
  multiParagraphCells: number;
  bylineRemainder: string | null;
};

function isArticle(doc: Docx): boolean {
  return doc.nodes.some(
    (node) =>
      node.kind === "p" &&
      node.para.style === "Heading1" &&
      paragraphText(node.para) === SEO_HEADING,
  );
}

function headingLevel(style: string, file: string): 2 | 3 | null {
  if (style === "Heading1") return 2;
  if (style === "Heading2") return 3;
  if (/^Heading\d/.test(style)) throw new Error(`${file}: unexpected ${style}`);
  return null;
}

/** A RichText with the `links` key only when there is something in it. */
function prose(rich: { text: string; links: LinkMark[] }): RichText {
  return rich.links.length > 0 ? { text: rich.text, links: rich.links } : { text: rich.text };
}

function parseArticle(file: string, doc: Docx): Parsed {
  const fail = (message: string): Error => new Error(`${file}: ${message}`);
  const nodes = doc.nodes;
  let i = 0;

  const nextParagraph = (): Paragraph => {
    while (i < nodes.length) {
      const node = nodes[i];
      i += 1;
      if (node.kind === "p" && paragraphText(node.para)) return node.para;
      if (node.kind === "table") throw fail("expected a paragraph, found a table");
    }
    throw fail("ran out of paragraphs");
  };

  /* 1. title, byline, summary */
  const titlePara = nextParagraph();
  if (titlePara.style !== "Title") throw fail("first paragraph is not the Title");
  const title = paragraphText(titlePara);

  const bylineMatch = paragraphText(nextParagraph()).match(BYLINE);
  if (!bylineMatch) throw fail("byline not in the expected form");
  const monthIndex = MONTHS.indexOf(bylineMatch[1]);
  if (monthIndex < 0) throw fail(`unknown month "${bylineMatch[1]}"`);
  const statedDate = {
    year: Number(bylineMatch[2]),
    month: monthIndex + 1,
    text: `${bylineMatch[1]} ${bylineMatch[2]}`,
  };
  const bylineRemainder = bylineMatch[3].trim() || null;

  const summary = paragraphText(nextParagraph());

  /* 2. everything else, section by section */
  const body: ArticleBlock[] = [];
  const faqs: ArticleFaq[] = [];
  const sources: ArticleSource[] = [];
  const related: string[] = [];
  const droppedCtaLinks: string[] = [];
  const droppedSections: string[] = [];
  const tableLinks: string[] = [];
  let keyTakeaways: Article["keyTakeaways"] | null = null;
  let metaTitle: string | null = null;
  let metaDescription: string | null = null;
  let slug: string | null = null;
  let multiParagraphCells = 0;

  if (bylineRemainder) body.push({ kind: "paragraph", text: bylineRemainder });

  type Mode = "body" | "faq" | "related" | "sources" | "seo";
  let mode: Mode = "body";
  let openList: { numId: string; block: ArticleBlock & { kind: "list" } } | null = null;
  let openFaq: ArticleFaq | null = null;

  const closeList = () => {
    openList = null;
  };

  for (; i < nodes.length; i += 1) {
    const node = nodes[i];

    /* ---- tables */
    if (node.kind === "table") {
      closeList();
      const rows = node.table.rows;
      if (mode === "seo") {
        if (rows[0]?.[0]?.[0] === "Field" && rows[0]?.[1]?.[0] === "Recommendation") {
          for (const row of rows.slice(1)) {
            const field = row[0]?.join(" ");
            const value = row[1]?.join(" ") ?? "";
            if (field === "SEO title") metaTitle = value;
            if (field === "Meta description") metaDescription = value;
            if (field === "URL") slug = value;
          }
        }
        continue;
      }
      if (mode !== "body") throw fail(`table inside the ${mode} section`);
      tableLinks.push(...node.table.links);

      const isTakeaways =
        rows.length === 1 && rows[0].length === 1 && /^Key (takeaways|statistics)/.test(rows[0][0][0] ?? "");
      if (isTakeaways) {
        if (keyTakeaways) throw fail("two takeaways tables");
        const [heading, ...items] = rows[0][0];
        if (items.length === 0) throw fail("takeaways table has no items");
        keyTakeaways = { heading, items };
        continue;
      }

      const [headerRow, ...bodyRows] = rows;
      if (!headerRow || bodyRows.length === 0) throw fail("table with no body rows");
      const flatten = (row: string[][]) =>
        row.map((cell) => {
          if (cell.length > 1) multiParagraphCells += 1;
          return cell.join(" ");
        });
      const header = flatten(headerRow);
      const tableRows = bodyRows.map(flatten);
      if (tableRows.some((row) => row.length !== header.length)) throw fail("ragged table");
      body.push({ kind: "table", header, rows: tableRows });
      continue;
    }

    /* ---- paragraphs */
    const para = node.para;
    const rich = richText(para);
    const text = rich.text;
    if (!text) continue;
    const level = headingLevel(para.style, file);
    const links = para.runs.filter((run) => run.href).map((run) => run.href as string);

    if (level === 2) {
      closeList();
      openFaq = null;
      if (text === SEO_HEADING) mode = "seo";
      else if (text === FAQ_HEADING) mode = "faq";
      else if (text === SOURCES_HEADING) mode = "sources";
      else if (RELATED_HEADINGS.has(text)) mode = "related";
      else if (mode === "faq" || mode === "related") {
        // A closing call-to-action ("Hiring nurses for permanent roles?")
        // after the FAQ: link prose, handled like related reading.
        droppedSections.push(text);
        mode = "related";
      } else {
        if (mode !== "body") throw fail(`unexpected section "${text}" after the ${mode} section`);
        body.push({ kind: "heading", level: 2, text });
      }
      continue;
    }

    if (mode === "seo") continue;

    if (mode === "related") {
      for (const href of links) {
        const path = href.replace(SITE_ORIGIN, "");
        const match = path !== href ? path.match(/^\/insights\/([a-z0-9-]+)\/?$/) : null;
        if (match) {
          if (!related.includes(match[1])) related.push(match[1]);
        } else {
          droppedCtaLinks.push(href);
        }
      }
      continue;
    }

    if (mode === "sources") {
      if (level !== null) throw fail("heading inside Sources");
      if (para.numId === null) throw fail(`source outside a list: "${text}"`);
      // "Name: https://..." per link. An item that cites two documents
      // carries two links, separated by "; ", and yields two sources.
      let pending = "";
      for (const run of para.runs) {
        if (run.href) {
          const name = pending.replace(/\s+/g, " ").trim().replace(/^[;\s]+/, "").replace(/[:;\s]+$/, "");
          if (!name) throw fail(`source with no name before ${run.href}`);
          // A hyperlink target occasionally swallows the punctuation that
          // followed it in the text ("...fees;"). Trailing punctuation is
          // never part of a URL on these lists.
          sources.push({ name, url: run.href.replace(/[;,.)]+$/, "") });
          pending = "";
        } else {
          pending += run.text;
        }
      }
      if (pending.replace(/\s+/g, " ").trim().replace(/[;.\s]+$/, "")) {
        throw fail(`source text without a link: "${text}"`);
      }
      continue;
    }

    if (mode === "faq") {
      if (level === 3) {
        openFaq = { question: text, answer: [] };
        faqs.push(openFaq);
        continue;
      }
      if (!openFaq) throw fail(`FAQ text before the first question: "${text}"`);
      if (para.numId !== null) throw fail(`list inside an FAQ answer: "${text}"`);
      openFaq.answer.push(prose(rich));
      continue;
    }

    /* mode === "body" */
    if (level === 3) {
      closeList();
      body.push({ kind: "heading", level: 3, text });
      continue;
    }
    if (para.numId !== null || para.style === "ListParagraph") {
      if (para.numId === null) throw fail(`list paragraph without numbering: "${text}"`);
      if (!openList || openList.numId !== para.numId) {
        const block: ArticleBlock & { kind: "list" } = {
          kind: "list",
          ordered: doc.ordered.get(para.numId) ?? false,
          items: [],
        };
        body.push(block);
        openList = { numId: para.numId, block };
      }
      openList.block.items.push(prose(rich));
      continue;
    }
    closeList();
    body.push({ kind: "paragraph", ...prose(rich) });
  }

  /* 3. validate */
  if (!keyTakeaways) throw fail("no takeaways table");
  if (faqs.length === 0) throw fail("no FAQ section");
  if (faqs.some((faq) => faq.answer.length === 0)) throw fail("FAQ question without an answer");
  if (sources.length === 0) throw fail("no sources");
  if (!metaTitle || !metaDescription || !slug) throw fail("SEO table missing title, description or URL");
  if (!slug.startsWith("/insights/")) throw fail(`URL "${slug}" is not under /insights/`);
  slug = slug.slice("/insights/".length);
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw fail(`slug "${slug}" is not a clean URL segment`);
  if (mode !== "seo") throw fail("document ended before the SEO section");

  const article = fixBrand({
    slug,
    title,
    // The layout appends " | Talentrax Global" to every title itself.
    metaTitle: metaTitle.replace(/\s*\|\s*TalentRax(?: Global)?\s*$/i, ""),
    metaDescription,
    summary,
    keyTakeaways,
    body,
    faqs,
    sources,
    related,
  });

  return {
    file,
    article,
    statedDate,
    droppedCtaLinks,
    droppedSections,
    tableLinks,
    multiParagraphCells,
    bylineRemainder,
  };
}

/** "TalentRax" -> "Talentrax" in every string, however deep. */
function fixBrand<T>(value: T): T {
  if (typeof value === "string") return value.replace(/TalentRax/g, "Talentrax") as T;
  if (Array.isArray(value)) return value.map(fixBrand) as T;
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, inner]) => [key, fixBrand(inner)]),
    ) as T;
  }
  return value;
}

function everyString(value: unknown, out: string[] = []): string[] {
  if (typeof value === "string") out.push(value);
  else if (Array.isArray(value)) value.forEach((inner) => everyString(inner, out));
  else if (value && typeof value === "object") {
    Object.values(value).forEach((inner) => everyString(inner, out));
  }
  return out;
}

/* --------------------------------------------------------- link resolve */

type Restored = "article" | "page" | "external";

/** Where a document href ends up on this site, if anywhere. */
function resolveHref(
  href: string,
  slugs: Set<string>,
): { href: string; outcome: Restored } | null {
  if (SITE_ORIGIN.test(href)) {
    const rest = href.replace(SITE_ORIGIN, "") || "/";
    const [beforeHash, hash] = rest.split("#");
    const path = beforeHash.split("?")[0].replace(/\/$/, "") || "/";
    const article = path.match(/^\/insights\/([a-z0-9-]+)$/);
    if (article) {
      return slugs.has(article[1]) ? { href: path, outcome: "article" } : null;
    }
    const pageFile = join(APP_DIR, path === "/" ? "page.tsx" : `${path.slice(1)}/page.tsx`);
    if (existsSync(pageFile)) return { href: hash ? `${path}#${hash}` : path, outcome: "page" };
    return null;
  }
  if (/^https:\/\/[^\s/]+/.test(href)) return { href, outcome: "external" };
  return null;
}

/** Every RichText in an article, so the marks can be resolved in place. */
function proseOf(article: Parsed["article"]): RichText[] {
  const out: RichText[] = [];
  for (const block of article.body) {
    if (block.kind === "paragraph") out.push(block);
    if (block.kind === "list") out.push(...block.items);
  }
  for (const faq of article.faqs) out.push(...faq.answer);
  return out;
}

function checkMarks(rich: RichText, file: string): void {
  let last = 0;
  for (const mark of rich.links ?? []) {
    if (mark.start < last || mark.end <= mark.start || mark.end > rich.text.length) {
      throw new Error(`${file}: malformed link mark ${JSON.stringify(mark)} on "${rich.text}"`);
    }
    if (!/^(\/|https:\/\/)/.test(mark.href)) {
      throw new Error(`${file}: link mark with an unresolved href ${mark.href}`);
    }
    last = mark.end;
  }
}

/* --------------------------------------------------------------- output */

function articleFile(article: Article, file: string): string {
  return [
    "/**",
    ` * ${GENERATED_MARKER} from "${file}".`,
    " *",
    " * Do not edit by hand: the next import overwrites this file. Fix the",
    " * source document and re-run `npm run import:articles -- <dir>`.",
    " */",
    "",
    'import type { Article } from "../../lib/insights";',
    "",
    `export const article: Article = ${JSON.stringify(article, null, 2)};`,
    "",
  ].join("\n");
}

function indexFile(slugs: string[]): string {
  const identifier = (slug: string) =>
    "article_" + slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());
  return [
    "/**",
    ` * ${GENERATED_MARKER}: the index of every imported article.`,
    " *",
    " * Do not edit by hand. Adding or removing an article is a change to the",
    " * source documents followed by `npm run import:articles -- <dir>`.",
    " */",
    "",
    'import type { Article } from "../../lib/insights";',
    "",
    ...slugs.map((slug) => `import { article as ${identifier(slug)} } from "./${slug}.ts";`),
    "",
    "export const articles: Article[] = [",
    ...slugs.map((slug) => `  ${identifier(slug)},`),
    "];",
    "",
  ].join("\n");
}

type ExistingDates = { datePublished: string; dateModified: string } | null;

function existingDates(path: string): ExistingDates {
  if (!existsSync(path)) return null;
  const text = readFileSync(path, "utf8");
  const published = text.match(/"datePublished": "(\d{4}-\d{2}-\d{2})"/)?.[1];
  const modified = text.match(/"dateModified": "(\d{4}-\d{2}-\d{2})"/)?.[1];
  return published && modified ? { datePublished: published, dateModified: modified } : null;
}

/* ----------------------------------------------------------------- main */

const directory = resolve(sourceDir);
const files = readdirSync(directory)
  .filter((name) => name.toLowerCase().endsWith(".docx") && !name.startsWith("~$"))
  .sort();

const skipped: string[] = [];
const parsed: Parsed[] = [];

for (const file of files) {
  const doc = readDocx(join(directory, file));
  if (!isArticle(doc)) {
    skipped.push(file);
    continue;
  }
  parsed.push(parseArticle(file, doc));
}

/* cross-article validation */
const slugs = new Map<string, string>();
for (const item of parsed) {
  const other = slugs.get(item.article.slug);
  if (other) throw new Error(`slug "${item.article.slug}" is used by both ${other} and ${item.file}`);
  slugs.set(item.article.slug, item.file);
}
const slugSet = new Set(slugs.keys());

/* resolve every inline link now that the full slug set is known */
const restored: Record<Restored, number> = { article: 0, page: 0, external: 0 };
const droppedTargets: string[] = [];
for (const item of parsed) {
  for (const rich of proseOf(item.article)) {
    if (!rich.links) continue;
    const kept: LinkMark[] = [];
    for (const mark of rich.links) {
      const resolved = resolveHref(mark.href, slugSet);
      if (resolved === null) {
        droppedTargets.push(mark.href);
      } else {
        restored[resolved.outcome] += 1;
        kept.push({ ...mark, href: resolved.href });
      }
    }
    if (kept.length > 0) rich.links = kept;
    else delete rich.links;
    checkMarks(rich, item.file);
  }
}

for (const item of parsed) {
  for (const slug of item.article.related) {
    if (!slugSet.has(slug)) throw new Error(`${item.file}: related article "${slug}" was not imported`);
    if (slug === item.article.slug) throw new Error(`${item.file}: relates to itself`);
  }
  for (const source of item.article.sources) {
    if (!/^https:\/\/[^\s/]+/.test(source.url)) {
      throw new Error(`${item.file}: source "${source.name}" has a non-https URL: ${source.url}`);
    }
  }
  const strings = everyString(item.article);
  const offenders = strings.filter(
    (text) => /\[[A-Z]/.test(text) || /not for publication/i.test(text) || /TalentRax/.test(text),
  );
  if (offenders.length > 0) {
    throw new Error(`${item.file}: placeholder or unpublishable text survived:\n  ${offenders.join("\n  ")}`);
  }
}

/* dates and files */
const [importYear, importMonth] = importDate.split("-").map(Number);
const futureDated: { slug: string; stated: string }[] = [];

mkdirSync(OUTPUT_DIR, { recursive: true });
const written = new Set<string>();

for (const item of parsed.sort((a, b) => a.article.slug.localeCompare(b.article.slug))) {
  const { slug } = item.article;
  const path = join(OUTPUT_DIR, `${slug}.ts`);
  const { year, month } = item.statedDate;

  let sourceDate: string;
  if (year > importYear || (year === importYear && month > importMonth)) {
    futureDated.push({ slug, stated: item.statedDate.text });
    sourceDate = importDate;
  } else if (year === importYear && month === importMonth) {
    sourceDate = importDate;
  } else {
    sourceDate = `${year}-${String(month).padStart(2, "0")}-01`;
  }

  const existing = existingDates(path);
  let article: Article = {
    id: slug,
    ...item.article,
    datePublished: existing?.datePublished ?? sourceDate,
    dateModified: existing?.dateModified ?? sourceDate,
  };
  let text = articleFile(article, item.file);
  if (existing && readFileSync(path, "utf8") !== text) {
    article = { ...article, dateModified: importDate };
    text = articleFile(article, item.file);
  }
  writeFileSync(path, text);
  written.add(`${slug}.ts`);
}

writeFileSync(join(OUTPUT_DIR, "index.ts"), indexFile([...slugs.keys()].sort()));
written.add("index.ts");

/* remove generated files whose article is no longer in the source */
for (const name of readdirSync(OUTPUT_DIR)) {
  if (written.has(name)) continue;
  const path = join(OUTPUT_DIR, name);
  if (readFileSync(path, "utf8").includes(GENERATED_MARKER)) {
    rmSync(path);
    console.log(`removed stale ${name}`);
  }
}

/* ---------------------------------------------------------------- report */

const count = (items: string[]) =>
  [...items.reduce((m, s) => m.set(s, (m.get(s) ?? 0) + 1), new Map<string, number>())]
    .sort((a, b) => b[1] - a[1])
    .map(([key, n]) => `    ${String(n).padStart(3)}  ${key}`)
    .join("\n");
const stripOrigin = (href: string) => href.replace(SITE_ORIGIN, "");

console.log(`Imported ${parsed.length} article(s) into ${OUTPUT_DIR}`);
console.log(`Skipped ${skipped.length} file(s) with no "${SEO_HEADING}" section:`);
for (const file of skipped) console.log(`    ${file}`);

console.log(`\nSlugs (${parsed.length}):`);
for (const item of parsed) console.log(`    ${item.article.slug.padEnd(42)} <- ${item.file}`);

console.log(`\nStated dates later than the import date (${importDate}); imported with the import date instead (${futureDated.length}):`);
for (const entry of futureDated) console.log(`    ${entry.slug.padEnd(42)} "Last updated: ${entry.stated}"`);

const restoredTotal = restored.article + restored.page + restored.external;
console.log(`\nInline links restored as marks (${restoredTotal}):`);
console.log(`    ${String(restored.article).padStart(3)}  to another imported article`);
console.log(`    ${String(restored.page).padStart(3)}  to a page this site has`);
console.log(`    ${String(restored.external).padStart(3)}  external https`);
console.log(`\nInline links dropped, text kept, because the target does not exist here (${droppedTargets.length}):`);
console.log(count(droppedTargets.map(stripOrigin)));

const tableLinks = parsed.flatMap((p) => p.tableLinks);
console.log(`\nLinks inside table cells, dropped because cells are plain text (${tableLinks.length}):`);
if (tableLinks.length > 0) console.log(count(tableLinks.map(stripOrigin)));

const cta = parsed.flatMap((p) => p.droppedCtaLinks);
console.log(`\nRelated-reading links that were not article links, dropped with their prose (${cta.length}):`);
console.log(count(cta.map(stripOrigin)));

const sections = parsed.filter((p) => p.droppedSections.length > 0);
console.log(`\nClosing call-to-action sections after the FAQ, dropped with their prose (${sections.length}):`);
for (const item of sections) console.log(`    ${item.article.slug}: "${item.droppedSections.join('", "')}"`);

const notes = parsed.filter((p) => p.bylineRemainder);
console.log(`\nByline paragraphs with a trailing data note, kept as the first body paragraph (${notes.length}):`);
for (const item of notes) console.log(`    ${item.article.slug}: "${item.bylineRemainder}"`);

const multi = parsed.reduce((n, p) => n + p.multiParagraphCells, 0);
console.log(`\nBody table cells with more than one paragraph, joined with a space: ${multi}`);
